let urlsToCache = [
  '/',
  '/DPRHTML/dictionary-results.css',
  '/DPRHTML/dictionary-results.html',
  '/DPRHTML/dictionary.css',
  '/DPRHTML/dictionary.html',
  '/DPRHTML/favicon.png',
  '/DPRHTML/help.css',
  '/DPRHTML/help.html',
  '/DPRHTML/index.css',
  '/DPRHTML/index.html',
  '/DPRHTML/navigation.css',
  '/DPRHTML/navigation.html',
  '/DPRHTML/search-results.css',
  '/DPRHTML/search-results.html',
  '/DPRHTML/search.css',
  '/DPRHTML/search.html',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/FontAwesome.otf',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/fontawesome-webfont.eot',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/fontawesome-webfont.svg',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/fontawesome-webfont.ttf',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/fontawesome-webfont.woff',
  'digitalpalireader/content/js/external/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2',
  '/digitalpalireader/content/js/external/ui/1.12.1/themes/base/jquery-ui.css',
  '/digitalpalireader/content/js/external/bootstrap/4.4.1/css/bootstrap.min.css',
  '/digitalpalireader/content/js/external/font-awesome/4.7.0/css/font-awesome.min.css',
  '/digitalpalireader/content/js/external/jquery-3.2.1.min.js',
  '/digitalpalireader/content/js/external/ui/1.12.1/jquery-ui.min.js',
  '/digitalpalireader/content/js/external/ajax/libs/popper.js/1.12.9/umd/popper.min.js',
  '/digitalpalireader/content/js/external/bootstrap/4.0.0/js/bootstrap.min.js',
  '/digitalpalireader/content/js/dpr_pal.js',
  '/digitalpalireader/content/dev.js',
  '/digitalpalireader/content/js/web/io.js',
  '/digitalpalireader/content/js/send.js',
  '/digitalpalireader/content/js/receive.js',
  '/digitalpalireader/content/js/web/chrome_sidebar.js',
  '/digitalpalireader/content/js/web/send_sidebar.js',
  '/digitalpalireader/content/js/dhpv.js',
  '/digitalpalireader/content/js/navigation_common.js',
  '/digitalpalireader/content/js/web/navigation_sidebar.js',
  '/digitalpalireader/content/js/prefload.js',
  '/digitalpalireader/content/js/web/xml_sidebar.js',
  '/digitalpalireader/content/js/translit.js',
  '/digitalpalireader/content/js/config.js',
  '/digitalpalireader/content/js/xml_load.js',
  '/digitalpalireader/content/js/navigation.js',
  '/digitalpalireader/content/js/format.js',
  '/digitalpalireader/content/js/web/opts_sidebar.js',
  '/digitalpalireader/content/js/relmul.js',
  '/digitalpalireader/content/js/relatt.js',
  '/digitalpalireader/content/js/reltik.js',
  '/digitalpalireader/content/js/dppn.js',
  '/digitalpalireader/content/js/translations.js',
  '/digitalpalireader/content/js/xml.js',
  '/digitalpalireader/content/js/history.js',
  '/digitalpalireader/content/js/web/search.js',
  '/digitalpalireader/content/js/search.js',
  '/digitalpalireader/content/js/search_history.js',
  '/digitalpalireader/content/js/sortaz.js',
  '/digitalpalireader/content/js/dict.js',
  '/digitalpalireader/content/js/irreg.js',
  '/digitalpalireader/content/js/dict_xml.js',
  '/digitalpalireader/content/js/listsm.js',
  '/digitalpalireader/content/js/listam.js',
  '/digitalpalireader/content/js/chrome.js',
  '/digitalpalireader/content/js/convert.js',
  '/digitalpalireader/content/js/move.js',
  '/digitalpalireader/content/js/analysis_declension.js',
  '/digitalpalireader/content/js/analysis_arrays.js',
  '/digitalpalireader/content/js/analysis_function.js',
  '/digitalpalireader/content/js/analysis_output.js',
  '/digitalpalireader/content/js/inflect.js',
  '/digitalpalireader/content/js/grammar.js',
  '/digitalpalireader/content/js/ped.js',
  '/digitalpalireader/content/js/nameno.js',
  '/digitalpalireader/content/js/english.js',
  '/digitalpalireader/content/js/epd.js',
  '/digitalpalireader/content/js/roots.js',
  '/digitalpalireader/content/js/roots_link.js',
  '/digitalpalireader/content/js/skt.js',
  '/digitalpalireader/content/js/skt_roots.js',
  '/digitalpalireader/content/js/attlist.js',
  '/digitalpalireader/content/js/tiklist.js',
  '/digitalpalireader/content/js/titles.js',
  '/digitalpalireader/content/js/web/sidebar.js',
  '/digitalpalireader/content/etc/XML1/0/ped.xml',
  '/digitalpalireader/content/etc/XML1/1/ped.xml',
  '/digitalpalireader/content/etc/XML1/2/ped.xml',
  '/digitalpalireader/content/etc/XML1/3/ped.xml',
  '/digitalpalireader/content/etc/XML1/4/ped.xml',
  '/digitalpalireader/content/etc/XML2/1.xml',
  '/digitalpalireader/content/etc/XML2/2.xml',
  '/digitalpalireader/content/etc/XML2/3.xml',
  '/digitalpalireader/content/etc/XML2/4.xml',
  '/digitalpalireader/content/etc/XML2/5.xml',
  '/digitalpalireader/content/etc/XML2/6.xml',
  '/digitalpalireader/content/etc/XML2/7.xml',
  '/digitalpalireader/content/etc/XML2/8.xml',
  '/digitalpalireader/content/etc/XML2/9.xml',
  '/digitalpalireader/content/etc/XML2/10.xml',
  '/digitalpalireader/content/etc/XML2/abbrev.xml',
  '/DPRMyanmar/content/xml/a10a.xml',
  '/DPRMyanmar/content/xml/a10m.xml',
  '/DPRMyanmar/content/xml/a10t.xml',
  '/DPRMyanmar/content/xml/a11a.xml',
  '/DPRMyanmar/content/xml/a11m.xml',
  '/DPRMyanmar/content/xml/a11t.xml',
  '/DPRMyanmar/content/xml/a1a.xml',
  '/DPRMyanmar/content/xml/a1m.xml',
  '/DPRMyanmar/content/xml/a1t.xml',
  '/DPRMyanmar/content/xml/a2a.xml',
  '/DPRMyanmar/content/xml/a2m.xml',
  '/DPRMyanmar/content/xml/a2t.xml',
  '/DPRMyanmar/content/xml/a3a.xml',
  '/DPRMyanmar/content/xml/a3m.xml',
  '/DPRMyanmar/content/xml/a3t.xml',
  '/DPRMyanmar/content/xml/a4a.xml',
  '/DPRMyanmar/content/xml/a4m.xml',
  '/DPRMyanmar/content/xml/a4t.xml',
  '/DPRMyanmar/content/xml/a5a.xml',
  '/DPRMyanmar/content/xml/a5m.xml',
  '/DPRMyanmar/content/xml/a5t.xml',
  '/DPRMyanmar/content/xml/a6a.xml',
  '/DPRMyanmar/content/xml/a6m.xml',
  '/DPRMyanmar/content/xml/a6t.xml',
  '/DPRMyanmar/content/xml/a7a.xml',
  '/DPRMyanmar/content/xml/a7m.xml',
  '/DPRMyanmar/content/xml/a7t.xml',
  '/DPRMyanmar/content/xml/a8a.xml',
  '/DPRMyanmar/content/xml/a8m.xml',
  '/DPRMyanmar/content/xml/a8t.xml',
  '/DPRMyanmar/content/xml/a9a.xml',
  '/DPRMyanmar/content/xml/a9m.xml',
  '/DPRMyanmar/content/xml/a9t.xml',
  '/DPRMyanmar/content/xml/b1m.xml',
  '/DPRMyanmar/content/xml/b2m.xml',
  '/DPRMyanmar/content/xml/d1a.xml',
  '/DPRMyanmar/content/xml/d1m.xml',
  '/DPRMyanmar/content/xml/d1t.xml',
  '/DPRMyanmar/content/xml/d2a.xml',
  '/DPRMyanmar/content/xml/d2m.xml',
  '/DPRMyanmar/content/xml/d2t.xml',
  '/DPRMyanmar/content/xml/d3a.xml',
  '/DPRMyanmar/content/xml/d3m.xml',
  '/DPRMyanmar/content/xml/d3t.xml',
  '/DPRMyanmar/content/xml/g1m.xml',
  '/DPRMyanmar/content/xml/g2m.xml',
  '/DPRMyanmar/content/xml/g3m.xml',
  '/DPRMyanmar/content/xml/g4m.xml',
  '/DPRMyanmar/content/xml/g5m.xml',
  '/DPRMyanmar/content/xml/k10a.xml',
  '/DPRMyanmar/content/xml/k10m.xml',
  '/DPRMyanmar/content/xml/k11m.xml',
  '/DPRMyanmar/content/xml/k12a.xml',
  '/DPRMyanmar/content/xml/k12m.xml',
  '/DPRMyanmar/content/xml/k13a.xml',
  '/DPRMyanmar/content/xml/k13m.xml',
  '/DPRMyanmar/content/xml/k14a.xml',
  '/DPRMyanmar/content/xml/k14m.xml',
  '/DPRMyanmar/content/xml/k15a.xml',
  '/DPRMyanmar/content/xml/k15m.xml',
  '/DPRMyanmar/content/xml/k16m.xml',
  '/DPRMyanmar/content/xml/k17m.xml',
  '/DPRMyanmar/content/xml/k18m.xml',
  '/DPRMyanmar/content/xml/k19m.xml',
  '/DPRMyanmar/content/xml/k1a.xml',
  '/DPRMyanmar/content/xml/k1m.xml',
  '/DPRMyanmar/content/xml/k20m.xml',
  '/DPRMyanmar/content/xml/k21m.xml',
  '/DPRMyanmar/content/xml/k2a.xml',
  '/DPRMyanmar/content/xml/k2m.xml',
  '/DPRMyanmar/content/xml/k3a.xml',
  '/DPRMyanmar/content/xml/k3m.xml',
  '/DPRMyanmar/content/xml/k4a.xml',
  '/DPRMyanmar/content/xml/k4m.xml',
  '/DPRMyanmar/content/xml/k5a.xml',
  '/DPRMyanmar/content/xml/k5m.xml',
  '/DPRMyanmar/content/xml/k6a.xml',
  '/DPRMyanmar/content/xml/k6m.xml',
  '/DPRMyanmar/content/xml/k7a.xml',
  '/DPRMyanmar/content/xml/k7m.xml',
  '/DPRMyanmar/content/xml/k8a.xml',
  '/DPRMyanmar/content/xml/k8m.xml',
  '/DPRMyanmar/content/xml/k9a.xml',
  '/DPRMyanmar/content/xml/k9m.xml',
  '/DPRMyanmar/content/xml/m1a.xml',
  '/DPRMyanmar/content/xml/m1m.xml',
  '/DPRMyanmar/content/xml/m1t.xml',
  '/DPRMyanmar/content/xml/m2a.xml',
  '/DPRMyanmar/content/xml/m2m.xml',
  '/DPRMyanmar/content/xml/m2t.xml',
  '/DPRMyanmar/content/xml/m3a.xml',
  '/DPRMyanmar/content/xml/m3m.xml',
  '/DPRMyanmar/content/xml/m3t.xml',
  '/DPRMyanmar/content/xml/n1m.xml',
  '/DPRMyanmar/content/xml/n2m.xml',
  '/DPRMyanmar/content/xml/n3m.xml',
  '/DPRMyanmar/content/xml/n4m.xml',
  '/DPRMyanmar/content/xml/n5m.xml',
  '/DPRMyanmar/content/xml/n6m.xml',
  '/DPRMyanmar/content/xml/n7m.xml',
  '/DPRMyanmar/content/xml/n8m.xml',
  '/DPRMyanmar/content/xml/n9m.xml',
  '/DPRMyanmar/content/xml/s1a.xml',
  '/DPRMyanmar/content/xml/s1m.xml',
  '/DPRMyanmar/content/xml/s1t.xml',
  '/DPRMyanmar/content/xml/s2a.xml',
  '/DPRMyanmar/content/xml/s2m.xml',
  '/DPRMyanmar/content/xml/s2t.xml',
  '/DPRMyanmar/content/xml/s3a.xml',
  '/DPRMyanmar/content/xml/s3m.xml',
  '/DPRMyanmar/content/xml/s3t.xml',
  '/DPRMyanmar/content/xml/s4a.xml',
  '/DPRMyanmar/content/xml/s4m.xml',
  '/DPRMyanmar/content/xml/s4t.xml',
  '/DPRMyanmar/content/xml/s5a.xml',
  '/DPRMyanmar/content/xml/s5m.xml',
  '/DPRMyanmar/content/xml/s5t.xml',
  '/DPRMyanmar/content/xml/v10t.xml',
  '/DPRMyanmar/content/xml/v11t.xml',
  '/DPRMyanmar/content/xml/v12t.xml',
  '/DPRMyanmar/content/xml/v13t.xml',
  '/DPRMyanmar/content/xml/v14t.xml',
  '/DPRMyanmar/content/xml/v15t.xml',
  '/DPRMyanmar/content/xml/v16t.xml',
  '/DPRMyanmar/content/xml/v17t.xml',
  '/DPRMyanmar/content/xml/v18t.xml',
  '/DPRMyanmar/content/xml/v1a.xml',
  '/DPRMyanmar/content/xml/v1m.xml',
  '/DPRMyanmar/content/xml/v1t.xml',
  '/DPRMyanmar/content/xml/v2a.xml',
  '/DPRMyanmar/content/xml/v2m.xml',
  '/DPRMyanmar/content/xml/v2t.xml',
  '/DPRMyanmar/content/xml/v3a.xml',
  '/DPRMyanmar/content/xml/v3m.xml',
  '/DPRMyanmar/content/xml/v3t.xml',
  '/DPRMyanmar/content/xml/v4a.xml',
  '/DPRMyanmar/content/xml/v4m.xml',
  '/DPRMyanmar/content/xml/v4t.xml',
  '/DPRMyanmar/content/xml/v5a.xml',
  '/DPRMyanmar/content/xml/v5m.xml',
  '/DPRMyanmar/content/xml/v5t.xml',
  '/DPRMyanmar/content/xml/v6a.xml',
  '/DPRMyanmar/content/xml/v6m.xml',
  '/DPRMyanmar/content/xml/v6t.xml',
  '/DPRMyanmar/content/xml/v7t.xml',
  '/DPRMyanmar/content/xml/v8t.xml',
  '/DPRMyanmar/content/xml/v9t.xml',
  '/DPRMyanmar/content/xml/x1a.xml',
  '/DPRMyanmar/content/xml/x1m.xml',
  '/DPRMyanmar/content/xml/x2a.xml',
  '/DPRMyanmar/content/xml/x2m.xml',
  '/DPRMyanmar/content/xml/y10m.xml',
  '/DPRMyanmar/content/xml/y11m.xml',
  '/DPRMyanmar/content/xml/y12m.xml',
  '/DPRMyanmar/content/xml/y13m.xml',
  '/DPRMyanmar/content/xml/y14m.xml',
  '/DPRMyanmar/content/xml/y1a.xml',
  '/DPRMyanmar/content/xml/y1m.xml',
  '/DPRMyanmar/content/xml/y1t.xml',
  '/DPRMyanmar/content/xml/y2a.xml',
  '/DPRMyanmar/content/xml/y2m.xml',
  '/DPRMyanmar/content/xml/y2t.xml',
  '/DPRMyanmar/content/xml/y3a.xml',
  '/DPRMyanmar/content/xml/y3m.xml',
  '/DPRMyanmar/content/xml/y3t.xml',
  '/DPRMyanmar/content/xml/y4a.xml',
  '/DPRMyanmar/content/xml/y4m.xml',
  '/DPRMyanmar/content/xml/y4t.xml',
  '/DPRMyanmar/content/xml/y5a.xml',
  '/DPRMyanmar/content/xml/y5m.xml',
  '/DPRMyanmar/content/xml/y5t.xml',
  '/DPRMyanmar/content/xml/y6a.xml',
  '/DPRMyanmar/content/xml/y6m.xml',
  '/DPRMyanmar/content/xml/y6t.xml',
  '/DPRMyanmar/content/xml/y7m.xml',
  '/DPRMyanmar/content/xml/y8m.xml',
  '/DPRMyanmar/content/xml/y9a.xml',
  '/DPRMyanmar/content/xml/y9m.xml',
  '/DPRMyanmar/content/xml/y9t.xml',
  '/DPRThai/content/xml/a10m.xml',
  '/DPRThai/content/xml/a11m.xml',
  '/DPRThai/content/xml/a1m.xml',
  '/DPRThai/content/xml/a2m.xml',
  '/DPRThai/content/xml/a3m.xml',
  '/DPRThai/content/xml/a4m.xml',
  '/DPRThai/content/xml/a5m.xml',
  '/DPRThai/content/xml/a6m.xml',
  '/DPRThai/content/xml/a7m.xml',
  '/DPRThai/content/xml/a8m.xml',
  '/DPRThai/content/xml/a9m.xml',
  '/DPRThai/content/xml/d1m.xml',
  '/DPRThai/content/xml/d2m.xml',
  '/DPRThai/content/xml/d3m.xml',
  '/DPRThai/content/xml/k1m.xml',
  '/DPRThai/content/xml/k2m.xml',
  '/DPRThai/content/xml/k3m.xml',
  '/DPRThai/content/xml/k4m.xml',
  '/DPRThai/content/xml/k5m.xml',
  '/DPRThai/content/xml/m1m.xml',
  '/DPRThai/content/xml/m2m.xml',
  '/DPRThai/content/xml/m3m.xml',
  '/DPRThai/content/xml/s1m.xml',
  '/DPRThai/content/xml/s2m.xml',
  '/DPRThai/content/xml/s3m.xml',
  '/DPRThai/content/xml/s4m.xml',
  '/DPRThai/content/xml/s5m.xml',
  '/DPRThai/content/xml/v1m.xml',
  '/DPRThai/content/xml/v2m.xml',
  '/DPRThai/content/xml/v3m.xml',
  '/DPRThai/content/xml/v4m.xml',
  '/DPRThai/content/xml/v5m.xml',
  '/DPRThai/content/xml/v6m.xml'
];
let CACHE_1 = 'dpr-cache-v1';
let CACHE_2 = 'dpr-cache-v2';

self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CACHE_1)
      .then(function(cache) {
        console.log('Opened cache');
        return cache.addAll(urlsToCache);
      })
  );
});

self.addEventListener('fetch', function(event) {
  event.respondWith(
    caches.match(event.request)
      .then(function(response) {
        if (response) {
          return response;
        } else {
          // fetch from internet
          return fetch(event.request)
            .then(function(response) {
              return caches.open(CACHE_1)
                .then(function(cache) {
                  cache.put(event.request.url, response.clone());
                  return response;
                })
            })
            // fallback
            .catch(function(err) {
              return caches.open(CACHE_1)
                .then(function(cache) {
                  return cache.match('/DPRHTML/index.html');
                });
            });
        }
      }
    )
  );
});

self.addEventListener('activate', function(event) {

  var cacheWhitelist = [CACHE_1, CACHE_2];

  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.map(function(cacheName) {
          if (cacheWhitelist.indexOf(cacheName) === -1) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});

