	var prem = new Array();
	var preach = new Array();
	var pra = 0;
	var prb = 0;
	var prc = 0;
	var prd = 0;
	var prcount = 0;
	var prany = 0;
	// in the following: 1=to be found, 2=cut offset, 3=length of stem must be greater than this, 4=whattoadd
	prem.push('o^0^0^a');
	prem.push('e^0^0^a');
	prem.push('i^0^3^ati');
	prem.push('a^1^0^a');
	prem.push('a,m^1^0');
	prem.push('a,m^1^0^a');
	prem.push('i,m^1^0');
	prem.push('u,m^1^0'); 
	prem.push('yo^0^1'); 
	prem.push('to^0^1');
	prem.push('aa^1^3^nt');
	prem.push('aa^1^0');
	prem.push('ii^1^0');
	prem.push('uu^1^0');
	prem.push('tu^0^3^ti');
	prem.push('si^0^3^ti');
	prem.push('ahi^1^1');
	prem.push('asu^1^1');
	prem.push('anna,m^1^1');
	prem.push('unna,m^1^1');
	prem.push('inna,m^1^1');
	prem.push('avo^0^0^u');
	prem.push('ato^1^2^nt');
	prem.push('ato^1^2^ti');
	prem.push('anto^3^1');
	prem.push('anto^1^1^ti');
	prem.push('ataa^1^1^nt');
	prem.push('ataa^2^1^i');
	prem.push('ayo^0^1^i');
	prem.push('ehi^0^0^a');
	prem.push('ena^0^0^a');
	prem.push('esu^0^0^a');
	prem.push('ino^0^0');
	prem.push('mhi^0^0');
	prem.push('asi^0^0^ti'); 
	prem.push('esi^0^0^ti');
	prem.push('osi^0^0^ti');
	prem.push('omi^0^0^ti');
	prem.push('oma^0^0^ti');
	prem.push('emi^0^0^ti');
	prem.push('ema^0^0^ti');
	prem.push('smaa^0^2'); 
	prem.push('mhaa^0^0');
	prem.push('ataa^1^0^nt');
	prem.push('anta,m^3^0');
	prem.push('aaya^1^0'); 
	prem.push('aahi^1^0');
	prem.push('aasu^1^0');
	prem.push('aayo^1^0');
	prem.push('iihi^1^0');
	prem.push('iisu^1^0');
	prem.push('uuhi^1^0');
	prem.push('uusu^1^0');
	prem.push('assa^1^0'); 
	prem.push('ebhi^0^0^a');
	prem.push('aani^1^0');
	prem.push('ino^1^0');
	prem.push('inaa^1^0');
	prem.push('iyaa^1^0');
	prem.push('issa^1^0');
	prem.push('uno^1^0');
	prem.push('unaa^1^0');
	prem.push('uyaa^1^0');
	prem.push('ussa^1^0');
	prem.push('anti^1^0^ti');
	prem.push('aami^1^0^ti');
	prem.push('aama^1^0^ti');
	prem.push('atha^1^0^ti');
	prem.push('antu^1^1^ti');
	prem.push('onti^1^0^ti');
	prem.push('otha^1^0^ti');
	prem.push('ontu^1^0^ti');
	prem.push('emi^1^0^ti');
	prem.push('enti^1^0^ti');
	prem.push('etha^1^0^ti');
	prem.push('entu^1^0^ti');
	prem.push('smi,m^0^0');
	
	prem.push('maano^0^2^ti');
	prem.push('maanaa^0^2^ti');
	prem.push('maana,m^0^2^ti');
	prem.push('maane^0^2^ti');
	prem.push('maanena^0^2^ti');
	prem.push('maanehi^0^2^ti');
	prem.push('maanassa^0^2^ti');
	prem.push('maanaana,m^0^2^ti');
	prem.push('maanasmi,m^0^2^ti');
	prem.push('maanesu^0^2^ti');
	
	prem.push('iya,m^0^0');
	prem.push('uya,m^0^0');
	prem.push('asmaa^0^0');
	prem.push('amhaa^0^0');
	prem.push('itvaa^0^0^ati'); 
	prem.push('tvaa^0^0^ti'); 
	prem.push('itu,m^0^0^ati');
	prem.push('eyya^0^0^ati');
	prem.push('eyyu,m^0^0^ati');
	prem.push('imhaa^0^0'); // aorist
	prem.push('i,msu^0^1^ati'); // aorist
	prem.push('ittha^0^0'); // aorist
	prem.push('aana,m^1^0'); 
	prem.push('aaya,m^1^0'); 
	prem.push('iina,m^1^0'); 
	prem.push('iiya,m^1^0'); 
	prem.push('uuna,m^1^0'); 
	prem.push('uuya,m^1^0'); 
	prem.push('abba,m^1^1');
	prem.push('anta,m^0^0');
	prem.push('eyya^1^0^ti');
	prem.push('eyyati^0^0^ati');
	prem.push('eyyasi^0^0^ati');
	prem.push('issati^0^0^ati');
	prem.push('issasi^0^0^ati');
	prem.push('issanti^0^0^ati');
	prem.push('issatha^0^0^ati');
	prem.push('issaami^0^0^ati');
	prem.push('issaama^0^0^ati');
	prem.push('ssasi^0^0^ti');
	prem.push('ssati^0^0^ti');
	prem.push('ssanti^0^0^ti');
	prem.push('ssatha^0^0^ti');
	prem.push('ssaami^0^0^ti');
	prem.push('ssaama^0^0^ti');
	prem.push('eyyatha^0^0^ati');
	prem.push('eyyaami^0^0^ati');
	prem.push('eyyaasi^0^0^ati');
	prem.push('eyyaama^0^0^ati');
	prem.push('eyyanti^0^0^ati');

	prem.push('aapetvaa^1^0^ti');

	prem.push('iya,m^1^7');
