	var prem = new Array();
	var preach = new Array();
	var pra = 0;
	var prb = 0;
	var prc = 0;
	var prd = 0;
	var prcount = 0;
	var prany = 0;
	// in the following: 1=to be found, 2=wheretofind, 3=whattocut, 4=minimumlength, 5=whattoadd
	prem.push('o^1^1^0^a');
	prem.push('e^1^1^0^a');
	prem.push('i^1^1^4^ati');
	prem.push('a^1^0^4^a');
	prem.push('a,m^3^2^0');
	prem.push('a,m^3^2^0^a');
	prem.push('i,m^3^2^0');
	prem.push('~n^2^2^0'); // compound special
	prem.push('m^1^1^0'); // compound special
	prem.push('u,m^3^2^0'); 
	prem.push('yo^2^2^0'); 
	prem.push('to^2^2^0');
	prem.push('aa^2^1^3^nt');
	prem.push('aa^2^1^0');
	prem.push('ii^2^1^0');
	prem.push('uu^2^1^0');
	prem.push('tu^2^2^0^ti');
	prem.push('si^2^2^0^ti');
	prem.push('ahi^3^2^5');
	prem.push('asu^3^2^5');
	prem.push('anna,m^5^4^8');
	prem.push('avo^3^3^0^u');
	prem.push('no^2^2^6');
	prem.push('naa^3^3^7');
	prem.push('ato^3^2^6^nt');
	prem.push('ato^3^2^6^nt');
	prem.push('anto^4^1^6');
	prem.push('ataa^4^3^6^nt');
	prem.push('ayo^3^3^4^i');
	prem.push('ehi^3^3^0^a');
	prem.push('ena^3^3^0^a');
	prem.push('esu^3^3^0^a');
	prem.push('ino^2^2^0');
	prem.push('mhi^3^3');
	prem.push('asi^2^2^0^ti'); 
	prem.push('esi^2^2^0^ti');
	prem.push('osi^2^2^0^ti');
	prem.push('omi^2^2^0^ti');
	prem.push('oma^2^2^0^ti');
	prem.push('emi^2^2^0^ti');
	prem.push('ema^2^2^0^ti');
	prem.push('smaa^4^4^7'); 
	prem.push('mhaa^4^4^0');
	prem.push('ataa^4^3^0^nt');
	prem.push('anta,m^6^3^0');
	prem.push('aaya^4^3^0'); 
	prem.push('aahi^4^3^0');
	prem.push('aasu^4^3^0');
	prem.push('aayo^4^3^0');
	prem.push('iihi^4^3^0');
	prem.push('iisu^4^3^0');
	prem.push('uuhi^4^3^0');
	prem.push('uusu^4^3^0');
	prem.push('assa^4^4^0^a'); 
	prem.push('ebhi^4^4^0^a');
	prem.push('aani^4^4^0^a');
	prem.push('ino^3^2^0');
	prem.push('inaa^4^3^0');
	prem.push('iyaa^4^3^0');
	prem.push('issa^4^3^0');
	prem.push('uno^3^2^0');
	prem.push('unaa^4^3^0');
	prem.push('uyaa^4^3^0');
	prem.push('ussa^4^3^0');
	prem.push('anti^4^3^0^ti');
	prem.push('aami^4^3^0^ti');
	prem.push('aama^4^3^0^ti');
	prem.push('atha^4^3^0^ti');
	prem.push('antu^4^3^0^ti');
	prem.push('onti^4^3^0^ti');
	prem.push('otha^4^3^0^ti');
	prem.push('ontu^4^3^0^ti');
	prem.push('emi^3^2^0^ti');
	prem.push('enti^4^3^0^ti');
	prem.push('etha^4^3^0^ti');
	prem.push('entu^4^3^0^ti');
	prem.push('smi,m^5^5^0');
	prem.push('maano^5^5^0^ti');
	prem.push('antam^5^2^8'); // compound special
	prem.push('iya,m^4^4^0');
	prem.push('uya,m^4^4^0');
	prem.push('asmaa^4^4^0');
	prem.push('amhaa^4^4^0');
	prem.push('itvaa^5^5^0^ati'); 
	prem.push('tvaa^4^4^0^ti'); 
	prem.push('itu,m^5^5^0^ati');
	prem.push('eyya^4^4^0^ati');
	prem.push('eyyu,m^6^6^0^ati');
	prem.push('imhaa^5^5^0'); // aorist
	prem.push('i,msu^5^5^7^ati'); // aorist
	prem.push('ittha^5^5^0'); // aorist
	prem.push('aana,m^6^5^0'); 
	prem.push('aaya,m^6^5^0'); 
	prem.push('iina,m^6^5^0'); 
	prem.push('iiya,m^6^5^0'); 
	prem.push('uuna,m^6^5^0'); 
	prem.push('uuya,m^6^5^0'); 
	prem.push('abba,m^6^5^7');
	prem.push('anta,m^3^3^0');
	prem.push('eyya^4^3^0^ti');
	prem.push('eyyati^6^6^0^ati');
	prem.push('eyyasi^6^6^0^ati');
	prem.push('issati^6^6^0^ati');
	prem.push('issasi^6^6^0^ati');
	prem.push('issanti^7^7^0^ati');
	prem.push('issatha^7^7^0^ati');
	prem.push('issaami^7^7^0^ati');
	prem.push('issaama^7^7^0^ati');
	prem.push('ssasi^5^5^0^ti');
	prem.push('ssati^5^5^0^ti');
	prem.push('ssanti^6^6^0^ti');
	prem.push('ssatha^6^6^0^ti');
	prem.push('ssaami^6^6^0^ti');
	prem.push('ssaama^6^6^0^ti');
	prem.push('eyyatha^7^7^0^ati');
	prem.push('eyyaami^7^7^0^ati');
	prem.push('eyyaasi^7^7^0^ati');
	prem.push('eyyaama^7^7^0^ati');
	prem.push('eyyanti^7^7^0^ati');

	prem.push('aapetvaa^8^7^0^ti');

	prem.push('iya,m^5^4^7');
