
var irregda = [];

// Irregular Verbs

// removed: abhijaanaati = abhijaanaati
irregda["abhijaananti"] = mainda["abhijaanaati"];
irregda["abhijaanaasi"] = mainda["abhijaanaati"];
irregda["abhijaanaatha"] = mainda["abhijaanaati"];
irregda["abhijaanaami"] = mainda["abhijaanaati"];
irregda["abhijaanaama"] = mainda["abhijaanaati"];

irregda["abhijaanaahi"] = mainda["abhijaanaati"];
irregda["abhijaanissati"] = mainda["abhijaanaati"];
irregda["abhijaanissanti"] = mainda["abhijaanaati"];
irregda["abhijaanissasi"] = mainda["abhijaanaati"];
irregda["abhijaanissatha"] = mainda["abhijaanaati"];
irregda["abhijaanissaami"] = mainda["abhijaanaati"];
irregda["abhijaanissaama"] = mainda["abhijaanaati"];
irregda["abhijaaneyya"] = mainda["abhijaanaati"];
irregda["abhija~n~naa"] = mainda["abhijaanaati"];
// removed: abhisa`nkharoti = abhisa`nkharoti
irregda["abhisa`nkharonti"] = mainda["abhisa`nkharoti"];
irregda["abhisa`nkhareyya"] = mainda["abhisa`nkharoti"];
irregda["abhisa`nkhareyya,m"] = mainda["abhisa`nkharoti"];
// removed: acchati = acchati
irregda["acchanti"] = mainda["acchati"];
irregda["acchenti"] = mainda["acchati"];
irregda["acchasi"] = mainda["acchati"];
irregda["acchaami"] = mainda["acchati"];
irregda["acchatu"] = mainda["acchati"];
irregda["accha"] = mainda["acchati"];
irregda["accheyya"] = mainda["acchati"];
irregda["acchata,m"] = mainda["acchati"];
irregda["acchassu"] = mainda["acchati"];
// removed: aadadaati = aadadaati
// removed: addasa = addasa
// removed: addasaa = addasaa
irregda["addasa,msu"] = mainda["dakkhati"];
// removed: addasaa = addasaa
irregda["addasatha"] = mainda["dakkhati"];
irregda["addasa,m"] = mainda["dakkhati"];
irregda["addakkhi,m"] = mainda["dakkhati"];
irregda["addasaama"] = mainda["dakkhati"];
// removed: adhi,t,thaati = adhi,t,thaati
irregda["adhiti,t,thati"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thahati"] = mainda["adhi,t,thaati"];
irregda["adhi,t,theti"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thahanti"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thenti"] = mainda["adhi,t,thaati"];
irregda["adhiti,t,thasi"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thaami"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thema"] = mainda["adhi,t,thaati"];

irregda["adhi,t,thaahi"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thehi"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thaheyya"] = mainda["adhi,t,thaati"];
irregda["adhi,t,theyya"] = mainda["adhi,t,thaati"];
irregda["adhi,t,thaheyyaasi"] = mainda["adhi,t,thaati"];
// removed: adhiseti = adhiseti
irregda["adhisayati"] = mainda["adhiseti"];
irregda["adhisayeyya"] = mainda["adhiseti"];
// removed: aadisati = aadisati
irregda["aadisanti"] = mainda["aadisati"];
irregda["aadiseyya"] = mainda["aadisati"];
irregda["aadise"] = mainda["aadisati"];
irregda["aadiseyyaasi"] = mainda["aadisati"];
// removed: aadiyati = aadiyati
irregda["aadeti"] = mainda["aadiyati"];
irregda["aadatte"] = mainda["aadiyati"];
irregda["aadiyanti"] = mainda["aadiyati"];
irregda["aadenti"] = mainda["aadiyati"];
irregda["aadiyasi"] = mainda["aadiyati"];
irregda["aadiyatha"] = mainda["aadiyati"];
irregda["aadetha"] = mainda["aadiyati"];
irregda["aadiyaami"] = mainda["aadiyati"];
irregda["aadiyaama"] = mainda["aadiyati"];

irregda["aadiyantu"] = mainda["aadiyati"];
irregda["aadiya"] = mainda["aadiyati"];
irregda["aadiyissati"] = mainda["aadiyati"];
irregda["aadiyissanti"] = mainda["aadiyati"];
irregda["aadiyissasi"] = mainda["aadiyati"];
irregda["aadiyissatha"] = mainda["aadiyati"];
irregda["aadiyissaami"] = mainda["aadiyati"];
irregda["aadiyissaama"] = mainda["aadiyati"];
irregda["aadiyeyya"] = mainda["aadiyati"];
irregda["aadiyeyyu,m"] = mainda["aadiyati"];
irregda["aadiyeyyaasi"] = mainda["aadiyati"];
irregda["aadiyeyyaatha"] = mainda["aadiyati"];
irregda["aadiyeyya,m"] = mainda["aadiyati"];
irregda["aadiyeyyaama"] = mainda["aadiyati"];
irregda["aahaasi"] = mainda["aaharati"];
// removed: aahari = aahari
irregda["aaharesi"] = mainda["aaharati"];
irregda["aahari,msu"] = mainda["aaharati"];
irregda["aaha,msu"] = mainda["aaharati"];
irregda["aahari,m"] = mainda["aaharati"];
irregda["aaharaama"] = mainda["aaharati"];
irregda["aaharimha"] = mainda["aaharati"];
irregda["ahesu,m"] = mainda["ahosi"];
// removed: ahosi = ahosi
irregda["ahuvattha"] = mainda["ahosi"];
irregda["ahosi,m"] = mainda["ahosi"];
irregda["ahumha"] = mainda["ahosi"];
irregda["a~n~naati"] = mainda["aajaanaati"];
irregda["aajaananti"] = mainda["aajaanaati"];
irregda["aajaanaasi"] = mainda["aajaanaati"];
irregda["aajaanaatha"] = mainda["aajaanaati"];
irregda["aajaanaami"] = mainda["aajaanaati"];
irregda["aajaanaama"] = mainda["aajaanaati"];

irregda["aajaanaahi"] = mainda["aajaanaati"];
irregda["aajaaneyya"] = mainda["aajaanaati"];
irregda["aajaaneyyu,m"] = mainda["aajaanaati"];
irregda["aajaaneyyaasi"] = mainda["aajaanaati"];
irregda["aajaaneyyaatha"] = mainda["aajaanaati"];
irregda["aajaaneyya,m"] = mainda["aajaanaati"];
irregda["aajaaneyyaama"] = mainda["aajaanaati"];
// removed: ajjhagaa = ajjhagaa
irregda["ajjhagu"] = mainda["ajjhagaa"];
irregda["ajjhaguu"] = mainda["ajjhagaa"];
irregda["ajjhagu,m"] = mainda["ajjhagaa"];
irregda["ajjhaga,msu"] = mainda["ajjhagaa"];
// removed: ajjhagaa = ajjhagaa
irregda["adhiga,m"] = mainda["ajjhagaa"];
irregda["ajjhaga,m"] = mainda["ajjhagaa"];
// removed: ajjhagaa = ajjhagaa
// removed: ajjhagamaa = ajjhagamaa
irregda["ajjhagacchi"] = mainda["ajjhagamaa"];
irregda["ajjhaga~nchi"] = mainda["ajjhagamaa"];
irregda["adhigacchi"] = mainda["ajjhagamaa"];
irregda["adhiga~nchi"] = mainda["ajjhagamaa"];
irregda["ajjhagama,msu"] = mainda["ajjhagamaa"];
irregda["ajjhagamu,m"] = mainda["ajjhagamaa"];
irregda["ajjhaga,msu"] = mainda["ajjhagamaa"];
irregda["adhigami,msu"] = mainda["ajjhagamaa"];
irregda["adhigacchi,msu"] = mainda["ajjhagamaa"];
// removed: ajjhagamaa = ajjhagamaa
irregda["ajjhagamaasi"] = mainda["ajjhagamaa"];
irregda["ajjhagama,m"] = mainda["ajjhagamaa"];
irregda["ajjhagami,m"] = mainda["ajjhagamaa"];
irregda["adhigami,m"] = mainda["ajjhagamaa"];
irregda["adhigacchi,m"] = mainda["ajjhagamaa"];
irregda["adhigacchissa,m"] = mainda["ajjhagamaa"];
irregda["ajjhagamaamase"] = mainda["ajjhagamaa"];
irregda["aanayati"] = mainda["aaneti"];
irregda["aanayaami"] = mainda["aaneti"];
// removed: aaneti = aaneti
irregda["aanenti"] = mainda["aaneti"];
irregda["aanesi"] = mainda["aaneti"];
irregda["aanetha"] = mainda["aaneti"];
irregda["aanemi"] = mainda["aaneti"];
irregda["aanema"] = mainda["aaneti"];

irregda["aanehi"] = mainda["aaneti"];
irregda["aaneyya"] = mainda["aaneti"];
irregda["aaneyyaatha"] = mainda["aaneti"];
irregda["aaneyyaama"] = mainda["aaneti"];
// removed: antaradhaayati = antaradhaayati
irregda["antaradhaayanti"] = mainda["antaradhaayati"];
irregda["antaradhaayasi"] = mainda["antaradhaayati"];
irregda["antaradhaayatha"] = mainda["antaradhaayati"];
irregda["antaradhaayaami"] = mainda["antaradhaayati"];
irregda["antaradhaayaama"] = mainda["antaradhaayati"];
irregda["antaradhaayatu"] = mainda["antaradhaayati"];
irregda["antaradhaayantu"] = mainda["antaradhaayati"];
irregda["antaradhaayaahi"] = mainda["antaradhaayati"];
irregda["antaradhaayatha"] = mainda["antaradhaayati"];
irregda["antaradhaayaami"] = mainda["antaradhaayati"];
irregda["antaradhaayaama"] = mainda["antaradhaayati"];
irregda["antaradhaayissati"] = mainda["antaradhaayati"];
irregda["antaradhaayissanti"] = mainda["antaradhaayati"];
irregda["antaradhaayissasi"] = mainda["antaradhaayati"];
irregda["antaradhaayissatha"] = mainda["antaradhaayati"];
irregda["antaradhaayissaami"] = mainda["antaradhaayati"];
irregda["antaradhaayissaama"] = mainda["antaradhaayati"];
irregda["antaradhaayeyya"] = mainda["antaradhaayati"];
irregda["antaradhaayatha"] = mainda["antaradhaayati"];

irregda["antaradhaayassu"] = mainda["antaradhaayati"];
irregda["anubhonti"] = mainda["anubhoti"];
irregda["anubhosi"] = mainda["anubhoti"];
irregda["anubhotha"] = mainda["anubhoti"];
irregda["anubhomi"] = mainda["anubhoti"];
irregda["anubhoma"] = mainda["anubhoti"];
irregda["anubhotu"] = mainda["anubhoti"];
irregda["anubhontu"] = mainda["anubhoti"];
irregda["anubhohi"] = mainda["anubhoti"];

irregda["anukaronti"] = mainda["anukaroti"];
irregda["anukubbanti"] = mainda["anukaroti"];
irregda["anukaromi"] = mainda["anukaroti"];

irregda["anupadeti"] = mainda["anuppadeti"];

irregda["anuppadehi"] = mainda["anuppadeti"];
irregda["anupadajjeyya"] = mainda["anuppadeti"];
irregda["anuppadajju,m"] = mainda["anuppadeti"];
irregda["anuppadajjeyyu,m"] = mainda["anuppadeti"];
irregda["anuppadajjeyyaasi"] = mainda["anuppadeti"];
irregda["anupadajjeyyaasi"] = mainda["anuppadeti"];
irregda["anuppadeyyaasi"] = mainda["anuppadeti"];
irregda["anupadajjeyyaamaa"] = mainda["anuppadeti"];
// removed: anuseti = anuseti
irregda["anusenti"] = mainda["anuseti"];
// removed: anvagaa = anvagaa
irregda["anvaga,m"] = mainda["anvagaa"];
irregda["anvaguu"] = mainda["anvagaa"];
irregda["anvaguu"] = mainda["anvagaa"];
irregda["anvaga,m"] = mainda["anvagaa"];
irregda["annagaa"] = mainda["anvagaa"];
irregda["anvaguu"] = mainda["anvagaa"];
// removed: aarabhati = aarabhati
irregda["aarambhati"] = mainda["aarabhati"];

irregda["aarabhate"] = mainda["aarabhati"];

irregda["aarabhavho"] = mainda["aarabhati"];
// removed: aasi = aasi
irregda["aasu,m"] = mainda["aasati"];
irregda["aasu"] = mainda["aasati"];
irregda["aasi,msu"] = mainda["aasati"];
irregda["aasisu,m"] = mainda["aasati"];
// removed: aasi = aasi
irregda["aasi,m"] = mainda["aasati"];
irregda["aasimhaa"] = mainda["aasati"];
irregda["siyaa"] = mainda["atthi"];
irregda["siyu,m"] = mainda["atthi"];
irregda["siya,msu"] = mainda["atthi"];
irregda["assu,m"] = mainda["atthi"];
irregda["siyaa"] = mainda["atthi"];
irregda["assasi"] = mainda["atthi"];
irregda["assatha"] = mainda["atthi"];
irregda["siya,m"] = mainda["atthi"];
irregda["siyaa"] = mainda["atthi"];
irregda["assa,m"] = mainda["atthi"];
irregda["assaama"] = mainda["atthi"];
// removed: assosi = assosi
irregda["assosu,m"] = mainda["su,naati"];
// removed: assosi = assosi
irregda["assuttha"] = mainda["su,naati"];
irregda["assosi,m"] = mainda["su,naati"];
irregda["assumha"] = mainda["su,naati"];
// removed: atibhoti = atibhoti
irregda["atibhonti"] = mainda["atibhoti"];
irregda["atibhomi"] = mainda["atibhoti"];
irregda["accagaa"] = mainda["atigacchati"];
irregda["atigaa"] = mainda["atigacchati"];
irregda["accagu,m"] = mainda["atigacchati"];
irregda["accaguu"] = mainda["atigacchati"];
irregda["accagamaa"] = mainda["atigacchati"];
// removed: atthi = atthi
irregda["santi"] = mainda["atthi"];
irregda["asi"] = mainda["atthi"];
irregda["si"] = mainda["atthi"];
irregda["atthaz4"] = mainda["atthi"];
irregda["asmi"] = mainda["atthi"];
irregda["smi"] = mainda["atthi"];
irregda["amhi"] = mainda["atthi"];
irregda["mhi"] = mainda["atthi"];
irregda["asma"] = mainda["atthi"];
irregda["asmaa"] = mainda["atthi"];
irregda["amha"] = mainda["atthi"];
irregda["smase"] = mainda["atthi"];
irregda["atthu"] = mainda["atthi"];

irregda["avoca"] = mainda["vattiz1"];
irregda["amhaase"] = mainda["atthi"];
irregda["amhase"] = mainda["atthi"];
irregda["amhaa"] = mainda["atthi"];
// removed: avoca = avoca
irregda["avocu,m"] = mainda["vattiz1"];
// removed: avoca = avoca
irregda["avaca"] = mainda["vattiz1"];
irregda["avocuttha"] = mainda["vattiz1"];
irregda["avacuttha"] = mainda["vattiz1"];
irregda["avoca,m"] = mainda["vattiz1"];
irregda["avocumha"] = mainda["vattiz1"];
irregda["avocumhaa"] = mainda["vattiz1"];
// removed: bruuti = bruuti
irregda["bruusi"] = mainda["bruuti"];
irregda["bruutha"] = mainda["bruuti"];
irregda["bruumi"] = mainda["bruuti"];

irregda["bruuhi"] = mainda["bruuti"];
irregda["cetayati"] = mainda["cinteti"];
irregda["cetayanti"] = mainda["cinteti"];
irregda["cetayasi"] = mainda["cinteti"];
irregda["cetayatha"] = mainda["cinteti"];
irregda["cetayaami"] = mainda["cinteti"];
irregda["cetayaama"] = mainda["cinteti"];
irregda["ceteti"] = mainda["cinteti"];
irregda["cetenti"] = mainda["cinteti"];
irregda["cetesi"] = mainda["cinteti"];
irregda["cetetha"] = mainda["cinteti"];
irregda["cetemi"] = mainda["cinteti"];
irregda["cetema"] = mainda["cinteti"];
irregda["cinteyya"] = mainda["cinteti"];
irregda["cetaye"] = mainda["cinteti"];
irregda["cinteyyu,m"] = mainda["cinteti"];
irregda["cinteyyaasi"] = mainda["cinteti"];
irregda["cinteyyaatha"] = mainda["cinteti"];
irregda["cinteyya,m"] = mainda["cinteti"];
irregda["cinteyyaami"] = mainda["cinteti"];
irregda["cinteyyaama"] = mainda["cinteti"];
irregda["cintesi"] = mainda["cinteti"];
irregda["cintesu,m"] = mainda["cinteti"];
irregda["acintayu,m"] = mainda["cinteti"];
irregda["cintesi"] = mainda["cinteti"];
irregda["cintittha"] = mainda["cinteti"];
irregda["cintesi,m"] = mainda["cinteti"];
irregda["cintimha"] = mainda["cinteti"];
irregda["adaa"] = mainda["dadaati"];
irregda["ado"] = mainda["dadaati"];
irregda["adattha"] = mainda["dadaati"];
irregda["dattha"] = mainda["dadaati"];
irregda["adamha"] = mainda["dadaati"];

irregda["adada,m"] = mainda["dadaati"];
// removed: dadaati = dadaati
irregda["dadanti"] = mainda["dadaati"];
irregda["dadaasi"] = mainda["dadaati"];
irregda["dadaatha"] = mainda["dadaati"];
irregda["dadaami"] = mainda["dadaati"];
irregda["dadaama"] = mainda["dadaati"];
irregda["deti"] = mainda["dadaati"];
irregda["denti"] = mainda["dadaati"];
irregda["desi"] = mainda["dadaati"];
irregda["detha"] = mainda["dadaati"];
irregda["demi"] = mainda["dadaati"];
irregda["dammi"] = mainda["dadaati"];
irregda["dema"] = mainda["dadaati"];
irregda["detu"] = mainda["dadaati"];
irregda["dentu"] = mainda["dadaati"];
irregda["dehi"] = mainda["dadaati"];
irregda["dadaahi"] = mainda["dadaati"];
irregda["detha"] = mainda["dadaati"];
irregda["demi"] = mainda["dadaati"];
irregda["dema"] = mainda["dadaati"];
irregda["dadeyya"] = mainda["dadaati"];
irregda["dade"] = mainda["dadaati"];
irregda["dajjaa"] = mainda["dadaati"];
irregda["dajjeyya"] = mainda["dadaati"];
irregda["dadeyyaasi"] = mainda["dadaati"];
irregda["dajjeyyaatha"] = mainda["dadaati"];
irregda["dadeyya,m"] = mainda["dadaati"];
irregda["dajja,m"] = mainda["dadaati"];
// removed: dakkhati = dakkhati
irregda["dakkhiti"] = mainda["dakkhati"];
irregda["dakkhanti"] = mainda["dakkhati"];
irregda["dakkhinti"] = mainda["dakkhati"];
irregda["dakkhasi"] = mainda["dakkhati"];
irregda["dakkhatha"] = mainda["dakkhati"];
irregda["dakkhaami"] = mainda["dakkhati"];
irregda["dakkhaama"] = mainda["dakkhati"];

irregda["dakkha"] = mainda["dakkhati"];
// removed: essati = essati
irregda["issati"] = mainda["essati"];
irregda["ehiti"] = mainda["essati"];
irregda["essanti"] = mainda["essati"];
irregda["issanti"] = mainda["essati"];
irregda["ehinti"] = mainda["essati"];
irregda["essasi"] = mainda["essati"];
irregda["ehisi"] = mainda["essati"];
irregda["essaami"] = mainda["essati"];
irregda["essa,m"] = mainda["essati"];
// removed: eti = eti
irregda["ayati"] = mainda["eti"];
irregda["itiz2"] = mainda["eti"];
irregda["enti"] = mainda["eti"];
irregda["esi"] = mainda["eti"];
irregda["etha"] = mainda["eti"];
irregda["emi"] = mainda["eti"];
irregda["ayaama"] = mainda["eti"];
irregda["etu"] = mainda["eti"];
irregda["ehi"] = mainda["eti"];
irregda["aya"] = mainda["eti"];
irregda["etha"] = mainda["eti"];
irregda["eyya"] = mainda["eti"];
irregda["eyyaasi"] = mainda["eti"];
irregda["agamaasi"] = mainda["gacchati"];
// removed: gacchi = gacchi
irregda["agacchi"] = mainda["gacchati"];
irregda["aga~nchi"] = mainda["gacchati"];
irregda["agamaa"] = mainda["gacchati"];
irregda["gami"] = mainda["gacchati"];
irregda["agaa"] = mainda["gacchati"];
irregda["gacchi,msu"] = mainda["gacchati"];
irregda["agamu,m"] = mainda["gacchati"];
irregda["agama,msu"] = mainda["gacchati"];
irregda["agami,msu"] = mainda["gacchati"];
irregda["aguu"] = mainda["gacchati"];
irregda["agamaa"] = mainda["gacchati"];
irregda["agacchittha"] = mainda["gacchati"];
irregda["agamittha"] = mainda["gacchati"];
irregda["gacchi,m"] = mainda["gacchati"];
irregda["agacchi,m"] = mainda["gacchati"];
irregda["aga~nchi,m"] = mainda["gacchati"];
irregda["agamaasi,m"] = mainda["gacchati"];
irregda["agami,mhase"] = mainda["gacchati"];
irregda["agamamhaa"] = mainda["gacchati"];
irregda["hanti"] = mainda["hanati"];
// removed: hanati = hanati
irregda["hanaati"] = mainda["hanati"];
irregda["hananti"] = mainda["hanati"];
irregda["hanaasi"] = mainda["hanati"];
irregda["hanatha"] = mainda["hanati"];
irregda["hanaami"] = mainda["hanati"];
irregda["hanaama"] = mainda["hanati"];

irregda["hanantu"] = mainda["hanati"];
irregda["hana"] = mainda["hanati"];
irregda["haneyya"] = mainda["hanati"];
irregda["hane"] = mainda["hanati"];
irregda["haneyyu,m"] = mainda["hanati"];
irregda["haneyya,m"] = mainda["hanati"];
irregda["hanata,m"] = mainda["hanati"];
irregda["hanassu"] = mainda["hanati"];
irregda["hessati"] = mainda["hoti"];
irregda["hehiti"] = mainda["hoti"];
irregda["hohiti"] = mainda["hoti"];
irregda["hessanti"] = mainda["hoti"];
irregda["hohisi"] = mainda["hoti"];
irregda["hessasi"] = mainda["hoti"];
irregda["hehisi"] = mainda["hoti"];
irregda["hessatha"] = mainda["hoti"];
irregda["hessaami"] = mainda["hoti"];
irregda["hessa,m"] = mainda["hoti"];
irregda["hessaama"] = mainda["hoti"];
// removed: hoti = hoti
irregda["honti"] = mainda["hoti"];
irregda["hosi"] = mainda["hoti"];
irregda["hotha"] = mainda["hoti"];
irregda["homi"] = mainda["hoti"];
irregda["homa"] = mainda["hoti"];
irregda["hotu"] = mainda["hoti"];
irregda["hontu"] = mainda["hoti"];
irregda["hohi"] = mainda["hoti"];
irregda["hotha"] = mainda["hoti"];
irregda["homi"] = mainda["hoti"];
irregda["homa"] = mainda["hoti"];
irregda["hupeyya"] = mainda["hoti"];
irregda["jaaneyya"] = mainda["jaanaati"];
irregda["ja~n~naa"] = mainda["jaanaati"];
irregda["jaaneyyu,m"] = mainda["jaanaati"];
irregda["jaaneyyaasi"] = mainda["jaanaati"];
irregda["jaaneyyaatha"] = mainda["jaanaati"];
irregda["jaaneyya,m"] = mainda["jaanaati"];
irregda["jaaneyyaami"] = mainda["jaanaati"];
irregda["jaaneyyaama"] = mainda["jaanaati"];
irregda["jaaniyaama"] = mainda["jaanaati"];
irregda["jaanemu"] = mainda["jaanaati"];
// removed: jaanaati = jaanaati
irregda["jaananti"] = mainda["jaanaati"];
irregda["jaanaasi"] = mainda["jaanaati"];
irregda["jaanaatha"] = mainda["jaanaati"];
irregda["jaanaami"] = mainda["jaanaati"];
irregda["jaanaama"] = mainda["jaanaati"];
irregda["jaanaatu"] = mainda["jaanaati"];
irregda["jaanantu"] = mainda["jaanaati"];
irregda["jaanaahi"] = mainda["jaanaati"];
irregda["jaanaatha"] = mainda["jaanaati"];
irregda["jaanaami"] = mainda["jaanaati"];
irregda["jaanaama"] = mainda["jaanaati"];
// removed: jayati = jayati
irregda["jayanti"] = mainda["jayati"];
irregda["jayasi"] = mainda["jayati"];
irregda["jayatha"] = mainda["jayati"];
irregda["jayaami"] = mainda["jayati"];
irregda["jayaama"] = mainda["jayati"];
irregda["jeti"] = mainda["jayati"];
irregda["jenti"] = mainda["jayati"];
irregda["jesi"] = mainda["jayati"];
irregda["jetha"] = mainda["jayati"];
irregda["jemi"] = mainda["jayati"];
irregda["jema"] = mainda["jayati"];
irregda["jinaati"] = mainda["jayati"];
irregda["jinanti"] = mainda["jayati"];
irregda["jinaasi"] = mainda["jayati"];
irregda["jinaatha"] = mainda["jayati"];
irregda["jinaami"] = mainda["jayati"];
irregda["jinaama"] = mainda["jayati"];
irregda["jeyya"] = mainda["jayati"];
irregda["jine"] = mainda["jayati"];
irregda["jineyyu,m"] = mainda["jayati"];

irregda["akaa"] = mainda["karoti"];
irregda["aka,msu"] = mainda["karoti"];
irregda["akaa"] = mainda["karoti"];
irregda["akattha"] = mainda["karoti"];
irregda["aka,m"] = mainda["karoti"];
irregda["akamha"] = mainda["karoti"];
irregda["akara,m"] = mainda["karoti"];
irregda["akaraa"] = mainda["karoti"];
irregda["akari"] = mainda["karoti"];
irregda["akarii"] = mainda["karoti"];
irregda["akarittha"] = mainda["karoti"];
irregda["akaru,m"] = mainda["karoti"];
irregda["akari,msu"] = mainda["karoti"];
irregda["akara"] = mainda["karoti"];
irregda["akaraa"] = mainda["karoti"];
irregda["akari"] = mainda["karoti"];
irregda["akarii"] = mainda["karoti"];
irregda["akarittha"] = mainda["karoti"];
irregda["akara,m"] = mainda["karoti"];
irregda["akari,m"] = mainda["karoti"];
irregda["akaraama"] = mainda["karoti"];
irregda["akaramha"] = mainda["karoti"];
irregda["akarimha"] = mainda["karoti"];
irregda["akaasi"] = mainda["karoti"];
irregda["akaasi,m"] = mainda["karoti"];
irregda["kaahaasi,m"] = mainda["karoti"];
irregda["akaasimha"] = mainda["karoti"];
irregda["kaaraapesi"] = mainda["karoti"];
irregda["kaaraapesu,m"] = mainda["karoti"];
irregda["kaaraapayi,msu"] = mainda["karoti"];
irregda["kaaraapesi,m"] = mainda["karoti"];
irregda["kaarapesi,m"] = mainda["karoti"];
irregda["kaarapesi"] = mainda["karoti"];
irregda["kaaraapayi,m"] = mainda["karoti"];
irregda["kaaraapeti"] = mainda["karoti"];
irregda["kaaraapayati"] = mainda["karoti"];
irregda["kaaraapenti"] = mainda["karoti"];
irregda["kaaraapetha"] = mainda["karoti"];
irregda["kaaraapiyati"] = mainda["karoti"];
irregda["kariyati"] = mainda["karoti"];
irregda["kariiyati"] = mainda["karoti"];
irregda["kariiyate"] = mainda["karoti"];
irregda["kariyyati"] = mainda["karoti"];
irregda["kariyyate"] = mainda["karoti"];
irregda["kayirati"] = mainda["karoti"];
irregda["kiirati"] = mainda["karoti"];
irregda["kayyati"] = mainda["karoti"];
irregda["kayyate"] = mainda["karoti"];
irregda["kariiyanti"] = mainda["karoti"];
irregda["kayiranti"] = mainda["karoti"];
irregda["kiiranti"] = mainda["karoti"];
irregda["kariyanti"] = mainda["karoti"];
irregda["kariiyi"] = mainda["karoti"];
irregda["akaaresi"] = mainda["karoti"];
irregda["kaaresi"] = mainda["karoti"];
irregda["akaarayi"] = mainda["karoti"];
irregda["kaarayi"] = mainda["karoti"];
irregda["kaaresu,m"] = mainda["karoti"];
irregda["kaarayi,msu"] = mainda["karoti"];
irregda["akaarayu,m"] = mainda["karoti"];
irregda["kaarayu,m"] = mainda["karoti"];
irregda["kaaresi"] = mainda["karoti"];
irregda["kaarayesi"] = mainda["karoti"];
irregda["kaaresi,m"] = mainda["karoti"];
irregda["akaarayi,m"] = mainda["karoti"];
irregda["kaarayi,m"] = mainda["karoti"];
irregda["kaarayesi,m"] = mainda["karoti"];
irregda["akaarayi"] = mainda["karoti"];
irregda["kaarayi"] = mainda["karoti"];
irregda["kaareti"] = mainda["karoti"];
irregda["kaarayati"] = mainda["karoti"];
irregda["kaarayate"] = mainda["karoti"];
irregda["kaarenti"] = mainda["karoti"];
irregda["kaaretha"] = mainda["karoti"];
irregda["kaaremi"] = mainda["karoti"];
irregda["kaarayaami"] = mainda["karoti"];
irregda["karii"] = mainda["karoti"];
irregda["kari,msu"] = mainda["karoti"];
irregda["karu,m"] = mainda["karoti"];
irregda["karii"] = mainda["karoti"];
irregda["kari"] = mainda["karoti"];
irregda["karittha"] = mainda["karoti"];
irregda["kari,m"] = mainda["karoti"];
irregda["karimha"] = mainda["karoti"];
irregda["karimhaa"] = mainda["karoti"];
irregda["karissati"] = mainda["karoti"];
irregda["kaahati"] = mainda["karoti"];
irregda["kaahiti"] = mainda["karoti"];
irregda["kaasati"] = mainda["karoti"];
irregda["karissanti"] = mainda["karoti"];
irregda["kaahanti"] = mainda["karoti"];
irregda["kaahinti"] = mainda["karoti"];
irregda["karissare"] = mainda["karoti"];
irregda["karissasi"] = mainda["karoti"];
irregda["kaahasi"] = mainda["karoti"];
irregda["kaahisi"] = mainda["karoti"];
irregda["karissatha"] = mainda["karoti"];
irregda["kaahatha"] = mainda["karoti"];
irregda["karissaami"] = mainda["karoti"];
irregda["kaahaami"] = mainda["karoti"];
irregda["karissa,m"] = mainda["karoti"];
irregda["kassaami"] = mainda["karoti"];
irregda["kassa,m"] = mainda["karoti"];
irregda["kaasa,m"] = mainda["karoti"];
irregda["karissaama"] = mainda["karoti"];
irregda["kaahaama"] = mainda["karoti"];
irregda["kassaama"] = mainda["karoti"];
// removed: karoti = karoti
irregda["kayirati"] = mainda["karoti"];
irregda["karonti"] = mainda["karoti"];
irregda["karosi"] = mainda["karoti"];
irregda["karotha"] = mainda["karoti"];
irregda["karomi"] = mainda["karoti"];
irregda["kummi"] = mainda["karoti"];
irregda["karoma"] = mainda["karoti"];
irregda["kareyya"] = mainda["karoti"];
irregda["kare"] = mainda["karoti"];
irregda["kariyaa"] = mainda["karoti"];
irregda["kuriyaa"] = mainda["karoti"];
irregda["kuyiraa"] = mainda["karoti"];
irregda["kayiraatha"] = mainda["karoti"];
irregda["kayiraa"] = mainda["karoti"];
irregda["kayira"] = mainda["karoti"];
irregda["kareyyu,m"] = mainda["karoti"];
irregda["kayiru,m"] = mainda["karoti"];
irregda["kareyyaasi"] = mainda["karoti"];
irregda["kare"] = mainda["karoti"];
irregda["kayiraasi"] = mainda["karoti"];
irregda["kayiraa"] = mainda["karoti"];
irregda["kareyyaatha"] = mainda["karoti"];
irregda["kayiraatha"] = mainda["karoti"];
irregda["kareyya,m"] = mainda["karoti"];
irregda["katvaa"] = mainda["karoti"];
irregda["kareyyaami"] = mainda["karoti"];
irregda["kareyyaama"] = mainda["karoti"];
irregda["kubbati"] = mainda["karoti"];
irregda["kurute"] = mainda["karoti"];
irregda["kubbanti"] = mainda["karoti"];
irregda["karotu"] = mainda["karoti"];
irregda["kurutu"] = mainda["karoti"];
irregda["karontu"] = mainda["karoti"];
irregda["karohi"] = mainda["karoti"];
irregda["kuru"] = mainda["karoti"];
irregda["karotha"] = mainda["karoti"];
irregda["karomi"] = mainda["karoti"];
irregda["karoma"] = mainda["karoti"];
irregda["kariyatu"] = mainda["karoti"];
irregda["kayiratu"] = mainda["karoti"];
irregda["kuruta,m"] = mainda["karoti"];
irregda["karassu"] = mainda["karoti"];
irregda["kuruvho"] = mainda["karoti"];
irregda["karomase"] = mainda["karoti"];
irregda["kubbetha"] = mainda["karoti"];
irregda["kubbaye"] = mainda["karoti"];
irregda["kaaretu"] = mainda["karoti"];
irregda["kaarehi"] = mainda["karoti"];
irregda["kaaraapehi"] = mainda["karoti"];
irregda["kaareya"] = mainda["karoti"];
irregda["kaareyya"] = mainda["karoti"];
irregda["kaarayeyya"] = mainda["karoti"];
irregda["kaaraapeyya"] = mainda["karoti"];
irregda["kaareyyu,m"] = mainda["karoti"];
irregda["kaaraapeyyaasi"] = mainda["karoti"];
irregda["kaaraapeyyaatha"] = mainda["karoti"];
irregda["kaareya"] = mainda["karoti"];
irregda["kaaraapeyya,m"] = mainda["karoti"];
irregda["kaareyyaama"] = mainda["karoti"];
// removed: labhati = labhati
irregda["labhanti"] = mainda["labhati"];
irregda["labhasi"] = mainda["labhati"];
irregda["labhatha"] = mainda["labhati"];
irregda["labhaami"] = mainda["labhati"];
irregda["labhaama"] = mainda["labhati"];
irregda["labhatu"] = mainda["labhati"];
irregda["labhantu"] = mainda["labhati"];
irregda["labha"] = mainda["labhati"];
irregda["labhatha"] = mainda["labhati"];
irregda["labhaami"] = mainda["labhati"];
irregda["labhaama"] = mainda["labhati"];
irregda["labheyya"] = mainda["labhati"];
irregda["labhe"] = mainda["labhati"];
irregda["labheyyu,m"] = mainda["labhati"];
irregda["labheyyaasi"] = mainda["labhati"];
irregda["labheyyaatha"] = mainda["labhati"];
irregda["labheyya,m"] = mainda["labhati"];
irregda["labheyyaama"] = mainda["labhati"];
irregda["labhate"] = mainda["labhati"];
irregda["labhare"] = mainda["labhati"];
irregda["labhase"] = mainda["labhati"];
irregda["labhe"] = mainda["labhati"];
irregda["labhata,m"] = mainda["labhati"];
irregda["labhassu"] = mainda["labhati"];
irregda["labhaamase"] = mainda["labhati"];
irregda["labhaamhase"] = mainda["labhati"];
irregda["labhetha"] = mainda["labhati"];
irregda["labhetho"] = mainda["labhati"];
irregda["alattha"] = mainda["labhati"];
irregda["labhi"] = mainda["labhati"];
irregda["alabhi"] = mainda["labhati"];
irregda["alabbhittha"] = mainda["labhati"];
irregda["alatthu,m"] = mainda["labhati"];
irregda["alabhi,msu"] = mainda["labhati"];
irregda["labhi,msu"] = mainda["labhati"];
irregda["alattha,msu"] = mainda["labhati"];
irregda["labhittha"] = mainda["labhati"];
irregda["alattha,m"] = mainda["labhati"];
irregda["alabhi,m"] = mainda["labhati"];
irregda["labhi,m"] = mainda["labhati"];
irregda["alabhittha,m"] = mainda["labhati"];
irregda["labhimhaa"] = mainda["labhati"];
irregda["alatthamha"] = mainda["labhati"];
// removed: paccanubhoti = paccanubhoti
irregda["paccanubhonti"] = mainda["paccanubhoti"];
irregda["paccanubhosi"] = mainda["paccanubhoti"];
irregda["paccanubhotha"] = mainda["paccanubhoti"];
irregda["paccanubhomi"] = mainda["paccanubhoti"];
irregda["paccanubhoma"] = mainda["paccanubhoti"];
// removed: paccu,t,thaati = paccu,t,thaati
irregda["paccu,t,thanti"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaasi"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaatha"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaami"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaama"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaatu"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thantu"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaahi"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaatha"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaami"] = mainda["paccu,t,thaati"];
irregda["paccu,t,thaama"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyya"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyyu,m"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyyaasi"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyyaatha"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyya,m"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyyaami"] = mainda["paccu,t,thaati"];
irregda["paccu,t,theyyaama"] = mainda["paccu,t,thaati"];
// removed: paccupa,t,thaati = paccupa,t,thaati
irregda["paccupa,t,thaasi"] = mainda["paccupa,t,thaati"];
// removed: pahoti = pahoti
irregda["pahonti"] = mainda["pahoti"];
irregda["pahosi"] = mainda["pahoti"];
irregda["pahotha"] = mainda["pahoti"];
irregda["pahomi"] = mainda["pahoti"];
irregda["pahoma"] = mainda["pahoti"];
irregda["pakkaami"] = mainda["pakkamati"];
irregda["pakkamu,m"] = mainda["pakkamati"];
irregda["pakkami,msu"] = mainda["pakkamati"];
// removed: pa,tikaroti = pa,tikaroti
irregda["pa,tikaronti"] = mainda["pa,tikaroti"];
irregda["pa,tikarosi"] = mainda["pa,tikaroti"];
irregda["pa,tikarotha"] = mainda["pa,tikaroti"];
irregda["pa,tikaromi"] = mainda["pa,tikaroti"];
irregda["pa,tikaroma"] = mainda["pa,tikaroti"];
irregda["pa,tikarotu"] = mainda["pa,tikaroti"];
irregda["pa,tikarontu"] = mainda["pa,tikaroti"];
irregda["pa,tikarohi"] = mainda["pa,tikaroti"];
irregda["pa,tikarotha"] = mainda["pa,tikaroti"];
irregda["pa,tikaromi"] = mainda["pa,tikaroti"];
irregda["pa,tikaroma"] = mainda["pa,tikaroti"];
irregda["pa,tikareyya"] = mainda["pa,tikaroti"];
irregda["pa,tikareyyu,m"] = mainda["pa,tikaroti"];
irregda["pa,tikareyyaasi"] = mainda["pa,tikaroti"];
irregda["pa,tikareyyaatha"] = mainda["pa,tikaroti"];
irregda["pa,tikareyya,m"] = mainda["pa,tikaroti"];
irregda["pa,tikareyyaama"] = mainda["pa,tikaroti"];
irregda["paccassosi"] = mainda["pa,tissu,naati"];
irregda["paccassosu,m"] = mainda["pa,tissu,naati"];
irregda["paccassosi"] = mainda["pa,tissu,naati"];
irregda["paccassuttha"] = mainda["pa,tissu,naati"];
irregda["paccassosi,m"] = mainda["pa,tissu,naati"];
irregda["paccassumha"] = mainda["pa,tissu,naati"];
// removed: pappoti = pappoti
irregda["papponti"] = mainda["pappoti"];
irregda["papposi"] = mainda["pappoti"];
irregda["pappotha"] = mainda["pappoti"];
irregda["pappomi"] = mainda["pappoti"];
irregda["pappoma"] = mainda["pappoti"];
irregda["pappotu"] = mainda["pappoti"];
irregda["pappontu"] = mainda["pappoti"];
irregda["pappohi"] = mainda["pappoti"];
irregda["pappotha"] = mainda["pappoti"];
irregda["pappomi"] = mainda["pappoti"];
irregda["pappoma"] = mainda["pappoti"];

irregda["pappomu"] = mainda["pappoti"];
// removed: paapu,naati = paapu,naati
irregda["paapu,nanti"] = mainda["paapu,naati"];
irregda["paapu,naasi"] = mainda["paapu,naati"];
irregda["paapu,naatha"] = mainda["paapu,naati"];
irregda["paapu,naami"] = mainda["paapu,naati"];
irregda["paapu,naama"] = mainda["paapu,naati"];
irregda["paapu,neyya"] = mainda["paapu,naati"];
irregda["paapu,ne"] = mainda["paapu,naati"];
irregda["paapu,neyyaama"] = mainda["paapu,naati"];

// removed: pati,t,thahati = pati,t,thahati
irregda["pati,t,thahanti"] = mainda["pati,t,thahati"];
irregda["pati,t,thahasi"] = mainda["pati,t,thahati"];
irregda["pati,t,thahatha"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaami"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaama"] = mainda["pati,t,thahati"];
irregda["pati,t,thaati"] = mainda["pati,t,thahati"];
irregda["pati,t,thanti"] = mainda["pati,t,thahati"];
irregda["pati,t,thaasi"] = mainda["pati,t,thahati"];
irregda["pati,t,thaatha"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaami"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaama"] = mainda["pati,t,thahati"];
irregda["pati,t,thaatu"] = mainda["pati,t,thahati"];
irregda["pati,t,thantu"] = mainda["pati,t,thahati"];
irregda["pati,t,thaahi"] = mainda["pati,t,thahati"];
irregda["pati,t,thaatha"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaami"] = mainda["pati,t,thahati"];
irregda["pati,t,thahaama"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyya"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyyu,m"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyyaasi"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyyaatha"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyya,m"] = mainda["pati,t,thahati"];
irregda["pati,t,thaheyyaami"] = mainda["pati,t,thahati"];
irregda["paaturahosi"] = mainda["paatubhavati"];
irregda["paaturaha,msu"] = mainda["paatubhavati"];
irregda["paaturahi,msu"] = mainda["paatubhavati"];
irregda["paaturahosi"] = mainda["paatubhavati"];
irregda["paaturahuvattha"] = mainda["paatubhavati"];
irregda["paaturahosi,m"] = mainda["paatubhavati"];
irregda["paaturahumha"] = mainda["paatubhavati"];

// removed: sakkoti = sakkoti
irregda["sakkonti"] = mainda["sakkoti"];
irregda["sakkosi"] = mainda["sakkoti"];
irregda["sakkotha"] = mainda["sakkoti"];
irregda["sakkomi"] = mainda["sakkoti"];
irregda["sakkoma"] = mainda["sakkoti"];
irregda["sakku,neyya"] = mainda["sakkoti"];
irregda["sakku,neyyu,m"] = mainda["sakkoti"];
irregda["sakku,neyyaasi"] = mainda["sakkoti"];
irregda["sakku,neyyaatha"] = mainda["sakkoti"];
irregda["sakku,neyya,m"] = mainda["sakkoti"];
irregda["sakku,neyyaama"] = mainda["sakkoti"];
irregda["sakku,nemu"] = mainda["sakkoti"];

// removed: sambhoti = sambhoti
irregda["sambhonti"] = mainda["sambhoti"];
// removed: samudeti = samudeti
irregda["samudayati"] = mainda["samudeti"];
// removed: santi,t,thati = santi,t,thati
irregda["santi,t,thanti"] = mainda["santi,t,thati"];
irregda["santi,t,thasi"] = mainda["santi,t,thati"];
irregda["santi,t,thatha"] = mainda["santi,t,thati"];
irregda["santi,t,thaami"] = mainda["santi,t,thati"];
irregda["santi,t,thaama"] = mainda["santi,t,thati"];
irregda["sa,n,thaati"] = mainda["santi,t,thati"];
irregda["sa,n,thahati"] = mainda["santi,t,thati"];
irregda["sa,n,thanti"] = mainda["santi,t,thati"];
irregda["sa,n,thahanti"] = mainda["santi,t,thati"];
irregda["sa,n,thaasi"] = mainda["santi,t,thati"];
irregda["sa,n,thahasi"] = mainda["santi,t,thati"];
irregda["sa,n,thaatha"] = mainda["santi,t,thati"];
irregda["sa,n,thahatha"] = mainda["santi,t,thati"];
irregda["sa,n,thaami"] = mainda["santi,t,thati"];
irregda["sa,n,thahaami"] = mainda["santi,t,thati"];
irregda["sa,n,thaama"] = mainda["santi,t,thati"];
irregda["sa,n,thahaama"] = mainda["santi,t,thati"];
irregda["sa,n,thaheyya"] = mainda["santi,t,thati"];
irregda["sayati"] = mainda["seti"];
irregda["sayanti"] = mainda["seti"];
irregda["sayasi"] = mainda["seti"];
irregda["sayatha"] = mainda["seti"];
irregda["sayaami"] = mainda["seti"];
irregda["sayaama"] = mainda["seti"];
// removed: seti = seti
irregda["senti"] = mainda["seti"];
irregda["sesi"] = mainda["seti"];
irregda["setha"] = mainda["seti"];
irregda["semi"] = mainda["seti"];
irregda["sema"] = mainda["seti"];
irregda["sayatu"] = mainda["seti"];
irregda["sayeyya"] = mainda["seti"];
irregda["saye"] = mainda["seti"];
irregda["sayeyyaatha"] = mainda["seti"];
// removed: su,naati = su,naati

irregda["su,noti"] = mainda["su,naati"];
irregda["su,nanti"] = mainda["su,naati"];
irregda["su,naasi"] = mainda["su,naati"];
irregda["su,nosi"] = mainda["su,naati"];
irregda["su,naatha"] = mainda["su,naati"];
irregda["su,notha"] = mainda["su,naati"];
irregda["su,naami"] = mainda["su,naati"];
irregda["su,nomi"] = mainda["su,naati"];
irregda["su,noma"] = mainda["su,naati"];
irregda["su,naama"] = mainda["su,naati"];
irregda["su,naatu"] = mainda["su,naati"];
irregda["su,nohi"] = mainda["su,naati"];
irregda["su,naahi"] = mainda["su,naati"];
irregda["su,neyya"] = mainda["su,naati"];
irregda["su,neyyu,m"] = mainda["su,naati"];
irregda["su,neyyaatha"] = mainda["su,naati"];
irregda["su,neyya,m"] = mainda["su,naati"];
irregda["su,neyyaama"] = mainda["su,naati"];

irregda["sossati"] = mainda["su,naati"];

irregda["sussa,m"] = mainda["su,naati"];

irregda["sossi"] = mainda["su,naati"];
irregda["assosi"] = mainda["su,naati"];
irregda["assosu,m"] = mainda["su,naati"];
irregda["assu,m"] = mainda["su,naati"];
irregda["assuz5"] = mainda["su,naati"];
irregda["su,ni"] = mainda["su,naati"];
irregda["assumha"] = mainda["su,naati"];
irregda["assuttha"] = mainda["su,naati"];
irregda["suyati "] = mainda["su,naati"];
irregda["suyyati"] = mainda["su,naati"];

// removed: ti,t,thati = ti,t,thati
irregda["ti,t,thanti"] = mainda["ti,t,thati"];
irregda["ti,t,thasi"] = mainda["ti,t,thati"];
irregda["ti,t,thatha"] = mainda["ti,t,thati"];
irregda["ti,t,thaami"] = mainda["ti,t,thati"];
irregda["ti,t,thaama"] = mainda["ti,t,thati"];
irregda["ti,t,thatu"] = mainda["ti,t,thati"];
irregda["ti,t,thantu"] = mainda["ti,t,thati"];
irregda["ti,t,tha"] = mainda["ti,t,thati"];
irregda["ti,t,thatha"] = mainda["ti,t,thati"];
irregda["ti,t,thaami"] = mainda["ti,t,thati"];
irregda["ti,t,thaama"] = mainda["ti,t,thati"];
irregda["ti,t,the"] = mainda["ti,t,thati"];
irregda["ti,t,theyya"] = mainda["ti,t,thati"];
irregda["ti,t,theyyu,m"] = mainda["ti,t,thati"];
irregda["ti,t,theyyaasi"] = mainda["ti,t,thati"];
irregda["ti,t,theyyaatha"] = mainda["ti,t,thati"];
irregda["ti,t,theyya,m"] = mainda["ti,t,thati"];
irregda["ti,t,theyyaami"] = mainda["ti,t,thati"];
irregda["ti,t,theyyaama"] = mainda["ti,t,thati"];
// removed: udayati = udayati
irregda["udayanti"] = mainda["udayati"];
// removed: udeti = udeti
irregda["udenti"] = mainda["udeti"];
// removed: upaccagaa = upaccagaa
irregda["upaccagu,m"] = mainda["upaccagaa"];
irregda["upaccagu"] = mainda["upaccagaa"];
irregda["upaccaguu"] = mainda["upaccagaa"];
irregda["upaccaga,m"] = mainda["upaccagaa"];
irregda["upaagamaasi"] = mainda["upaagacchati"];
// removed: upaagaami = upaagaami
irregda["upaagacchi"] = mainda["upaagacchati"];
irregda["upaaga~nchi"] = mainda["upaagacchati"];
irregda["upagacchi"] = mainda["upaagacchati"];
irregda["upaga~nchi"] = mainda["upaagacchati"];
irregda["upaagamu,m"] = mainda["upaagacchati"];
irregda["upaagami,msu"] = mainda["upaagacchati"];
irregda["upagami,msu"] = mainda["upaagacchati"];
irregda["upaaga~nchu,m"] = mainda["upaagacchati"];
irregda["upagacchu,m"] = mainda["upaagacchati"];
irregda["upaga~nchu,m"] = mainda["upaagacchati"];
irregda["upagacchi,msu"] = mainda["upaagacchati"];
irregda["upagacchu"] = mainda["upaagacchati"];
irregda["upaga~nchu"] = mainda["upaagacchati"];
irregda["upaagama,m"] = mainda["upaagacchati"];
irregda["upagama,m"] = mainda["upaagacchati"];
irregda["upaagami,m"] = mainda["upaagacchati"];
irregda["upagami,m"] = mainda["upaagacchati"];
irregda["upaagacchi,m"] = mainda["upaagacchati"];
irregda["upaaga~nchi,m"] = mainda["upaagacchati"];
irregda["upagacchi,m"] = mainda["upaagacchati"];
irregda["upaga~nchi,m"] = mainda["upaagacchati"];
irregda["upagacchittha"] = mainda["upaagacchati"];
// removed: upa,t,thahati = upa,t,thahati
irregda["upa,t,thaheti"] = mainda["upa,t,thahati"];
irregda["upa,t,thahanti"] = mainda["upa,t,thahati"];
irregda["upa,t,thahatha"] = mainda["upa,t,thahati"];
irregda["upa,t,thahaami"] = mainda["upa,t,thahati"];
irregda["upa,t,thahema"] = mainda["upa,t,thahati"];
irregda["upa,t,thahatu"] = mainda["upa,t,thahati"];
irregda["upa,t,thaha"] = mainda["upa,t,thahati"];
irregda["upa,t,thaheyya"] = mainda["upa,t,thahati"];

irregda["upa,t,thahassu"] = mainda["upa,t,thahati"];
// removed: upa,t,thaati = upa,t,thaati
irregda["upa,t,theti"] = mainda["upa,t,thaati"];
irregda["upa,t,thanti"] = mainda["upa,t,thaati"];
irregda["upa,t,thenti"] = mainda["upa,t,thaati"];
irregda["upa,t,thesi"] = mainda["upa,t,thaati"];
irregda["upa,t,thaatu"] = mainda["upa,t,thaati"];
irregda["upa,t,thaahi"] = mainda["upa,t,thaati"];
irregda["upa,t,theyya"] = mainda["upa,t,thaati"];

// removed: upati,t,thati = upati,t,thati
irregda["upati,t,thanti"] = mainda["upati,t,thati"];
irregda["upati,t,thatha"] = mainda["upati,t,thati"];
irregda["upati,t,thaama"] = mainda["upati,t,thati"];
irregda["upati,t,thatu"] = mainda["upati,t,thati"];
irregda["upati,t,theyya"] = mainda["upati,t,thati"];
irregda["upati,t,theyyu,m"] = mainda["upati,t,thati"];
irregda["upati,t,theyya,m"] = mainda["upati,t,thati"];
// removed: vadati = vadati
/*mainda["vadanti"] = mainda["vadati"];
irregda["vadasi"] = mainda["vadati"];
irregda["vadatha"] = mainda["vadati"];
irregda["vadaami"] = mainda["vadati"];
irregda["vadaama"] = mainda["vadati"];*/

irregda["vadehi"] = mainda["vadati"];

irregda["vademase"] = mainda["vadati"];
irregda["vadeyya"] = mainda["vajjaa"];
// removed: vajjaa = vajjaa
irregda["vadeyyu,m"] = mainda["vajjaa"];
irregda["vajju,m"] = mainda["vajjaa"];
irregda["vadeyyaasi"] = mainda["vajjaa"];
irregda["vajjesi"] = mainda["vajjaa"];
irregda["vajjaasi"] = mainda["vajjaa"];
irregda["vadeyyaatha"] = mainda["vajjaa"];
irregda["vade"] = mainda["vajjaa"];
irregda["vadeyya,m"] = mainda["vajjaa"];
irregda["vadeyyaami"] = mainda["vajjaa"];
irregda["vajja,m"] = mainda["vajjaa"];
irregda["vadeyyaama"] = mainda["vajjaa"];
// removed: vandati = vandati
//mainda["vandanti"] = mainda["vandati"];
//mainda["vandasi"] = mainda["vandati"];
//mainda["vandatha"] = mainda["vandati"];
//mainda["vandaami"] = mainda["vandati"];
//mainda["vandaama"] = mainda["vandati"];

//mainda["vandantu"] = mainda["vandati"];
irregda["vanda"] = mainda["vandati"];
irregda["vandaahi"] = mainda["vandati"];
irregda["vandeyya"] = mainda["vandati"];
irregda["vandeyyaasi"] = mainda["vandati"];
irregda["vandate"] = mainda["vandati"];
irregda["vandase"] = mainda["vandati"];
irregda["vande"] = mainda["vandati"];
irregda["viharaahi"] = mainda["viharati"];
irregda["vihaasi"] = mainda["viharati"];
irregda["vihi,msu"] = mainda["viharati"];
irregda["viha,msu"] = mainda["viharati"];
// removed: vijaanaati = vijaanaati
irregda["vijaananti"] = mainda["vijaanaati"];
irregda["vijaanaasi"] = mainda["vijaanaati"];
irregda["vijaanaatha"] = mainda["vijaanaati"];
irregda["vijaanaami"] = mainda["vijaanaati"];
irregda["vijaanaama"] = mainda["vijaanaati"];
irregda["vijaanaatu"] = mainda["vijaanaati"];
irregda["vijaanantu"] = mainda["vijaanaati"];
irregda["vijaana"] = mainda["vijaanaati"];
irregda["vijaanaahi"] = mainda["vijaanaati"];
irregda["vijaanaatha"] = mainda["vijaanaati"];
irregda["vijaanaami"] = mainda["vijaanaati"];
irregda["vijaanaama"] = mainda["vijaanaati"];
irregda["vijaaneyya"] = mainda["vijaanaati"];
irregda["vija~n~naa"] = mainda["vijaanaati"];
irregda["vijaaneyyu,m"] = mainda["vijaanaati"];
irregda["vijaaneyyaasi"] = mainda["vijaanaati"];
irregda["vijaaneyyaatha"] = mainda["vijaanaati"];
irregda["vijaaneyya,m"] = mainda["vijaanaati"];
irregda["vija~n~na,m"] = mainda["vijaanaati"];
irregda["vijaaniya,m"] = mainda["vijaanaati"];
irregda["vijaaneyyaama"] = mainda["vijaanaati"];
irregda["vijaanata,m"] = mainda["vijaanaati"];
// removed: vineti = vineti
irregda["vinenti"] = mainda["vineti"];
irregda["vinesi"] = mainda["vineti"];
irregda["vinetha"] = mainda["vineti"];
irregda["vinemi"] = mainda["vineti"];
irregda["vinema"] = mainda["vineti"];
irregda["vinetu"] = mainda["vineti"];
irregda["vinaya"] = mainda["vineti"];
irregda["vineyya"] = mainda["vineti"];
irregda["vineyyu,m"] = mainda["vineti"];
irregda["vineyyaasi"] = mainda["vineti"];
irregda["vineyyaatha"] = mainda["vineti"];
irregda["vineyya,m"] = mainda["vineti"];
irregda["vineyyaama"] = mainda["vineti"];

irregda["vinayassu"] = mainda["vineti"];
irregda["vinayetha"] = mainda["vineti"];
// removed: vu,t,thahati = vu,t,thahati
irregda["vu,t,thahanti"] = mainda["vu,t,thahati"];
irregda["vu,t,thahasi"] = mainda["vu,t,thahati"];
irregda["vu,t,thahatha"] = mainda["vu,t,thahati"];
irregda["vu,t,thahaami"] = mainda["vu,t,thahati"];
irregda["vu,t,thahaama"] = mainda["vu,t,thahati"];
irregda["vu,t,thaati"] = mainda["vu,t,thahati"];
irregda["vu,t,thanti"] = mainda["vu,t,thahati"];
irregda["vu,t,thaasi"] = mainda["vu,t,thahati"];
irregda["vu,t,thaatha"] = mainda["vu,t,thahati"];
irregda["vu,t,thaami"] = mainda["vu,t,thahati"];
irregda["vu,t,thaama"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissati"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissanti"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissasi"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissatha"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissaami"] = mainda["vu,t,thahati"];
irregda["vu,t,thahissaama"] = mainda["vu,t,thahati"];
irregda["vu,t,thaheyya"] = mainda["vu,t,thahati"];
irregda["byantiihoti"] = mainda["vyantiihoti"];
// removed: cinteti = cinteti
irregda["cintenti"] = mainda["cinteti"];
irregda["cintesi"] = mainda["cinteti"];
irregda["cintetha"] = mainda["cinteti"];
irregda["cintemi"] = mainda["cinteti"];
irregda["cintema"] = mainda["cinteti"];
irregda["huveyya"] = mainda["hoti"];

// irregular nouns

irregda["ida,m"] = mainda["ida"];

irregda["aya,m"] = mainda["ida"]
irregda["ima,m"] = mainda["ida"]
irregda["iminaa"] = mainda["ida"]
irregda["imasmaa"] = mainda["ida"]
irregda["imamhaa"] = mainda["ida"]
irregda["imassa"] = mainda["ida"]
irregda["asmi,m"] = mainda["ida"]
irregda["imasmi,m"] = mainda["ida"]
irregda["ime"] = mainda["ida"]
irregda["ime"] = mainda["ida"]
irregda["imehi"] = mainda["ida"]
irregda["imesa,m"] = mainda["ida"]
irregda["imehi"] = mainda["ida"]
irregda["imesa,m"] = mainda["ida"]
irregda["imesu"] = mainda["ida"]
irregda["ida,m"] = mainda["ida"]
irregda["ida,m"] = mainda["ida"]
irregda["iminaa"] = mainda["ida"]
irregda["imasmaa"] = mainda["ida"]
irregda["imamhaa"] = mainda["ida"]
irregda["imassa"] = mainda["ida"]
irregda["asmi,m"] = mainda["ida"]
irregda["imasmi,m"] = mainda["ida"]
irregda["imaani"] = mainda["ida"]
irregda["imaani"] = mainda["ida"]
irregda["imehi"] = mainda["ida"]
irregda["imesa,m"] = mainda["ida"]
irregda["imehi"] = mainda["ida"]
irregda["imesa,m"] = mainda["ida"]
irregda["imesu"] = mainda["ida"]
irregda["aya,m"] = mainda["ida"]
irregda["ima,m"] = mainda["ida"]
irregda["imaaya"] = mainda["ida"]
irregda["assaa"] = mainda["ida"]
irregda["imaaya"] = mainda["ida"]
irregda["assaa"] = mainda["ida"]
irregda["imassaa"] = mainda["ida"]
irregda["imaayam"] = mainda["ida"]
irregda["imaaya"] = mainda["ida"]
irregda["imaa"] = mainda["ida"]
irregda["imaa"] = mainda["ida"]
irregda["imaahi"] = mainda["ida"]
irregda["imaasa,m"] = mainda["ida"]
irregda["imaahi"] = mainda["ida"]
irregda["imaasa,m"] = mainda["ida"]
irregda["imaasu"] = mainda["ida"]

/*mainda["na,m"] = mainda["na"]
irregda["nena"] = mainda["na"]
irregda["nassa"] = mainda["na"]
irregda["nasmaa"] = mainda["na"]
irregda["namhaa"] = mainda["na"]
irregda["nassa"] = mainda["na"]
irregda["nasmi,m"] = mainda["na"]
irregda["namhi"] = mainda["na"]
irregda["ne"] = mainda["na"]
irregda["nehi"] = mainda["na"]
irregda["nesa,m"] = mainda["na"]
irregda["nehi"] = mainda["na"]
irregda["nesa,m"] = mainda["na"]
irregda["nesu"] = mainda["na"]
irregda["na,m"] = mainda["na"]
irregda["nena"] = mainda["na"]
irregda["nassa"] = mainda["na"]
irregda["nasmaa"] = mainda["na"]
irregda["namhaa"] = mainda["na"]
irregda["nassa"] = mainda["na"]
irregda["nasmi,m"] = mainda["na"]
irregda["namhi"] = mainda["na"]
irregda["naani"] = mainda["na"]
irregda["nehi"] = mainda["na"]
irregda["nesa,m"] = mainda["na"]
irregda["nehi"] = mainda["na"]
irregda["nesa,m"] = mainda["na"]
irregda["nesu"] = mainda["na"]
irregda["na,m"] = mainda["na"]
irregda["naaya"] = mainda["na"]
irregda["nassaa"] = mainda["na"]
irregda["naaya"] = mainda["na"]
irregda["nassaa"] = mainda["na"]
irregda["naaya"] = mainda["na"]
irregda["naaya,m"] = mainda["na"]
irregda["nassa,m"] = mainda["na"]
irregda["naa"] = mainda["na"]
irregda["naahi"] = mainda["na"]
irregda["naasa,m"] = mainda["na"]
irregda["naahi"] = mainda["na"]
irregda["naasa,m"] = mainda["na"]
irregda["naasu"] = mainda["na"]*/
irregda["aham"] = mainda["aha,m"]
irregda["ma,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mez2"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayi"] = mainda["aha,m"]
irregda["maya,m"] = mainda["aha,m"]
irregda["amhe"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhesu"] = mainda["aha,m"]
irregda["aha,m"] = mainda["aha,m"]
irregda["ma,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayi"] = mainda["aha,m"]
irregda["maya,m"] = mainda["aha,m"]
irregda["amhe"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhesu"] = mainda["aha,m"]
irregda["aha,m"] = mainda["aha,m"]
irregda["ma,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayaa"] = mainda["aha,m"]
irregda["mama"] = mainda["aha,m"]
irregda["mama,m"] = mainda["aha,m"]
irregda["mayha,m"] = mainda["aha,m"]
irregda["mayi"] = mainda["aha,m"]
irregda["maya,m"] = mainda["aha,m"]
irregda["amhe"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhehi"] = mainda["aha,m"]
irregda["amhaaka,m"] = mainda["aha,m"]
irregda["no"] = mainda["aha,m"]
irregda["asmaakam"] = mainda["aha,m"]
irregda["amhesu"] = mainda["aha,m"]

irregda["tumha"] = mainda["tuva,m"]
irregda["tayaa"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayaa"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayi"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]
irregda["vo"] = mainda["tumha"]
irregda["tumhehi"] = mainda["tumha"]
irregda["tuyha,m"] = mainda["tumha"]

irregda["tumhaaka,m"] = mainda["tumha"]


irregda["tumhehi"] = mainda["tumha"]

irregda["tumha,m"] = mainda["tumha"]


irregda["tumhesu"] = mainda["tumha"]
irregda["ta,mz1"] = mainda["tumha"]
irregda["tayaa"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayaa"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayi"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]

irregda["tumhehi"] = mainda["tumha"]




irregda["tumhehi"] = mainda["tumha"]



irregda["tumhesu"] = mainda["tumha"]
irregda["tayaa"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayaa"] = mainda["tumha"]
irregda["tava"] = mainda["tumha"]
irregda["te"] = mainda["tumha"]
irregda["tayi"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]
irregda["tumhe"] = mainda["tumha"]

irregda["tumhehi"] = mainda["tumha"]




irregda["tumhehi"] = mainda["tumha"]



irregda["tumhesu"] = mainda["tumha"]

irregda["asu"] = mainda["amu"]
irregda["amunaa"] = mainda["amu"]
irregda["amussa"] = mainda["amu"]
irregda["amumhaa"] = mainda["amu"]
irregda["amussa"] = mainda["amu"]
irregda["amusmi,m"] = mainda["amu"]
irregda["amuu"] = mainda["amu"]
irregda["amuu"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["adu,m"] = mainda["amu"]
irregda["adu,m"] = mainda["amu"]
irregda["amunaa"] = mainda["amu"]
irregda["amussa"] = mainda["amu"]
irregda["amumhaa"] = mainda["amu"]
irregda["amussa"] = mainda["amu"]
irregda["amusmi,m"] = mainda["amu"]
irregda["amuuni"] = mainda["amu"]
irregda["amuuni"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["asu"] = mainda["amu"]
irregda["asu"] = mainda["amu"]
irregda["amussaa"] = mainda["amu"]
irregda["amussaa"] = mainda["amu"]
irregda["amussa,m"] = mainda["amu"]
irregda["amuu"] = mainda["amu"]
irregda["amuu"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["amuuhi"] = mainda["amu"]
irregda["amuusa,m"] = mainda["amu"]
irregda["ena,m"] = mainda["ena"]

irregda["mahaaraajaa"] = mainda["mahaaraajaa"]
irregda["mahaaraaja"] = mainda["mahaaraajaa"]
irregda["mahaaraajaa,m"] = mainda["mahaaraajaa"]
irregda["mahaaraajena"] = mainda["mahaaraajaa"]
irregda["mahaaraajassa"] = mainda["mahaaraajaa"]
irregda["mahaaraajaa"] = mainda["mahaaraajaa"]
irregda["mahaaraajassa"] = mainda["mahaaraajaa"]
irregda["mahaaraaje"] = mainda["mahaaraajaa"]
irregda["mahaaraajaa"] = mainda["mahaaraajaa"]
irregda["mahaaraajaano"] = mainda["mahaaraajaa"]
irregda["mahaaraaje"] = mainda["mahaaraajaa"]
irregda["mahaaraajehi"] = mainda["mahaaraajaa"]
irregda["mahaaraajaana,m"] = mainda["mahaaraajaa"]
irregda["mahaaraajehi"] = mainda["mahaaraajaa"]
irregda["mahaaraajaana,m"] = mainda["mahaaraajaa"]
irregda["mahaaraajesu"] = mainda["mahaaraajaa"]

irregda["eko"] = mainda["eka"]
irregda["eka,m"] = mainda["eka"]
irregda["ekena"] = mainda["eka"]
irregda["ekassa"] = mainda["eka"]
irregda["ekasmaa"] = mainda["eka"]
irregda["ekamhaa"] = mainda["eka"]
irregda["ekassa"] = mainda["eka"]
irregda["ekasmi,m"] = mainda["eka"]
irregda["ekamhi"] = mainda["eka"]
irregda["eke"] = mainda["eka"]
irregda["eke"] = mainda["eka"]
irregda["ekehi"] = mainda["eka"]
irregda["ekesa,m"] = mainda["eka"]
irregda["ekehi"] = mainda["eka"]
irregda["ekesa,m"] = mainda["eka"]
irregda["ekesu"] = mainda["eka"]
irregda["eka,m"] = mainda["eka"]
irregda["eka,m"] = mainda["eka"]
irregda["ekena"] = mainda["eka"]
irregda["ekassa"] = mainda["eka"]
irregda["ekasmaa"] = mainda["eka"]
irregda["ekamhaa"] = mainda["eka"]
irregda["ka~n ci"] = mainda["ko ci"]
irregda["kena ci"] = mainda["ko ci"]
irregda["kassa ci"] = mainda["ko ci"]
irregda["kissa ci"] = mainda["ko ci"]
irregda["kasmaa ci"] = mainda["ko ci"]
irregda["kamhaa ci"] = mainda["ko ci"]
irregda["kassa ci"] = mainda["ko ci"]
irregda["kissa ci"] = mainda["ko ci"]
irregda["kismi~n ci"] = mainda["ko ci"]
irregda["kimhi ci"] = mainda["ko ci"]
irregda["ke ci"] = mainda["ko ci"]
irregda["ke ci"] = mainda["ko ci"]
irregda["kehi ci"] = mainda["ko ci"]
irregda["kesa,m ci"] = mainda["ko ci"]
irregda["kehi ci"] = mainda["ko ci"]
irregda["kesa,m ci"] = mainda["ko ci"]
irregda["kesu ci"] = mainda["ko ci"]
irregda["ki~n ci"] = mainda["ko ci"]
irregda["ki~n ci"] = mainda["ko ci"]
irregda["kena ci"] = mainda["ko ci"]
irregda["kassa ci"] = mainda["ko ci"]
irregda["kissa ci"] = mainda["ko ci"]
irregda["kasmaa ci"] = mainda["ko ci"]
irregda["kamhaa ci"] = mainda["ko ci"]
irregda["kassa ci"] = mainda["ko ci"]
irregda["kissa ci"] = mainda["ko ci"]
irregda["kismi~n ci"] = mainda["ko ci"]
irregda["kimhi ci"] = mainda["ko ci"]
irregda["kaani ci"] = mainda["ko ci"]
irregda["kaani ci"] = mainda["ko ci"]
irregda["kehi ci"] = mainda["ko ci"]
irregda["kesa~n ci"] = mainda["ko ci"]
irregda["kehi ci"] = mainda["ko ci"]
irregda["kesa~n ci"] = mainda["ko ci"]
irregda["kesu ci"] = mainda["ko ci"]
irregda["kaa ci"] = mainda["ko ci"]
irregda["ka,m ci"] = mainda["ko ci"]
irregda["kaaya ci"] = mainda["ko ci"]
irregda["kassaa ci"] = mainda["ko ci"]
irregda["kaaya ci"] = mainda["ko ci"]
irregda["kassaa ci"] = mainda["ko ci"]
irregda["kaaya ci"] = mainda["ko ci"]
irregda["kaaya~n ci"] = mainda["ko ci"]
irregda["kassa~n ci"] = mainda["ko ci"]
irregda["kaa ci"] = mainda["ko ci"]
irregda["kaa ci"] = mainda["ko ci"]
irregda["kaahi ci"] = mainda["ko ci"]
irregda["kaasa~n ci"] = mainda["ko ci"]
irregda["kaahi ci"] = mainda["ko ci"]
irregda["kaasa~n ci"] = mainda["ko ci"]
irregda["kaasu ci"] = mainda["ko ci"]
irregda["na ko ci"] = mainda["na ki~n ci"]
irregda["na ka,m ci"] = mainda["na ki~n ci"]
irregda["ekassa"] = mainda["eka"]
irregda["ekasmi,m"] = mainda["eka"]
irregda["ekamhi"] = mainda["eka"]
irregda["ekaani"] = mainda["eka"]

irregda["ubhohi"] = mainda["ubha"]
irregda["ubhinna,m"] = mainda["ubha"]
irregda["ubhosu"] = mainda["ubha"]
irregda["ubhayo"] = mainda["ubha"]

irregda["bhavanto"] = mainda["bhavanta"]
irregda["bhonto"] = mainda["bhavanta"]
irregda["bhavante"] = mainda["bhavanta"]
irregda["bhavantehi"] = mainda["bhavanta"]
irregda["bhavata,m"] = mainda["bhavanta"]
irregda["bhavantehi"] = mainda["bhavanta"]
irregda["bhavata,m"] = mainda["bhavanta"]
irregda["bhavantesu"] = mainda["bhavanta"]
irregda["bhotii"] = mainda["bhavanta"]
irregda["bhoti"] = mainda["bhavanta"]
irregda["bhoti,m"] = mainda["bhavanta"]
irregda["bhotiyaa"] = mainda["bhavanta"]
irregda["bhotiya,m"] = mainda["bhavanta"]
irregda["bhotiyo"] = mainda["bhavanta"]
irregda["bhotiihi"] = mainda["bhavanta"]
irregda["bhotiina,m"] = mainda["bhavanta"]
irregda["bhotiisu"] = mainda["bhavanta"]
irregda["attaa"] = mainda["attaz3"]
irregda["attaana,m"] = mainda["attaz3"]
irregda["attanaa"] = mainda["attaz3"]
irregda["attano"] = mainda["attaz3"]
irregda["attanaa"] = mainda["attaz3"]
irregda["attani"] = mainda["attaz3"]
irregda["attaano"] = mainda["attaz3"]
irregda["attaano"] = mainda["attaz3"]
irregda["attaano"] = mainda["attaz3"]
irregda["attehi"] = mainda["attaz3"]
irregda["attaana,m"] = mainda["attaz3"]
irregda["attehi"] = mainda["attaz3"]
irregda["attaana,m"] = mainda["attaz3"]
irregda["attanesu"] = mainda["attaz3"]

irregda["brahmaa"] = mainda["brahma"]
irregda["brahme"] = mainda["brahma"]
irregda["brahmaana,m"] = mainda["brahma"]
irregda["brahmunaa"] = mainda["brahma"]
irregda["brahmuno"] = mainda["brahma"]
irregda["brahmunaa"] = mainda["brahma"]
irregda["brahmuno"] = mainda["brahma"]
irregda["brahmani"] = mainda["brahma"]
irregda["brahmaano"] = mainda["brahma"]
irregda["brahmaano"] = mainda["brahma"]
irregda["brahmaano"] = mainda["brahma"]
irregda["brahmehi"] = mainda["brahma"]
irregda["brahmaana,m"] = mainda["brahma"]
irregda["brahmehi"] = mainda["brahma"]
irregda["brahmaana,m"] = mainda["brahma"]
irregda["brahmanesu"] = mainda["brahma"]

irregda["yuvaa"] = mainda["yuva"]
irregda["kammunaa"] = mainda["kamma"]
irregda["kammanaa"] = mainda["kamma"]
irregda["kammuno"] = mainda["kamma"]
irregda["kammaa"] = mainda["kamma"]
irregda["kammasmaa"] = mainda["kamma"]
irregda["kammamhaa"] = mainda["kamma"]
irregda["kammunaa"] = mainda["kamma"]
irregda["kammanaa"] = mainda["kamma"]
irregda["kammato"] = mainda["kamma"]
irregda["kammassa"] = mainda["kamma"]
irregda["kammuno"] = mainda["kamma"]
irregda["kamme"] = mainda["kamma"]
irregda["kammasmi,m"] = mainda["kamma"]
irregda["kammani"] = mainda["kamma"]
irregda["kammaani"] = mainda["kamma"]
irregda["kammaani"] = mainda["kamma"]
irregda["kammehi"] = mainda["kamma"]
irregda["kammaana,m"] = mainda["kamma"]
irregda["kammehi"] = mainda["kamma"]
irregda["kammaana,m"] = mainda["kamma"]
irregda["kammesu"] = mainda["kamma"]

irregda["tayo"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["ti,n,na,m"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["ti,n,na,m"] = mainda["taya"]
irregda["tiisu"] = mainda["taya"]
irregda["tii,ni"] = mainda["taya"]
irregda["ti,ni"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["ti,n,na,m"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["ti,n,na,m"] = mainda["taya"]
irregda["tiisu"] = mainda["taya"]
irregda["tisso"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["tissanna,m"] = mainda["taya"]
irregda["tiihi"] = mainda["taya"]
irregda["tissanna,m"] = mainda["taya"]
irregda["tiisu"] = mainda["taya"]

irregda["pa~ncahi"] = mainda["pa~nca"]
irregda["pa~ncasu"] = mainda["pa~nca"]


irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhosu"] = mainda["ubho"]
irregda["ubho"] = mainda["ubho"]
irregda["ubho"] = mainda["ubho"]
irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhosu"] = mainda["ubho"]
irregda["ubho"] = mainda["ubho"]
irregda["ubho"] = mainda["ubho"]
irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhohi"] = mainda["ubho"]
irregda["ubhinna,m"] = mainda["ubho"]
irregda["ubhosu"] = mainda["ubho"]
irregda["yaavatako"] = mainda["yaavataka"]
irregda["yaavataka,m"] = mainda["yaavataka"]
irregda["yaavatakena"] = mainda["yaavataka"]
irregda["yaavatakaaya"] = mainda["yaavataka"]
irregda["yaavatakassa"] = mainda["yaavataka"]
irregda["yaavatakaa"] = mainda["yaavataka"]
irregda["yaavatakasmaa"] = mainda["yaavataka"]
irregda["yaavatakamhaa"] = mainda["yaavataka"]
irregda["yaavatakato"] = mainda["yaavataka"]
irregda["yaavatakassa"] = mainda["yaavataka"]
irregda["yaavatake"] = mainda["yaavataka"]
irregda["yaavatakasmi,m"] = mainda["yaavataka"]
irregda["yaavatakaa"] = mainda["yaavataka"]
irregda["yaavatake"] = mainda["yaavataka"]
irregda["yaavatakehi"] = mainda["yaavataka"]
irregda["yaavatakaana,m"] = mainda["yaavataka"]
irregda["yaavatakehi"] = mainda["yaavataka"]
irregda["yaavatakaana,m"] = mainda["yaavataka"]
irregda["yaavatakesu"] = mainda["yaavataka"]
irregda["yaavataka,m"] = mainda["yaavataka"]
irregda["yaavataka,m"] = mainda["yaavataka"]
irregda["yaavatakena"] = mainda["yaavataka"]
irregda["yaavatakaaya"] = mainda["yaavataka"]
irregda["yaavatakassa"] = mainda["yaavataka"]
irregda["yaavatakaa"] = mainda["yaavataka"]
irregda["yaavatakasmaa"] = mainda["yaavataka"]
irregda["yaavatakamhaa"] = mainda["yaavataka"]
irregda["yaavatakato"] = mainda["yaavataka"]
irregda["yaavatakassa"] = mainda["yaavataka"]
irregda["yaavatake"] = mainda["yaavataka"]
irregda["yaavatakasmi,m"] = mainda["yaavataka"]
irregda["yaavatakaani"] = mainda["yaavataka"]
irregda["yaavatakaani"] = mainda["yaavataka"]
irregda["yaavatakehi"] = mainda["yaavataka"]
irregda["yaavatakaana,m"] = mainda["yaavataka"]
irregda["yaavatakehi"] = mainda["yaavataka"]
irregda["yaavatakaana,m"] = mainda["yaavataka"]
irregda["yaavatakesu"] = mainda["yaavataka"]
irregda["yaavatikaa"] = mainda["yaavataka"]
irregda["yaavatika,m"] = mainda["yaavataka"]
irregda["yaavatikaaya"] = mainda["yaavataka"]
irregda["yaavatikaaya"] = mainda["yaavataka"]
irregda["yaavatikaaya"] = mainda["yaavataka"]
irregda["yaavatikaaya"] = mainda["yaavataka"]
irregda["yaavatikaaya"] = mainda["yaavataka"]
irregda["yaavatikaaya,m"] = mainda["yaavataka"]
irregda["yaavatikaayo"] = mainda["yaavataka"]
irregda["yaavatikaa"] = mainda["yaavataka"]
irregda["yaavatikaayo"] = mainda["yaavataka"]
irregda["yaavatikaa"] = mainda["yaavataka"]
irregda["yaavatikaahi"] = mainda["yaavataka"]
irregda["yaavatikaana,m"] = mainda["yaavataka"]
irregda["yaavatikaahi"] = mainda["yaavataka"]
irregda["yaavatikaana,m"] = mainda["yaavataka"]
irregda["yaavatikaasu"] = mainda["yaavataka"]
irregda["gava,m"] = mainda["go"]
irregda["gopa"] = mainda["go"] // added
irregda["gavena"] = mainda["go"]
irregda["gavassa"] = mainda["go"]
irregda["gavaa"] = mainda["go"]
irregda["gavassa"] = mainda["go"]
irregda["gave"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gohi"] = mainda["go"]
irregda["gunna,m"] = mainda["go"]
irregda["gohi"] = mainda["go"]
irregda["gunna,m"] = mainda["go"]
irregda["gava,m"] = mainda["go"]
irregda["gosu"] = mainda["go"]
irregda["gava,m"] = mainda["go"]
irregda["gavena"] = mainda["go"]
irregda["gavassa"] = mainda["go"]
irregda["gavaa"] = mainda["go"]
irregda["gavassa"] = mainda["go"]
irregda["gave"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gaavo"] = mainda["go"]
irregda["gohi"] = mainda["go"]
irregda["gunna,m"] = mainda["go"]
irregda["gohi"] = mainda["go"]
irregda["gunna,m"] = mainda["go"]
irregda["gava,m"] = mainda["go"]
irregda["gosu"] = mainda["go"]
irregda["sakhaa"] = mainda["sakha"]
irregda["sakhaa"] = mainda["sakha"]
irregda["sakhaara,m"] = mainda["sakha"]
irregda["sakhinaa"] = mainda["sakha"]
irregda["sakhino"] = mainda["sakha"]
irregda["sakhinaa"] = mainda["sakha"]
irregda["sakhaarasmaa"] = mainda["sakha"]
irregda["sakhino"] = mainda["sakha"]
irregda["sakhe"] = mainda["sakha"]
irregda["sakhaaro"] = mainda["sakha"]
irregda["sakhaaro"] = mainda["sakha"]
irregda["sakhaaro"] = mainda["sakha"]
irregda["sakhaarehi"] = mainda["sakha"]
irregda["sakhiina,m"] = mainda["sakha"]
irregda["sakhaarehi"] = mainda["sakha"]
irregda["sakhiina,m"] = mainda["sakha"]
irregda["sakhaaresu"] = mainda["sakha"]
irregda["bhaanumaa"] = mainda["bhaanumantu"]
irregda["bhaanuma,m"] = mainda["bhaanumantu"]
irregda["agghanako"] = mainda["agghanaka"]
irregda["agghanaka,m"] = mainda["agghanaka"]
irregda["agghanakena"] = mainda["agghanaka"]
irregda["agghanakaaya"] = mainda["agghanaka"]
irregda["agghanakassa"] = mainda["agghanaka"]
irregda["agghanakaa"] = mainda["agghanaka"]
irregda["agghanakasmaa"] = mainda["agghanaka"]
irregda["agghanakassa"] = mainda["agghanaka"]
irregda["agghanake"] = mainda["agghanaka"]
irregda["agghanakasmi,m"] = mainda["agghanaka"]
irregda["agghanakaa"] = mainda["agghanaka"]
irregda["agghanake"] = mainda["agghanaka"]
irregda["agghanakehi"] = mainda["agghanaka"]
irregda["agghanakaana,m"] = mainda["agghanaka"]
irregda["agghanakehi"] = mainda["agghanaka"]
irregda["agghanakaana,m"] = mainda["agghanaka"]
irregda["agghanakesu"] = mainda["agghanaka"]
irregda["agghanaka,m"] = mainda["agghanaka"]
irregda["agghanaka,m"] = mainda["agghanaka"]
irregda["agghanakena"] = mainda["agghanaka"]
irregda["agghanakaaya"] = mainda["agghanaka"]
irregda["agghanakassa"] = mainda["agghanaka"]
irregda["agghanakaa"] = mainda["agghanaka"]
irregda["agghanakasmaa"] = mainda["agghanaka"]
irregda["agghanakassa"] = mainda["agghanaka"]
irregda["agghanake"] = mainda["agghanaka"]
irregda["agghanakasmi,m"] = mainda["agghanaka"]
irregda["agghanakaani"] = mainda["agghanaka"]
irregda["agghanakaani"] = mainda["agghanaka"]
irregda["agghanakehi"] = mainda["agghanaka"]
irregda["agghanakaana,m"] = mainda["agghanaka"]
irregda["agghanakehi"] = mainda["agghanaka"]
irregda["agghanakaana,m"] = mainda["agghanaka"]
irregda["agghanakesu"] = mainda["agghanaka"]
irregda["agghanikaa"] = mainda["agghanaka"]
irregda["agghanika,m"] = mainda["agghanaka"]
irregda["agghanikaaya"] = mainda["agghanaka"]
irregda["agghanikaaya"] = mainda["agghanaka"]
irregda["agghanikaaya"] = mainda["agghanaka"]
irregda["agghanikaaya"] = mainda["agghanaka"]
irregda["agghanikaaya"] = mainda["agghanaka"]
irregda["agghanikaaya,m"] = mainda["agghanaka"]
irregda["agghanikaayo"] = mainda["agghanaka"]
irregda["agghanikaa"] = mainda["agghanaka"]
irregda["agghanikaayo"] = mainda["agghanaka"]
irregda["agghanikaa"] = mainda["agghanaka"]
irregda["agghanikaahi"] = mainda["agghanaka"]
irregda["agghanikaana,m"] = mainda["agghanaka"]
irregda["agghanikaahi"] = mainda["agghanaka"]
irregda["agghanikaana,m"] = mainda["agghanaka"]
irregda["agghanikaasu"] = mainda["agghanaka"]
irregda["asmaa"] = mainda["asmaa"]
irregda["asmanaa"] = mainda["asmaa"]
irregda["asmena"] = mainda["asmaa"]
irregda["asmani"] = mainda["asmaa"]
irregda["katamo"] = mainda["katama"]
irregda["katama,m"] = mainda["katama"]
irregda["katamena"] = mainda["katama"]
irregda["katamassa"] = mainda["katama"]
irregda["katamasmaa"] = mainda["katama"]
irregda["katamamhaa"] = mainda["katama"]
irregda["katamassa"] = mainda["katama"]
irregda["katamasmi,m"] = mainda["katama"]
irregda["katamamhi"] = mainda["katama"]
irregda["katame"] = mainda["katama"]
irregda["katame"] = mainda["katama"]
irregda["katamehi"] = mainda["katama"]
irregda["katamesa,m"] = mainda["katama"]
irregda["katamehi"] = mainda["katama"]
irregda["katamesa,m"] = mainda["katama"]
irregda["katamesaana,m"] = mainda["katama"]
irregda["katamesu"] = mainda["katama"]
irregda["katama,m"] = mainda["katama"]
irregda["katama,m"] = mainda["katama"]
irregda["katamena"] = mainda["katama"]
irregda["katamassa"] = mainda["katama"]
irregda["katamasmaa"] = mainda["katama"]
irregda["katamamhaa"] = mainda["katama"]
irregda["katamassa"] = mainda["katama"]
irregda["katamasmi,m"] = mainda["katama"]
irregda["katamamhi"] = mainda["katama"]
irregda["katamaani"] = mainda["katama"]
irregda["katamaani"] = mainda["katama"]
irregda["katamehi"] = mainda["katama"]
irregda["katamesa,m"] = mainda["katama"]
irregda["katamehi"] = mainda["katama"]
irregda["katamesa,m"] = mainda["katama"]
irregda["katamesu"] = mainda["katama"]
irregda["katamaa"] = mainda["katama"]
irregda["katama,m"] = mainda["katama"]
irregda["katamaaya"] = mainda["katama"]
irregda["katamassaa"] = mainda["katama"]
irregda["katamaaya"] = mainda["katama"]
irregda["katamassaa"] = mainda["katama"]
irregda["katamaaya"] = mainda["katama"]
irregda["katamassa,m"] = mainda["katama"]
irregda["katamaa"] = mainda["katama"]
irregda["katamaa"] = mainda["katama"]
irregda["katamaahi"] = mainda["katama"]
irregda["katamaasa,m"] = mainda["katama"]
irregda["katamaahi"] = mainda["katama"]
irregda["katamaasa,m"] = mainda["katama"]
irregda["katamaasu"] = mainda["katama"]
irregda["odako"] = mainda["odaka"]
irregda["odaka,m"] = mainda["odaka"]
irregda["odakena"] = mainda["odaka"]
irregda["odakaaya"] = mainda["odaka"]
irregda["odakassa"] = mainda["odaka"]
irregda["odakaa"] = mainda["odaka"]
irregda["odakasmaa"] = mainda["odaka"]
irregda["odakassa"] = mainda["odaka"]
irregda["odake"] = mainda["odaka"]
irregda["odakasmi,m"] = mainda["odaka"]
irregda["odakaa"] = mainda["odaka"]
irregda["odake"] = mainda["odaka"]
irregda["odakehi"] = mainda["odaka"]
irregda["odakaana,m"] = mainda["odaka"]
irregda["odakehi"] = mainda["odaka"]
irregda["odakaana,m"] = mainda["odaka"]
irregda["odakesu"] = mainda["odaka"]
irregda["odaka,m"] = mainda["odaka"]
irregda["odaka,m"] = mainda["odaka"]
irregda["odakena"] = mainda["odaka"]
irregda["odakaaya"] = mainda["odaka"]
irregda["odakassa"] = mainda["odaka"]
irregda["odakaa"] = mainda["odaka"]
irregda["odakasmaa"] = mainda["odaka"]
irregda["odakassa"] = mainda["odaka"]
irregda["odake"] = mainda["odaka"]
irregda["odakasmi,m"] = mainda["odaka"]
irregda["odakaani"] = mainda["odaka"]
irregda["odakaani"] = mainda["odaka"]
irregda["odakehi"] = mainda["odaka"]
irregda["odakaana,m"] = mainda["odaka"]
irregda["odakehi"] = mainda["odaka"]
irregda["odakaana,m"] = mainda["odaka"]
irregda["odakesu"] = mainda["odaka"]
irregda["odikaa"] = mainda["odaka"]
irregda["odika,m"] = mainda["odaka"]
irregda["odikaaya"] = mainda["odaka"]
irregda["odikaaya"] = mainda["odaka"]
irregda["odikaaya"] = mainda["odaka"]
irregda["odikaaya"] = mainda["odaka"]
irregda["odikaaya"] = mainda["odaka"]
irregda["odikaaya,m"] = mainda["odaka"]
irregda["odikaayo"] = mainda["odaka"]
irregda["odikaa"] = mainda["odaka"]
irregda["odikaayo"] = mainda["odaka"]
irregda["odikaa"] = mainda["odaka"]
irregda["odikaahi"] = mainda["odaka"]
irregda["odikaana,m"] = mainda["odaka"]
irregda["odikaahi"] = mainda["odaka"]
irregda["odikaana,m"] = mainda["odaka"]
irregda["odikaasu"] = mainda["odaka"]

/*

irregda["santo"] = mainda["santa"]
irregda["satiz2"] = mainda["santa"]
irregda["sante"] = mainda["santa"]
irregda["santo"] = mainda["santa"]
irregda["sante"] = mainda["santa"]
irregda["sabbhi"] = mainda["santa"]
irregda["sata,m"] = mainda["santa"]
irregda["santesu"] = mainda["santa"]
irregda["santa,m"] = mainda["santa"]
irregda["santa,m"] = mainda["santa"]
irregda["sata,m"] = mainda["santa"]
irregda["sataa"] = mainda["santa"]
irregda["santato"] = mainda["santa"]

irregda["santaani"] = mainda["santa"]
irregda["sabbhi"] = mainda["santa"]
irregda["sata,m"] = mainda["santa"]
irregda["santesu"] = mainda["santa"]
irregda["satii"] = mainda["santa"]
irregda["sati,m"] = mainda["santa"]

irregda["satiyaa"] = mainda["santa"]
irregda["satiya,m"] = mainda["santa"]
irregda["satiyo"] = mainda["santa"]
irregda["satiihi"] = mainda["santa"]
irregda["satiina,m"] = mainda["santa"]
irregda["satiihi"] = mainda["santa"]
irregda["satiina,m"] = mainda["santa"]
irregda["satiisu"] = mainda["santa"]

*/

irregda["jaati,m"] = mainda["jaati"]
irregda["jaatiyaa"] = mainda["jaati"]
irregda["jaccaa"] = mainda["jaati"]
irregda["jaatiyaa"] = mainda["jaati"]
irregda["jaccaa"] = mainda["jaati"]
irregda["jaatiyaa"] = mainda["jaati"]
irregda["jaccaa"] = mainda["jaati"]
irregda["jaatiyaa"] = mainda["jaati"]
irregda["jaccaa"] = mainda["jaati"]
irregda["jaatiyaa"] = mainda["jaati"]
irregda["jaatiya,m"] = mainda["jaati"]
irregda["jaatiyo"] = mainda["jaati"]
irregda["jaatiyo"] = mainda["jaati"]
irregda["jaatiyo"] = mainda["jaati"]
irregda["jaatiihi"] = mainda["jaati"]
irregda["jaatiina,m"] = mainda["jaati"]
irregda["jaatiihi"] = mainda["jaati"]
irregda["jaatiina,m"] = mainda["jaati"]
irregda["jaatiisu"] = mainda["jaati"]
irregda["brahaa"] = mainda["brahanta"]
irregda["brahanta,m"] = mainda["brahanta"]
irregda["brahantaa"] = mainda["brahanta"]
irregda["brahatii"] = mainda["brahanta"]
irregda["candimaa"] = mainda["candimantu"]
irregda["catubba,n,ne"] = mainda["catubba,n,naa"]
irregda["catubba,n,nehi"] = mainda["catubba,n,naa"]
irregda["catubba,n,naana,m"] = mainda["catubba,n,naa"]
irregda["catubba,n,nehi"] = mainda["catubba,n,naa"]
irregda["catubba,n,naana,m"] = mainda["catubba,n,naa"]
irregda["catubba,n,nesu"] = mainda["catubba,n,naa"]

irregda["ta"] = mainda["ta`"]
irregda["ta,mz2"] = mainda["ta`"]
irregda["ten`"] = mainda["ta`"]
irregda["tesa,m"] = mainda["ta`"]
irregda["tasmaa"] = mainda["ta`"]
irregda["tad"] = mainda["ta`"]

irregda["tassa,m"] = mainda["ta`"]
irregda["taahi"] = mainda["ta`"]

irregda["yesa,m"] = mainda["ya"]
irregda["yad"] = mainda["ya"]
irregda["yassaa"] = mainda["ya"]
irregda["yassa,m"] = mainda["ya"]
irregda["yaasa,m"] = mainda["ya"]



irregda["kissa"] = mainda["ka"]
irregda["kasmaa"] = mainda["ka"]
irregda["kamhaa"] = mainda["ka"]
irregda["kismi,m"] = mainda["ka"]
irregda["kimhi"] = mainda["ka"]

irregda["kehi"] = mainda["ka"]
irregda["kesa,m"] = mainda["ka"]
irregda["kehi"] = mainda["ka"]
irregda["kesa,m"] = mainda["ka"]
irregda["kesu"] = mainda["ka"]

irregda["ki,m"] = mainda["ka"]
irregda["kaani"] = mainda["ka"]

irregda["kaa"] = mainda["ka"]
irregda["ka,m"] = mainda["ka"]
irregda["kaayaz2"] = mainda["ka"] // changed
irregda["kassaa"] = mainda["ka"]

irregda["kaaya,m"] = mainda["ka"]
irregda["kassa,m"] = mainda["ka"]

irregda["kaahi"] = mainda["ka"]
irregda["kaasa,m"] = mainda["ka"]
irregda["kaasu"] = mainda["ka"]

irregda["eso"] = mainda["eta"]
irregda["esa"] = mainda["eta"]
irregda["eta,m"] = mainda["eta"]
irregda["etena"] = mainda["eta"]
irregda["etassa"] = mainda["eta"]
irregda["etasmaa"] = mainda["eta"]
irregda["etamhaa"] = mainda["eta"]
irregda["etassa"] = mainda["eta"]
irregda["etasmi,m"] = mainda["eta"]
irregda["etamhi"] = mainda["eta"]
irregda["ete"] = mainda["eta"]
irregda["etehi"] = mainda["eta"]
irregda["etesa,m"] = mainda["eta"]
irregda["etehi"] = mainda["eta"]
irregda["etesa,m"] = mainda["eta"]
irregda["etesu"] = mainda["eta"]
irregda["eta,m"] = mainda["eta"]
irregda["eta"] = mainda["etad"]
irregda["eta,m"] = mainda["eta"]

irregda["etena"] = mainda["eta"]
irregda["etassa"] = mainda["eta"]
irregda["etasmaa"] = mainda["eta"]
irregda["etamhaa"] = mainda["eta"]
irregda["etassa"] = mainda["eta"]
irregda["etasmi,m"] = mainda["eta"]
irregda["etamhi"] = mainda["eta"]
irregda["etaani"] = mainda["eta"]
irregda["etaani"] = mainda["eta"]
irregda["etehi"] = mainda["eta"]
irregda["etesa,m"] = mainda["eta"]
irregda["etehi"] = mainda["eta"]
irregda["etesa,m"] = mainda["eta"]
irregda["etesu"] = mainda["eta"]
irregda["esaa"] = mainda["eta"]
irregda["eta,m"] = mainda["eta"]
irregda["etaaya"] = mainda["eta"]
irregda["etassaa"] = mainda["eta"]
irregda["etaaya"] = mainda["eta"]
irregda["etassaa"] = mainda["eta"]
irregda["etaaya,m"] = mainda["eta"]
irregda["etaaya"] = mainda["eta"]
irregda["etassa,m"] = mainda["eta"]
irregda["etaa"] = mainda["eta"]
irregda["etaa"] = mainda["eta"]
irregda["etaahi"] = mainda["eta"]
irregda["etaasa,m"] = mainda["eta"]
irregda["etaahi"] = mainda["eta"]
irregda["etaasa,m"] = mainda["eta"]
irregda["etaasu"] = mainda["eta"]
irregda["ekaani"] = mainda["eka"]
irregda["ekehi"] = mainda["eka"]
irregda["ekesa,m"] = mainda["eka"]
irregda["ekehi"] = mainda["eka"]
irregda["ekesa,m"] = mainda["eka"]
irregda["ekesu"] = mainda["eka"]
irregda["ekissaa"] = mainda["eka"]
irregda["ekaasa,m"] = mainda["eka"]

irregda["ekesa,m"] = mainda["eka"]
irregda["ekissaa"] = mainda["eka"]
irregda["ekaahi"] = mainda["eka"]
irregda["ekaasa,m"] = mainda["eka"]
irregda["pa,tiraajaana,m"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~naa"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~no"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~naa"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~no"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajini"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~ne"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajaano"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajaano"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajuuhi"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~na,m"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajuuhi"] = mainda["pa,tiraajaa"]
irregda["pa,tira~n~na,m"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajuuna,m"] = mainda["pa,tiraajaa"]
irregda["pa,tiraajuusu"] = mainda["pa,tiraajaa"]

irregda["raajaana,m"] = mainda["raajaa"]
irregda["ra~n~naa"] = mainda["raajaa"]
irregda["ra~n~no"] = mainda["raajaa"]
irregda["ra~n~naa"] = mainda["raajaa"]
irregda["ra~n~no"] = mainda["raajaa"]
irregda["raajini"] = mainda["raajaa"]
irregda["ra~n~ne"] = mainda["raajaa"]
irregda["raajaano"] = mainda["raajaa"]
irregda["raajaano"] = mainda["raajaa"]
irregda["raajuuhi"] = mainda["raajaa"]
irregda["ra~n~na,m"] = mainda["raajaa"]
irregda["raajuuhi"] = mainda["raajaa"]
irregda["ra~n~na,m"] = mainda["raajaa"]
irregda["raajuuna,m"] = mainda["raajaa"]
irregda["raajuusu"] = mainda["raajaa"]
irregda["bhikkhu"] = mainda["bhikkhu"]
irregda["bhikkhu"] = mainda["bhikkhu"]
irregda["bhikkhu,m"] = mainda["bhikkhu"]
irregda["bhikkhunaa"] = mainda["bhikkhu"]
irregda["bhikkhuno"] = mainda["bhikkhu"]
irregda["bhikkhunaa"] = mainda["bhikkhu"]
irregda["bhikkhuno"] = mainda["bhikkhu"]
irregda["bhikkhussa"] = mainda["bhikkhu"]
irregda["bhikkhusmi,m"] = mainda["bhikkhu"]
irregda["bhikkhavo"] = mainda["bhikkhu"]
irregda["bhikkhuu"] = mainda["bhikkhu"]
irregda["bhikkhavo"] = mainda["bhikkhu"]
irregda["bhikkhuu"] = mainda["bhikkhu"]
irregda["bhikkhave"] = mainda["bhikkhu"]
irregda["bhikkhavo"] = mainda["bhikkhu"]
irregda["bhikkhuu"] = mainda["bhikkhu"]
irregda["bhikkhuuhi"] = mainda["bhikkhu"]
irregda["bhikkhuuna,m"] = mainda["bhikkhu"]
irregda["bhikkhuuhi"] = mainda["bhikkhu"]
irregda["bhikkhuuna,m"] = mainda["bhikkhu"]
irregda["bhikkhuusu"] = mainda["bhikkhu"]
irregda["arahaa"] = mainda["arahant"]
irregda["araha,m"] = mainda["arahant"]
irregda["arahanto"] = mainda["arahant"]
irregda["arahaa"] = mainda["arahant"]
irregda["arahanta,m"] = mainda["arahant"]
irregda["arahataa"] = mainda["arahant"]
irregda["arahantena"] = mainda["arahant"]
irregda["arahato"] = mainda["arahant"]
irregda["arahataa"] = mainda["arahant"]
irregda["arahato"] = mainda["arahant"]
irregda["arahantassa"] = mainda["arahant"]
irregda["arahati"] = mainda["arahant"]
irregda["arahante"] = mainda["arahant"]
irregda["arahanto"] = mainda["arahant"]
irregda["arahantaa"] = mainda["arahant"]
irregda["arahanto"] = mainda["arahant"]
irregda["arahante"] = mainda["arahant"]
irregda["arahantehi"] = mainda["arahant"]
irregda["arahantaana,m"] = mainda["arahant"]
irregda["arahata,m"] = mainda["arahant"]
irregda["arahantehi"] = mainda["arahant"]
irregda["arahantaana,m"] = mainda["arahant"]
irregda["arahata,m"] = mainda["arahant"]
irregda["arahantesu"] = mainda["arahant"]

irregda["cattaaro"] = mainda["catu"]
irregda["cattaaro"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catusu"] = mainda["catu"]
irregda["catuusu"] = mainda["catu"]
irregda["cattaari"] = mainda["catu"]
irregda["cattaari"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catusu"] = mainda["catu"]
irregda["catuusu"] = mainda["catu"]
irregda["cattasso"] = mainda["catu"]
irregda["cattasso"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catuhi"] = mainda["catu"]
irregda["catuuhi"] = mainda["catu"]
irregda["catunna,m"] = mainda["catu"]
irregda["catusu"] = mainda["catu"]
irregda["catuusu"] = mainda["catu"]
irregda["addhaa"] = mainda["addhaa"]
irregda["addhaana,m"] = mainda["addhaa"]
irregda["addhunaa"] = mainda["addhaa"]
irregda["addhuno"] = mainda["addhaa"]
irregda["addhaa"] = mainda["addhaa"]
irregda["muddhaa"] = mainda["muddhaz2"]
irregda["muddha,m"] = mainda["muddhaz2"]
irregda["muddha,m"] = mainda["muddhaz2"]
irregda["muddhaana,m"] = mainda["muddhaz2"]
irregda["muddhanaa"] = mainda["muddhaz2"]
irregda["muddhani"] = mainda["muddhaz2"]
irregda["pumaa"] = mainda["puma"]
irregda["puma,m"] = mainda["puma"]
irregda["puma"] = mainda["puma"]
irregda["pumaana,m"] = mainda["puma"]
irregda["puma,m"] = mainda["puma"]
irregda["pumaanaa"] = mainda["puma"]
irregda["pumunaa"] = mainda["puma"]
irregda["pumena"] = mainda["puma"]
irregda["pumuno"] = mainda["puma"]
irregda["pumassa"] = mainda["puma"]
irregda["pumunaa"] = mainda["puma"]
irregda["pumaanaa"] = mainda["puma"]
irregda["pumaa"] = mainda["puma"]
irregda["pumasmaa"] = mainda["puma"]
irregda["pumamhaa"] = mainda["puma"]
irregda["pumuno"] = mainda["puma"]
irregda["pumassa"] = mainda["puma"]
irregda["pumaane"] = mainda["puma"]
irregda["pume"] = mainda["puma"]
irregda["pumasmi,m"] = mainda["puma"]
irregda["pumamhi"] = mainda["puma"]
irregda["pumaano"] = mainda["puma"]
irregda["pumaa"] = mainda["puma"]
irregda["pumaano"] = mainda["puma"]
irregda["pumaa"] = mainda["puma"]
irregda["pumaano"] = mainda["puma"]
irregda["pume"] = mainda["puma"]
irregda["pumaanehi"] = mainda["puma"]
irregda["pumaanebhi"] = mainda["puma"]
irregda["pumehi"] = mainda["puma"]
irregda["pumebhi"] = mainda["puma"]
irregda["pumaana,m"] = mainda["puma"]
irregda["pumaanehi"] = mainda["puma"]
irregda["pumaanebhi"] = mainda["puma"]
irregda["pumehi"] = mainda["puma"]
irregda["pumebhi"] = mainda["puma"]
irregda["pumaana,m"] = mainda["puma"]
irregda["pumaanesu"] = mainda["puma"]
irregda["pumaasu"] = mainda["puma"]
irregda["pumesu"] = mainda["puma"]
irregda["dve"] = mainda["dvi"]
irregda["dve"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviisu"] = mainda["dvi"]
irregda["dve"] = mainda["dvi"]
irregda["dve"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviisu"] = mainda["dvi"]
irregda["dve"] = mainda["dvi"]
irregda["dve"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviihi"] = mainda["dvi"]
irregda["dvinna,m"] = mainda["dvi"]
irregda["dviisu"] = mainda["dvi"]
irregda["bhava,m"] = mainda["bhavanta"]
irregda["bho"] = mainda["bhavanta"]
irregda["bhavanta,m"] = mainda["bhavanta"]
irregda["bhotaa"] = mainda["bhavanta"]
irregda["bhoto"] = mainda["bhavanta"]
irregda["bhotaa"] = mainda["bhavanta"]
irregda["bhoto"] = mainda["bhavanta"]
irregda["bhoti"] = mainda["bhavanta"]

var pedda = [];
for (attr in mainda) { pedda[attr] = mainda[attr]; }
for (attr in irregda) { pedda[attr] = irregda[attr]; }

