
// Irregular Verbs

// removed: abhijaanaati = abhijaanaati
mainda["abhijaananti"] = mainda["abhijaanaati"];
mainda["abhijaanaasi"] = mainda["abhijaanaati"];
mainda["abhijaanaatha"] = mainda["abhijaanaati"];
mainda["abhijaanaami"] = mainda["abhijaanaati"];
mainda["abhijaanaama"] = mainda["abhijaanaati"];

mainda["abhijaanaahi"] = mainda["abhijaanaati"];
mainda["abhijaanissati"] = mainda["abhijaanaati"];
mainda["abhijaanissanti"] = mainda["abhijaanaati"];
mainda["abhijaanissasi"] = mainda["abhijaanaati"];
mainda["abhijaanissatha"] = mainda["abhijaanaati"];
mainda["abhijaanissaami"] = mainda["abhijaanaati"];
mainda["abhijaanissaama"] = mainda["abhijaanaati"];
mainda["abhijaaneyya"] = mainda["abhijaanaati"];
mainda["abhija~n~naa"] = mainda["abhijaanaati"];
// removed: abhisa`nkharoti = abhisa`nkharoti
mainda["abhisa`nkharonti"] = mainda["abhisa`nkharoti"];
mainda["abhisa`nkhareyya"] = mainda["abhisa`nkharoti"];
mainda["abhisa`nkhareyya,m"] = mainda["abhisa`nkharoti"];
// removed: acchati = acchati
mainda["acchanti"] = mainda["acchati"];
mainda["acchenti"] = mainda["acchati"];
mainda["acchasi"] = mainda["acchati"];
mainda["acchaami"] = mainda["acchati"];
mainda["acchatu"] = mainda["acchati"];
mainda["accha"] = mainda["acchati"];
mainda["accheyya"] = mainda["acchati"];
mainda["acchata,m"] = mainda["acchati"];
mainda["acchassu"] = mainda["acchati"];
// removed: aadadaati = aadadaati
// removed: addasa = addasa
// removed: addasaa = addasaa
mainda["addasa,msu"] = mainda["addasaa"];
// removed: addasaa = addasaa
mainda["addasatha"] = mainda["addasaa"];
mainda["addasa,m"] = mainda["addasaa"];
mainda["addakkhi,m"] = mainda["addasaa"];
mainda["addasaama"] = mainda["addasaa"];
// removed: adhi,t,thaati = adhi,t,thaati
mainda["adhiti,t,thati"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thahati"] = mainda["adhi,t,thaati"];
mainda["adhi,t,theti"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thahanti"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thenti"] = mainda["adhi,t,thaati"];
mainda["adhiti,t,thasi"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thaami"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thema"] = mainda["adhi,t,thaati"];

mainda["adhi,t,thaahi"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thehi"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thaheyya"] = mainda["adhi,t,thaati"];
mainda["adhi,t,theyya"] = mainda["adhi,t,thaati"];
mainda["adhi,t,thaheyyaasi"] = mainda["adhi,t,thaati"];
// removed: adhiseti = adhiseti
mainda["adhisayati"] = mainda["adhiseti"];
mainda["adhisayeyya"] = mainda["adhiseti"];
// removed: aadisati = aadisati
mainda["aadisanti"] = mainda["aadisati"];
mainda["aadiseyya"] = mainda["aadisati"];
mainda["aadise"] = mainda["aadisati"];
mainda["aadiseyyaasi"] = mainda["aadisati"];
// removed: aadiyati = aadiyati
mainda["aadeti"] = mainda["aadiyati"];
mainda["aadatte"] = mainda["aadiyati"];
mainda["aadiyanti"] = mainda["aadiyati"];
mainda["aadenti"] = mainda["aadiyati"];
mainda["aadiyasi"] = mainda["aadiyati"];
mainda["aadiyatha"] = mainda["aadiyati"];
mainda["aadetha"] = mainda["aadiyati"];
mainda["aadiyaami"] = mainda["aadiyati"];
mainda["aadiyaama"] = mainda["aadiyati"];

mainda["aadiyantu"] = mainda["aadiyati"];
mainda["aadiya"] = mainda["aadiyati"];
mainda["aadiyissati"] = mainda["aadiyati"];
mainda["aadiyissanti"] = mainda["aadiyati"];
mainda["aadiyissasi"] = mainda["aadiyati"];
mainda["aadiyissatha"] = mainda["aadiyati"];
mainda["aadiyissaami"] = mainda["aadiyati"];
mainda["aadiyissaama"] = mainda["aadiyati"];
mainda["aadiyeyya"] = mainda["aadiyati"];
mainda["aadiyeyyu,m"] = mainda["aadiyati"];
mainda["aadiyeyyaasi"] = mainda["aadiyati"];
mainda["aadiyeyyaatha"] = mainda["aadiyati"];
mainda["aadiyeyya,m"] = mainda["aadiyati"];
mainda["aadiyeyyaama"] = mainda["aadiyati"];
mainda["aahaasi"] = mainda["aahari"];
// removed: aahari = aahari
mainda["aaharesi"] = mainda["aahari"];
mainda["aahari,msu"] = mainda["aahari"];
mainda["aaha,msu"] = mainda["aahari"];
mainda["aahari,m"] = mainda["aahari"];
mainda["aaharaama"] = mainda["aahari"];
mainda["aaharimha"] = mainda["aahari"];
mainda["ahesu,m"] = mainda["ahosi"];
// removed: ahosi = ahosi
mainda["ahuvattha"] = mainda["ahosi"];
mainda["ahosi,m"] = mainda["ahosi"];
mainda["ahumha"] = mainda["ahosi"];
mainda["a~n~naati"] = mainda["aajaanaati"];
mainda["aajaananti"] = mainda["aajaanaati"];
mainda["aajaanaasi"] = mainda["aajaanaati"];
mainda["aajaanaatha"] = mainda["aajaanaati"];
mainda["aajaanaami"] = mainda["aajaanaati"];
mainda["aajaanaama"] = mainda["aajaanaati"];

mainda["aajaanaahi"] = mainda["aajaanaati"];
mainda["aajaaneyya"] = mainda["aajaanaati"];
mainda["aajaaneyyu,m"] = mainda["aajaanaati"];
mainda["aajaaneyyaasi"] = mainda["aajaanaati"];
mainda["aajaaneyyaatha"] = mainda["aajaanaati"];
mainda["aajaaneyya,m"] = mainda["aajaanaati"];
mainda["aajaaneyyaama"] = mainda["aajaanaati"];
// removed: ajjhagaa = ajjhagaa
mainda["ajjhagu"] = mainda["ajjhagaa"];
mainda["ajjhaguu"] = mainda["ajjhagaa"];
mainda["ajjhagu,m"] = mainda["ajjhagaa"];
mainda["ajjhaga,msu"] = mainda["ajjhagaa"];
// removed: ajjhagaa = ajjhagaa
mainda["adhiga,m"] = mainda["ajjhagaa"];
mainda["ajjhaga,m"] = mainda["ajjhagaa"];
// removed: ajjhagaa = ajjhagaa
// removed: ajjhagamaa = ajjhagamaa
mainda["ajjhagacchi"] = mainda["ajjhagamaa"];
mainda["ajjhaga~nchi"] = mainda["ajjhagamaa"];
mainda["adhigacchi"] = mainda["ajjhagamaa"];
mainda["adhiga~nchi"] = mainda["ajjhagamaa"];
mainda["ajjhagama,msu"] = mainda["ajjhagamaa"];
mainda["ajjhagamu,m"] = mainda["ajjhagamaa"];
mainda["ajjhaga,msu"] = mainda["ajjhagamaa"];
mainda["adhigami,msu"] = mainda["ajjhagamaa"];
mainda["adhigacchi,msu"] = mainda["ajjhagamaa"];
// removed: ajjhagamaa = ajjhagamaa
mainda["ajjhagamaasi"] = mainda["ajjhagamaa"];
mainda["ajjhagama,m"] = mainda["ajjhagamaa"];
mainda["ajjhagami,m"] = mainda["ajjhagamaa"];
mainda["adhigami,m"] = mainda["ajjhagamaa"];
mainda["adhigacchi,m"] = mainda["ajjhagamaa"];
mainda["adhigacchissa,m"] = mainda["ajjhagamaa"];
mainda["ajjhagamaamase"] = mainda["ajjhagamaa"];
mainda["aanayati"] = mainda["aaneti"];
mainda["aanayaami"] = mainda["aaneti"];
// removed: aaneti = aaneti
mainda["aanenti"] = mainda["aaneti"];
mainda["aanesi"] = mainda["aaneti"];
mainda["aanetha"] = mainda["aaneti"];
mainda["aanemi"] = mainda["aaneti"];
mainda["aanema"] = mainda["aaneti"];

mainda["aanehi"] = mainda["aaneti"];
mainda["aaneyya"] = mainda["aaneti"];
mainda["aaneyyaatha"] = mainda["aaneti"];
mainda["aaneyyaama"] = mainda["aaneti"];
// removed: antaradhaayati = antaradhaayati
mainda["antaradhaayanti"] = mainda["antaradhaayati"];
mainda["antaradhaayasi"] = mainda["antaradhaayati"];
mainda["antaradhaayatha"] = mainda["antaradhaayati"];
mainda["antaradhaayaami"] = mainda["antaradhaayati"];
mainda["antaradhaayaama"] = mainda["antaradhaayati"];
mainda["antaradhaayatu"] = mainda["antaradhaayati"];
mainda["antaradhaayantu"] = mainda["antaradhaayati"];
mainda["antaradhaayaahi"] = mainda["antaradhaayati"];
mainda["antaradhaayatha"] = mainda["antaradhaayati"];
mainda["antaradhaayaami"] = mainda["antaradhaayati"];
mainda["antaradhaayaama"] = mainda["antaradhaayati"];
mainda["antaradhaayissati"] = mainda["antaradhaayati"];
mainda["antaradhaayissanti"] = mainda["antaradhaayati"];
mainda["antaradhaayissasi"] = mainda["antaradhaayati"];
mainda["antaradhaayissatha"] = mainda["antaradhaayati"];
mainda["antaradhaayissaami"] = mainda["antaradhaayati"];
mainda["antaradhaayissaama"] = mainda["antaradhaayati"];
mainda["antaradhaayeyya"] = mainda["antaradhaayati"];
mainda["antaradhaayatha"] = mainda["antaradhaayati"];

mainda["antaradhaayassu"] = mainda["antaradhaayati"];
mainda["anubhonti"] = mainda["anubhoti"];
mainda["anubhosi"] = mainda["anubhoti"];
mainda["anubhotha"] = mainda["anubhoti"];
mainda["anubhomi"] = mainda["anubhoti"];
mainda["anubhoma"] = mainda["anubhoti"];
mainda["anubhotu"] = mainda["anubhoti"];
mainda["anubhontu"] = mainda["anubhoti"];
mainda["anubhohi"] = mainda["anubhoti"];

mainda["anukaronti"] = mainda["anukaroti"];
mainda["anukubbanti"] = mainda["anukaroti"];
mainda["anukaromi"] = mainda["anukaroti"];

mainda["anupadeti"] = mainda["anuppadeti"];

mainda["anuppadehi"] = mainda["anuppadeti"];
mainda["anupadajjeyya"] = mainda["anuppadeti"];
mainda["anuppadajju,m"] = mainda["anuppadeti"];
mainda["anuppadajjeyyu,m"] = mainda["anuppadeti"];
mainda["anuppadajjeyyaasi"] = mainda["anuppadeti"];
mainda["anupadajjeyyaasi"] = mainda["anuppadeti"];
mainda["anuppadeyyaasi"] = mainda["anuppadeti"];
mainda["anupadajjeyyaamaa"] = mainda["anuppadeti"];
// removed: anuseti = anuseti
mainda["anusenti"] = mainda["anuseti"];
// removed: anvagaa = anvagaa
mainda["anvaga,m"] = mainda["anvagaa"];
mainda["anvaguu"] = mainda["anvagaa"];
mainda["anvaguu"] = mainda["anvagaa"];
mainda["anvaga,m"] = mainda["anvagaa"];
mainda["annagaa"] = mainda["anvagaa"];
mainda["anvaguu"] = mainda["anvagaa"];
// removed: aarabhati = aarabhati
mainda["aarambhati"] = mainda["aarabhati"];

mainda["aarabhate"] = mainda["aarabhati"];

mainda["aarabhavho"] = mainda["aarabhati"];
// removed: aasi = aasi
mainda["aasu,m"] = mainda["aasi"];
mainda["aasu"] = mainda["aasi"];
mainda["aasi,msu"] = mainda["aasi"];
mainda["aasisu,m"] = mainda["aasi"];
// removed: aasi = aasi
mainda["aasi,m"] = mainda["aasi"];
mainda["aasimhaa"] = mainda["aasi"];
mainda["siyaa"] = mainda["assa"];
// removed: assa = assa
mainda["assu"] = mainda["assa"];
mainda["siyu,m"] = mainda["assa"];
mainda["siya,msu"] = mainda["assa"];
mainda["assu,m"] = mainda["assa"];
mainda["siyaa"] = mainda["assa"];
mainda["assa"] = mainda["assaz5"];
mainda["assasi"] = mainda["assa"];
mainda["assu"] = mainda["assa"];
mainda["assatha"] = mainda["assa"];
mainda["siya,m"] = mainda["assa"];
mainda["siyaa"] = mainda["assa"];
mainda["assa,m"] = mainda["assa"];
mainda["assaama"] = mainda["assa"];
// removed: assosi = assosi
mainda["assosu,m"] = mainda["assosi"];
// removed: assosi = assosi
mainda["assuttha"] = mainda["assosi"];
mainda["assosi,m"] = mainda["assosi"];
mainda["assumha"] = mainda["assosi"];
// removed: atibhoti = atibhoti
mainda["atibhonti"] = mainda["atibhoti"];
mainda["atibhomi"] = mainda["atibhoti"];
mainda["accagaa"] = mainda["atigacchati"];
mainda["atigaa"] = mainda["atigacchati"];
mainda["accagu,m"] = mainda["atigacchati"];
mainda["accaguu"] = mainda["atigacchati"];
mainda["accagamaa"] = mainda["atigacchati"];
// removed: atthi = atthi
mainda["santi"] = mainda["atthi"];
mainda["asi"] = mainda["atthi"];
mainda["si"] = mainda["atthi"];
mainda["atthaz4"] = mainda["atthi"];
mainda["asmi"] = mainda["atthi"];
mainda["smi"] = mainda["atthi"];
mainda["amhi"] = mainda["atthi"];
mainda["mhi"] = mainda["atthi"];
mainda["asma"] = mainda["atthi"];
mainda["asmaa"] = mainda["atthi"];
mainda["amha"] = mainda["atthi"];
mainda["smase"] = mainda["atthi"];
mainda["atthu"] = mainda["atthi"];

mainda["avoca"] = mainda["vattiz1"];
mainda["amhaase"] = mainda["atthi"];
mainda["amhase"] = mainda["atthi"];
mainda["amhaa"] = mainda["atthi"];
// removed: avoca = avoca
mainda["avocu,m"] = mainda["avoca"];
// removed: avoca = avoca
mainda["avaca"] = mainda["avoca"];
mainda["avocuttha"] = mainda["avoca"];
mainda["avacuttha"] = mainda["avoca"];
mainda["avoca,m"] = mainda["avoca"];
mainda["avocumha"] = mainda["avoca"];
mainda["avocumhaa"] = mainda["avoca"];
// removed: bruuti = bruuti
mainda["bruusi"] = mainda["bruuti"];
mainda["bruutha"] = mainda["bruuti"];
mainda["bruumi"] = mainda["bruuti"];

mainda["bruuhi"] = mainda["bruuti"];
mainda["cetayati"] = mainda["cinteti"];
mainda["cetayanti"] = mainda["cinteti"];
mainda["cetayasi"] = mainda["cinteti"];
mainda["cetayatha"] = mainda["cinteti"];
mainda["cetayaami"] = mainda["cinteti"];
mainda["cetayaama"] = mainda["cinteti"];
mainda["ceteti"] = mainda["cinteti"];
mainda["cetenti"] = mainda["cinteti"];
mainda["cetesi"] = mainda["cinteti"];
mainda["cetetha"] = mainda["cinteti"];
mainda["cetemi"] = mainda["cinteti"];
mainda["cetema"] = mainda["cinteti"];
mainda["cinteyya"] = mainda["cinteti"];
mainda["cetaye"] = mainda["cinteti"];
mainda["cinteyyu,m"] = mainda["cinteti"];
mainda["cinteyyaasi"] = mainda["cinteti"];
mainda["cinteyyaatha"] = mainda["cinteti"];
mainda["cinteyya,m"] = mainda["cinteti"];
mainda["cinteyyaami"] = mainda["cinteti"];
mainda["cinteyyaama"] = mainda["cinteti"];
mainda["cintesi"] = mainda["cinteti"];
mainda["cintesu,m"] = mainda["cinteti"];
mainda["acintayu,m"] = mainda["cinteti"];
mainda["cintesi"] = mainda["cinteti"];
mainda["cintittha"] = mainda["cinteti"];
mainda["cintesi,m"] = mainda["cinteti"];
mainda["cintimha"] = mainda["cinteti"];
mainda["adaa"] = mainda["dadaati"];
mainda["ado"] = mainda["dadaati"];
mainda["adattha"] = mainda["dadaati"];
mainda["dattha"] = mainda["dadaati"];
mainda["adamha"] = mainda["dadaati"];

mainda["adada,m"] = mainda["dadaati"];
// removed: dadaati = dadaati
mainda["dadanti"] = mainda["dadaati"];
mainda["dadaasi"] = mainda["dadaati"];
mainda["dadaatha"] = mainda["dadaati"];
mainda["dadaami"] = mainda["dadaati"];
mainda["dadaama"] = mainda["dadaati"];
mainda["deti"] = mainda["dadaati"];
mainda["denti"] = mainda["dadaati"];
mainda["desi"] = mainda["dadaati"];
mainda["detha"] = mainda["dadaati"];
mainda["demi"] = mainda["dadaati"];
mainda["dammi"] = mainda["dadaati"];
mainda["dema"] = mainda["dadaati"];
mainda["detu"] = mainda["dadaati"];
mainda["dentu"] = mainda["dadaati"];
mainda["dehi"] = mainda["dadaati"];
mainda["dadaahi"] = mainda["dadaati"];
mainda["detha"] = mainda["dadaati"];
mainda["demi"] = mainda["dadaati"];
mainda["dema"] = mainda["dadaati"];
mainda["dadeyya"] = mainda["dadaati"];
mainda["dade"] = mainda["dadaati"];
mainda["dajjaa"] = mainda["dadaati"];
mainda["dajjeyya"] = mainda["dadaati"];
mainda["dadeyyaasi"] = mainda["dadaati"];
mainda["dajjeyyaatha"] = mainda["dadaati"];
mainda["dadeyya,m"] = mainda["dadaati"];
mainda["dajja,m"] = mainda["dadaati"];
// removed: dakkhati = dakkhati
mainda["dakkhiti"] = mainda["dakkhati"];
mainda["dakkhanti"] = mainda["dakkhati"];
mainda["dakkhinti"] = mainda["dakkhati"];
mainda["dakkhasi"] = mainda["dakkhati"];
mainda["dakkhatha"] = mainda["dakkhati"];
mainda["dakkhaami"] = mainda["dakkhati"];
mainda["dakkhaama"] = mainda["dakkhati"];

mainda["dakkha"] = mainda["dakkhati"];
// removed: essati = essati
mainda["issati"] = mainda["essati"];
mainda["ehiti"] = mainda["essati"];
mainda["essanti"] = mainda["essati"];
mainda["issanti"] = mainda["essati"];
mainda["ehinti"] = mainda["essati"];
mainda["essasi"] = mainda["essati"];
mainda["ehisi"] = mainda["essati"];
mainda["essaami"] = mainda["essati"];
mainda["essa,m"] = mainda["essati"];
// removed: eti = eti
mainda["ayati"] = mainda["eti"];
mainda["itiz2"] = mainda["eti"];
mainda["enti"] = mainda["eti"];
mainda["esi"] = mainda["eti"];
mainda["etha"] = mainda["eti"];
mainda["emi"] = mainda["eti"];
mainda["ayaama"] = mainda["eti"];
mainda["etu"] = mainda["eti"];
mainda["ehi"] = mainda["eti"];
mainda["aya"] = mainda["eti"];
mainda["etha"] = mainda["eti"];
mainda["eyya"] = mainda["eti"];
mainda["eyyaasi"] = mainda["eti"];
mainda["agamaasi"] = mainda["gacchi"];
// removed: gacchi = gacchi
mainda["agacchi"] = mainda["gacchi"];
mainda["aga~nchi"] = mainda["gacchi"];
mainda["agamaa"] = mainda["gacchi"];
mainda["gami"] = mainda["gacchi"];
mainda["agaa"] = mainda["gacchi"];
mainda["gacchi,msu"] = mainda["gacchi"];
mainda["agamu,m"] = mainda["gacchi"];
mainda["agama,msu"] = mainda["gacchi"];
mainda["agami,msu"] = mainda["gacchi"];
mainda["aguu"] = mainda["gacchi"];
mainda["agamaa"] = mainda["gacchi"];
mainda["agacchittha"] = mainda["gacchi"];
mainda["agamittha"] = mainda["gacchi"];
mainda["gacchi,m"] = mainda["gacchi"];
mainda["agacchi,m"] = mainda["gacchi"];
mainda["aga~nchi,m"] = mainda["gacchi"];
mainda["agamaasi,m"] = mainda["gacchi"];
mainda["agami,mhase"] = mainda["gacchi"];
mainda["agamamhaa"] = mainda["gacchi"];
mainda["hanti"] = mainda["hanati"];
// removed: hanati = hanati
mainda["hanaati"] = mainda["hanati"];
mainda["hananti"] = mainda["hanati"];
mainda["hanaasi"] = mainda["hanati"];
mainda["hanatha"] = mainda["hanati"];
mainda["hanaami"] = mainda["hanati"];
mainda["hanaama"] = mainda["hanati"];

mainda["hanantu"] = mainda["hanati"];
mainda["hana"] = mainda["hanati"];
mainda["haneyya"] = mainda["hanati"];
mainda["hane"] = mainda["hanati"];
mainda["haneyyu,m"] = mainda["hanati"];
mainda["haneyya,m"] = mainda["hanati"];
mainda["hanata,m"] = mainda["hanati"];
mainda["hanassu"] = mainda["hanati"];
mainda["hessati"] = mainda["hoti"];
mainda["hehiti"] = mainda["hoti"];
mainda["hohiti"] = mainda["hoti"];
mainda["hessanti"] = mainda["hoti"];
mainda["hohisi"] = mainda["hoti"];
mainda["hessasi"] = mainda["hoti"];
mainda["hehisi"] = mainda["hoti"];
mainda["hessatha"] = mainda["hoti"];
mainda["hessaami"] = mainda["hoti"];
mainda["hessa,m"] = mainda["hoti"];
mainda["hessaama"] = mainda["hoti"];
// removed: hoti = hoti
mainda["honti"] = mainda["hoti"];
mainda["hosi"] = mainda["hoti"];
mainda["hotha"] = mainda["hoti"];
mainda["homi"] = mainda["hoti"];
mainda["homa"] = mainda["hoti"];
mainda["hotu"] = mainda["hoti"];
mainda["hontu"] = mainda["hoti"];
mainda["hohi"] = mainda["hoti"];
mainda["hotha"] = mainda["hoti"];
mainda["homi"] = mainda["hoti"];
mainda["homa"] = mainda["hoti"];
mainda["hupeyya"] = mainda["hoti"];
mainda["jaaneyya"] = mainda["jaanaati"];
mainda["ja~n~naa"] = mainda["jaanaati"];
mainda["jaaneyyu,m"] = mainda["jaanaati"];
mainda["jaaneyyaasi"] = mainda["jaanaati"];
mainda["jaaneyyaatha"] = mainda["jaanaati"];
mainda["jaaneyya,m"] = mainda["jaanaati"];
mainda["jaaneyyaami"] = mainda["jaanaati"];
mainda["jaaneyyaama"] = mainda["jaanaati"];
mainda["jaaniyaama"] = mainda["jaanaati"];
mainda["jaanemu"] = mainda["jaanaati"];
// removed: jaanaati = jaanaati
mainda["jaananti"] = mainda["jaanaati"];
mainda["jaanaasi"] = mainda["jaanaati"];
mainda["jaanaatha"] = mainda["jaanaati"];
mainda["jaanaami"] = mainda["jaanaati"];
mainda["jaanaama"] = mainda["jaanaati"];
mainda["jaanaatu"] = mainda["jaanaati"];
mainda["jaanantu"] = mainda["jaanaati"];
mainda["jaanaahi"] = mainda["jaanaati"];
mainda["jaanaatha"] = mainda["jaanaati"];
mainda["jaanaami"] = mainda["jaanaati"];
mainda["jaanaama"] = mainda["jaanaati"];
// removed: jayati = jayati
mainda["jayanti"] = mainda["jayati"];
mainda["jayasi"] = mainda["jayati"];
mainda["jayatha"] = mainda["jayati"];
mainda["jayaami"] = mainda["jayati"];
mainda["jayaama"] = mainda["jayati"];
mainda["jeti"] = mainda["jayati"];
mainda["jenti"] = mainda["jayati"];
mainda["jesi"] = mainda["jayati"];
mainda["jetha"] = mainda["jayati"];
mainda["jemi"] = mainda["jayati"];
mainda["jema"] = mainda["jayati"];
mainda["jinaati"] = mainda["jayati"];
mainda["jinanti"] = mainda["jayati"];
mainda["jinaasi"] = mainda["jayati"];
mainda["jinaatha"] = mainda["jayati"];
mainda["jinaami"] = mainda["jayati"];
mainda["jinaama"] = mainda["jayati"];
mainda["jeyya"] = mainda["jayati"];
mainda["jine"] = mainda["jayati"];
mainda["jineyyu,m"] = mainda["jayati"];

mainda["akaa"] = mainda["karoti"];
mainda["aka,msu"] = mainda["karoti"];
mainda["akaa"] = mainda["karoti"];
mainda["akattha"] = mainda["karoti"];
mainda["aka,m"] = mainda["karoti"];
mainda["akamha"] = mainda["karoti"];
mainda["akara,m"] = mainda["karoti"];
mainda["akaraa"] = mainda["karoti"];
mainda["akari"] = mainda["karoti"];
mainda["akarii"] = mainda["karoti"];
mainda["akarittha"] = mainda["karoti"];
mainda["akaru,m"] = mainda["karoti"];
mainda["akari,msu"] = mainda["karoti"];
mainda["akara"] = mainda["karoti"];
mainda["akaraa"] = mainda["karoti"];
mainda["akari"] = mainda["karoti"];
mainda["akarii"] = mainda["karoti"];
mainda["akarittha"] = mainda["karoti"];
mainda["akara,m"] = mainda["karoti"];
mainda["akari,m"] = mainda["karoti"];
mainda["akaraama"] = mainda["karoti"];
mainda["akaramha"] = mainda["karoti"];
mainda["akarimha"] = mainda["karoti"];
mainda["akaasi"] = mainda["karoti"];
mainda["akaasi,m"] = mainda["karoti"];
mainda["kaahaasi,m"] = mainda["karoti"];
mainda["akaasimha"] = mainda["karoti"];
mainda["kaaraapesi"] = mainda["karoti"];
mainda["kaaraapesu,m"] = mainda["karoti"];
mainda["kaaraapayi,msu"] = mainda["karoti"];
mainda["kaaraapesi,m"] = mainda["karoti"];
mainda["kaarapesi,m"] = mainda["karoti"];
mainda["kaarapesi"] = mainda["karoti"];
mainda["kaaraapayi,m"] = mainda["karoti"];
mainda["kaaraapeti"] = mainda["karoti"];
mainda["kaaraapayati"] = mainda["karoti"];
mainda["kaaraapenti"] = mainda["karoti"];
mainda["kaaraapetha"] = mainda["karoti"];
mainda["kaaraapiyati"] = mainda["karoti"];
mainda["kariyati"] = mainda["karoti"];
mainda["kariiyati"] = mainda["karoti"];
mainda["kariiyate"] = mainda["karoti"];
mainda["kariyyati"] = mainda["karoti"];
mainda["kariyyate"] = mainda["karoti"];
mainda["kayirati"] = mainda["karoti"];
mainda["kiirati"] = mainda["karoti"];
mainda["kayyati"] = mainda["karoti"];
mainda["kayyate"] = mainda["karoti"];
mainda["kariiyanti"] = mainda["karoti"];
mainda["kayiranti"] = mainda["karoti"];
mainda["kiiranti"] = mainda["karoti"];
mainda["kariyanti"] = mainda["karoti"];
mainda["kariiyi"] = mainda["karoti"];
mainda["akaaresi"] = mainda["karoti"];
mainda["kaaresi"] = mainda["karoti"];
mainda["akaarayi"] = mainda["karoti"];
mainda["kaarayi"] = mainda["karoti"];
mainda["kaaresu,m"] = mainda["karoti"];
mainda["kaarayi,msu"] = mainda["karoti"];
mainda["akaarayu,m"] = mainda["karoti"];
mainda["kaarayu,m"] = mainda["karoti"];
mainda["kaaresi"] = mainda["karoti"];
mainda["kaarayesi"] = mainda["karoti"];
mainda["kaaresi,m"] = mainda["karoti"];
mainda["akaarayi,m"] = mainda["karoti"];
mainda["kaarayi,m"] = mainda["karoti"];
mainda["kaarayesi,m"] = mainda["karoti"];
mainda["akaarayi"] = mainda["karoti"];
mainda["kaarayi"] = mainda["karoti"];
mainda["kaareti"] = mainda["karoti"];
mainda["kaarayati"] = mainda["karoti"];
mainda["kaarayate"] = mainda["karoti"];
mainda["kaarenti"] = mainda["karoti"];
mainda["kaaretha"] = mainda["karoti"];
mainda["kaaremi"] = mainda["karoti"];
mainda["kaarayaami"] = mainda["karoti"];
mainda["karii"] = mainda["karoti"];
mainda["kari,msu"] = mainda["karoti"];
mainda["karu,m"] = mainda["karoti"];
mainda["karii"] = mainda["karoti"];
mainda["kari"] = mainda["karoti"];
mainda["karittha"] = mainda["karoti"];
mainda["kari,m"] = mainda["karoti"];
mainda["karimha"] = mainda["karoti"];
mainda["karimhaa"] = mainda["karoti"];
mainda["karissati"] = mainda["karoti"];
mainda["kaahati"] = mainda["karoti"];
mainda["kaahiti"] = mainda["karoti"];
mainda["kaasati"] = mainda["karoti"];
mainda["karissanti"] = mainda["karoti"];
mainda["kaahanti"] = mainda["karoti"];
mainda["kaahinti"] = mainda["karoti"];
mainda["karissare"] = mainda["karoti"];
mainda["karissasi"] = mainda["karoti"];
mainda["kaahasi"] = mainda["karoti"];
mainda["kaahisi"] = mainda["karoti"];
mainda["karissatha"] = mainda["karoti"];
mainda["kaahatha"] = mainda["karoti"];
mainda["karissaami"] = mainda["karoti"];
mainda["kaahaami"] = mainda["karoti"];
mainda["karissa,m"] = mainda["karoti"];
mainda["kassaami"] = mainda["karoti"];
mainda["kassa,m"] = mainda["karoti"];
mainda["kaasa,m"] = mainda["karoti"];
mainda["karissaama"] = mainda["karoti"];
mainda["kaahaama"] = mainda["karoti"];
mainda["kassaama"] = mainda["karoti"];
// removed: karoti = karoti
mainda["kayirati"] = mainda["karoti"];
mainda["karonti"] = mainda["karoti"];
mainda["karosi"] = mainda["karoti"];
mainda["karotha"] = mainda["karoti"];
mainda["karomi"] = mainda["karoti"];
mainda["kummi"] = mainda["karoti"];
mainda["karoma"] = mainda["karoti"];
mainda["kareyya"] = mainda["karoti"];
mainda["kare"] = mainda["karoti"];
mainda["kariyaa"] = mainda["karoti"];
mainda["kuriyaa"] = mainda["karoti"];
mainda["kuyiraa"] = mainda["karoti"];
mainda["kayiraatha"] = mainda["karoti"];
mainda["kayiraa"] = mainda["karoti"];
mainda["kayira"] = mainda["karoti"];
mainda["kareyyu,m"] = mainda["karoti"];
mainda["kayiru,m"] = mainda["karoti"];
mainda["kareyyaasi"] = mainda["karoti"];
mainda["kare"] = mainda["karoti"];
mainda["kayiraasi"] = mainda["karoti"];
mainda["kayiraa"] = mainda["karoti"];
mainda["kareyyaatha"] = mainda["karoti"];
mainda["kayiraatha"] = mainda["karoti"];
mainda["kareyya,m"] = mainda["karoti"];
mainda["katvaa"] = mainda["karoti"];
mainda["kareyyaami"] = mainda["karoti"];
mainda["kareyyaama"] = mainda["karoti"];
mainda["kubbati"] = mainda["karoti"];
mainda["kurute"] = mainda["karoti"];
mainda["kubbanti"] = mainda["karoti"];
mainda["karotu"] = mainda["karoti"];
mainda["kurutu"] = mainda["karoti"];
mainda["karontu"] = mainda["karoti"];
mainda["karohi"] = mainda["karoti"];
mainda["kuru"] = mainda["karoti"];
mainda["karotha"] = mainda["karoti"];
mainda["karomi"] = mainda["karoti"];
mainda["karoma"] = mainda["karoti"];
mainda["kariyatu"] = mainda["karoti"];
mainda["kayiratu"] = mainda["karoti"];
mainda["kuruta,m"] = mainda["karoti"];
mainda["karassu"] = mainda["karoti"];
mainda["kuruvho"] = mainda["karoti"];
mainda["karomase"] = mainda["karoti"];
mainda["kubbetha"] = mainda["karoti"];
mainda["kubbaye"] = mainda["karoti"];
mainda["kaaretu"] = mainda["karoti"];
mainda["kaarehi"] = mainda["karoti"];
mainda["kaaraapehi"] = mainda["karoti"];
mainda["kaareya"] = mainda["karoti"];
mainda["kaareyya"] = mainda["karoti"];
mainda["kaarayeyya"] = mainda["karoti"];
mainda["kaaraapeyya"] = mainda["karoti"];
mainda["kaareyyu,m"] = mainda["karoti"];
mainda["kaaraapeyyaasi"] = mainda["karoti"];
mainda["kaaraapeyyaatha"] = mainda["karoti"];
mainda["kaareya"] = mainda["karoti"];
mainda["kaaraapeyya,m"] = mainda["karoti"];
mainda["kaareyyaama"] = mainda["karoti"];
// removed: labhati = labhati
mainda["labhanti"] = mainda["labhati"];
mainda["labhasi"] = mainda["labhati"];
mainda["labhatha"] = mainda["labhati"];
mainda["labhaami"] = mainda["labhati"];
mainda["labhaama"] = mainda["labhati"];
mainda["labhatu"] = mainda["labhati"];
mainda["labhantu"] = mainda["labhati"];
mainda["labha"] = mainda["labhati"];
mainda["labhatha"] = mainda["labhati"];
mainda["labhaami"] = mainda["labhati"];
mainda["labhaama"] = mainda["labhati"];
mainda["labheyya"] = mainda["labhati"];
mainda["labhe"] = mainda["labhati"];
mainda["labheyyu,m"] = mainda["labhati"];
mainda["labheyyaasi"] = mainda["labhati"];
mainda["labheyyaatha"] = mainda["labhati"];
mainda["labheyya,m"] = mainda["labhati"];
mainda["labheyyaama"] = mainda["labhati"];
mainda["labhate"] = mainda["labhati"];
mainda["labhare"] = mainda["labhati"];
mainda["labhase"] = mainda["labhati"];
mainda["labhe"] = mainda["labhati"];
mainda["labhata,m"] = mainda["labhati"];
mainda["labhassu"] = mainda["labhati"];
mainda["labhaamase"] = mainda["labhati"];
mainda["labhaamhase"] = mainda["labhati"];
mainda["labhetha"] = mainda["labhati"];
mainda["labhetho"] = mainda["labhati"];
mainda["alattha"] = mainda["labhati"];
mainda["labhi"] = mainda["labhati"];
mainda["alabhi"] = mainda["labhi"];
mainda["alabbhittha"] = mainda["labhi"];
mainda["alatthu,m"] = mainda["labhi"];
mainda["alabhi,msu"] = mainda["labhi"];
mainda["labhi,msu"] = mainda["labhi"];
mainda["alattha,msu"] = mainda["labhi"];
mainda["labhittha"] = mainda["labhi"];
mainda["alattha,m"] = mainda["labhi"];
mainda["alabhi,m"] = mainda["labhi"];
mainda["labhi,m"] = mainda["labhi"];
mainda["alabhittha,m"] = mainda["labhi"];
mainda["labhimhaa"] = mainda["labhi"];
mainda["alatthamha"] = mainda["labhi"];
// removed: paccanubhoti = paccanubhoti
mainda["paccanubhonti"] = mainda["paccanubhoti"];
mainda["paccanubhosi"] = mainda["paccanubhoti"];
mainda["paccanubhotha"] = mainda["paccanubhoti"];
mainda["paccanubhomi"] = mainda["paccanubhoti"];
mainda["paccanubhoma"] = mainda["paccanubhoti"];
// removed: paccu,t,thaati = paccu,t,thaati
mainda["paccu,t,thanti"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaasi"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaatha"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaami"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaama"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaatu"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thantu"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaahi"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaatha"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaami"] = mainda["paccu,t,thaati"];
mainda["paccu,t,thaama"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyya"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyyu,m"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyyaasi"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyyaatha"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyya,m"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyyaami"] = mainda["paccu,t,thaati"];
mainda["paccu,t,theyyaama"] = mainda["paccu,t,thaati"];
// removed: paccupa,t,thaati = paccupa,t,thaati
mainda["paccupa,t,thaasi"] = mainda["paccupa,t,thaati"];
// removed: pahoti = pahoti
mainda["pahonti"] = mainda["pahoti"];
mainda["pahosi"] = mainda["pahoti"];
mainda["pahotha"] = mainda["pahoti"];
mainda["pahomi"] = mainda["pahoti"];
mainda["pahoma"] = mainda["pahoti"];
mainda["pakkaami"] = mainda["pakkamati"];
mainda["pakkamu,m"] = mainda["pakkamati"];
mainda["pakkami,msu"] = mainda["pakkamati"];
// removed: pa,tikaroti = pa,tikaroti
mainda["pa,tikaronti"] = mainda["pa,tikaroti"];
mainda["pa,tikarosi"] = mainda["pa,tikaroti"];
mainda["pa,tikarotha"] = mainda["pa,tikaroti"];
mainda["pa,tikaromi"] = mainda["pa,tikaroti"];
mainda["pa,tikaroma"] = mainda["pa,tikaroti"];
mainda["pa,tikarotu"] = mainda["pa,tikaroti"];
mainda["pa,tikarontu"] = mainda["pa,tikaroti"];
mainda["pa,tikarohi"] = mainda["pa,tikaroti"];
mainda["pa,tikarotha"] = mainda["pa,tikaroti"];
mainda["pa,tikaromi"] = mainda["pa,tikaroti"];
mainda["pa,tikaroma"] = mainda["pa,tikaroti"];
mainda["pa,tikareyya"] = mainda["pa,tikaroti"];
mainda["pa,tikareyyu,m"] = mainda["pa,tikaroti"];
mainda["pa,tikareyyaasi"] = mainda["pa,tikaroti"];
mainda["pa,tikareyyaatha"] = mainda["pa,tikaroti"];
mainda["pa,tikareyya,m"] = mainda["pa,tikaroti"];
mainda["pa,tikareyyaama"] = mainda["pa,tikaroti"];
mainda["paccassosi"] = mainda["pa,tissu,naati"];
mainda["paccassosu,m"] = mainda["pa,tissu,naati"];
mainda["paccassosi"] = mainda["pa,tissu,naati"];
mainda["paccassuttha"] = mainda["pa,tissu,naati"];
mainda["paccassosi,m"] = mainda["pa,tissu,naati"];
mainda["paccassumha"] = mainda["pa,tissu,naati"];
// removed: pappoti = pappoti
mainda["papponti"] = mainda["pappoti"];
mainda["papposi"] = mainda["pappoti"];
mainda["pappotha"] = mainda["pappoti"];
mainda["pappomi"] = mainda["pappoti"];
mainda["pappoma"] = mainda["pappoti"];
mainda["pappotu"] = mainda["pappoti"];
mainda["pappontu"] = mainda["pappoti"];
mainda["pappohi"] = mainda["pappoti"];
mainda["pappotha"] = mainda["pappoti"];
mainda["pappomi"] = mainda["pappoti"];
mainda["pappoma"] = mainda["pappoti"];

mainda["pappomu"] = mainda["pappoti"];
// removed: paapu,naati = paapu,naati
mainda["paapu,nanti"] = mainda["paapu,naati"];
mainda["paapu,naasi"] = mainda["paapu,naati"];
mainda["paapu,naatha"] = mainda["paapu,naati"];
mainda["paapu,naami"] = mainda["paapu,naati"];
mainda["paapu,naama"] = mainda["paapu,naati"];
mainda["paapu,neyya"] = mainda["paapu,naati"];
mainda["paapu,ne"] = mainda["paapu,naati"];
mainda["paapu,neyyaama"] = mainda["paapu,naati"];

// removed: pati,t,thahati = pati,t,thahati
mainda["pati,t,thahanti"] = mainda["pati,t,thahati"];
mainda["pati,t,thahasi"] = mainda["pati,t,thahati"];
mainda["pati,t,thahatha"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaami"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaama"] = mainda["pati,t,thahati"];
mainda["pati,t,thaati"] = mainda["pati,t,thahati"];
mainda["pati,t,thanti"] = mainda["pati,t,thahati"];
mainda["pati,t,thaasi"] = mainda["pati,t,thahati"];
mainda["pati,t,thaatha"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaami"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaama"] = mainda["pati,t,thahati"];
mainda["pati,t,thaatu"] = mainda["pati,t,thahati"];
mainda["pati,t,thantu"] = mainda["pati,t,thahati"];
mainda["pati,t,thaahi"] = mainda["pati,t,thahati"];
mainda["pati,t,thaatha"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaami"] = mainda["pati,t,thahati"];
mainda["pati,t,thahaama"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyya"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyyu,m"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyyaasi"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyyaatha"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyya,m"] = mainda["pati,t,thahati"];
mainda["pati,t,thaheyyaami"] = mainda["pati,t,thahati"];
mainda["paaturahosi"] = mainda["paatubhavati"];
mainda["paaturaha,msu"] = mainda["paatubhavati"];
mainda["paaturahi,msu"] = mainda["paatubhavati"];
mainda["paaturahosi"] = mainda["paatubhavati"];
mainda["paaturahuvattha"] = mainda["paatubhavati"];
mainda["paaturahosi,m"] = mainda["paatubhavati"];
mainda["paaturahumha"] = mainda["paatubhavati"];

// removed: sakkoti = sakkoti
mainda["sakkonti"] = mainda["sakkoti"];
mainda["sakkosi"] = mainda["sakkoti"];
mainda["sakkotha"] = mainda["sakkoti"];
mainda["sakkomi"] = mainda["sakkoti"];
mainda["sakkoma"] = mainda["sakkoti"];
mainda["sakku,neyya"] = mainda["sakkoti"];
mainda["sakku,neyyu,m"] = mainda["sakkoti"];
mainda["sakku,neyyaasi"] = mainda["sakkoti"];
mainda["sakku,neyyaatha"] = mainda["sakkoti"];
mainda["sakku,neyya,m"] = mainda["sakkoti"];
mainda["sakku,neyyaama"] = mainda["sakkoti"];
mainda["sakku,nemu"] = mainda["sakkoti"];

// removed: sambhoti = sambhoti
mainda["sambhonti"] = mainda["sambhoti"];
// removed: samudeti = samudeti
mainda["samudayati"] = mainda["samudeti"];
// removed: santi,t,thati = santi,t,thati
mainda["santi,t,thanti"] = mainda["santi,t,thati"];
mainda["santi,t,thasi"] = mainda["santi,t,thati"];
mainda["santi,t,thatha"] = mainda["santi,t,thati"];
mainda["santi,t,thaami"] = mainda["santi,t,thati"];
mainda["santi,t,thaama"] = mainda["santi,t,thati"];
mainda["sa,n,thaati"] = mainda["santi,t,thati"];
mainda["sa,n,thahati"] = mainda["santi,t,thati"];
mainda["sa,n,thanti"] = mainda["santi,t,thati"];
mainda["sa,n,thahanti"] = mainda["santi,t,thati"];
mainda["sa,n,thaasi"] = mainda["santi,t,thati"];
mainda["sa,n,thahasi"] = mainda["santi,t,thati"];
mainda["sa,n,thaatha"] = mainda["santi,t,thati"];
mainda["sa,n,thahatha"] = mainda["santi,t,thati"];
mainda["sa,n,thaami"] = mainda["santi,t,thati"];
mainda["sa,n,thahaami"] = mainda["santi,t,thati"];
mainda["sa,n,thaama"] = mainda["santi,t,thati"];
mainda["sa,n,thahaama"] = mainda["santi,t,thati"];
mainda["sa,n,thaheyya"] = mainda["santi,t,thati"];
mainda["sayati"] = mainda["seti"];
mainda["sayanti"] = mainda["seti"];
mainda["sayasi"] = mainda["seti"];
mainda["sayatha"] = mainda["seti"];
mainda["sayaami"] = mainda["seti"];
mainda["sayaama"] = mainda["seti"];
// removed: seti = seti
mainda["senti"] = mainda["seti"];
mainda["sesi"] = mainda["seti"];
mainda["setha"] = mainda["seti"];
mainda["semi"] = mainda["seti"];
mainda["sema"] = mainda["seti"];
mainda["sayatu"] = mainda["seti"];
mainda["sayeyya"] = mainda["seti"];
mainda["saye"] = mainda["seti"];
mainda["sayeyyaatha"] = mainda["seti"];
// removed: su,naati = su,naati

mainda["su,noti"] = mainda["su,naati"];
mainda["su,nanti"] = mainda["su,naati"];
mainda["su,naasi"] = mainda["su,naati"];
mainda["su,nosi"] = mainda["su,naati"];
mainda["su,naatha"] = mainda["su,naati"];
mainda["su,notha"] = mainda["su,naati"];
mainda["su,naami"] = mainda["su,naati"];
mainda["su,nomi"] = mainda["su,naati"];
mainda["su,noma"] = mainda["su,naati"];
mainda["su,naama"] = mainda["su,naati"];
mainda["su,naatu"] = mainda["su,naati"];
mainda["su,nohi"] = mainda["su,naati"];
mainda["su,naahi"] = mainda["su,naati"];
mainda["su,neyya"] = mainda["su,naati"];
mainda["su,neyyu,m"] = mainda["su,naati"];
mainda["su,neyyaatha"] = mainda["su,naati"];
mainda["su,neyya,m"] = mainda["su,naati"];
mainda["su,neyyaama"] = mainda["su,naati"];

mainda["sossati"] = mainda["su,naati"];

mainda["sussa,m"] = mainda["su,naati"];

mainda["sossi"] = mainda["su,naati"];
mainda["assosi"] = mainda["su,naati"];
mainda["assosu,m"] = mainda["su,naati"];
mainda["assu,m"] = mainda["su,naati"];
mainda["assu"] = mainda["su,naati"];
mainda["su,ni"] = mainda["su,naati"];
mainda["assumha"] = mainda["su,naati"];
mainda["assuttha"] = mainda["su,naati"];
mainda["suyati "] = mainda["su,naati"];
mainda["suyyati"] = mainda["su,naati"];

// removed: ti,t,thati = ti,t,thati
mainda["ti,t,thanti"] = mainda["ti,t,thati"];
mainda["ti,t,thasi"] = mainda["ti,t,thati"];
mainda["ti,t,thatha"] = mainda["ti,t,thati"];
mainda["ti,t,thaami"] = mainda["ti,t,thati"];
mainda["ti,t,thaama"] = mainda["ti,t,thati"];
mainda["ti,t,thatu"] = mainda["ti,t,thati"];
mainda["ti,t,thantu"] = mainda["ti,t,thati"];
mainda["ti,t,tha"] = mainda["ti,t,thati"];
mainda["ti,t,thatha"] = mainda["ti,t,thati"];
mainda["ti,t,thaami"] = mainda["ti,t,thati"];
mainda["ti,t,thaama"] = mainda["ti,t,thati"];
mainda["ti,t,the"] = mainda["ti,t,thati"];
mainda["ti,t,theyya"] = mainda["ti,t,thati"];
mainda["ti,t,theyyu,m"] = mainda["ti,t,thati"];
mainda["ti,t,theyyaasi"] = mainda["ti,t,thati"];
mainda["ti,t,theyyaatha"] = mainda["ti,t,thati"];
mainda["ti,t,theyya,m"] = mainda["ti,t,thati"];
mainda["ti,t,theyyaami"] = mainda["ti,t,thati"];
mainda["ti,t,theyyaama"] = mainda["ti,t,thati"];
// removed: udayati = udayati
mainda["udayanti"] = mainda["udayati"];
// removed: udeti = udeti
mainda["udenti"] = mainda["udeti"];
// removed: upaccagaa = upaccagaa
mainda["upaccagu,m"] = mainda["upaccagaa"];
mainda["upaccagu"] = mainda["upaccagaa"];
mainda["upaccaguu"] = mainda["upaccagaa"];
mainda["upaccaga,m"] = mainda["upaccagaa"];
mainda["upaagamaasi"] = mainda["upaagaami"];
// removed: upaagaami = upaagaami
mainda["upaagacchi"] = mainda["upaagaami"];
mainda["upaaga~nchi"] = mainda["upaagaami"];
mainda["upagacchi"] = mainda["upaagaami"];
mainda["upaga~nchi"] = mainda["upaagaami"];
mainda["upaagamu,m"] = mainda["upaagaami"];
mainda["upaagami,msu"] = mainda["upaagaami"];
mainda["upagami,msu"] = mainda["upaagaami"];
mainda["upaaga~nchu,m"] = mainda["upaagaami"];
mainda["upagacchu,m"] = mainda["upaagaami"];
mainda["upaga~nchu,m"] = mainda["upaagaami"];
mainda["upagacchi,msu"] = mainda["upaagaami"];
mainda["upagacchu"] = mainda["upaagaami"];
mainda["upaga~nchu"] = mainda["upaagaami"];
mainda["upaagama,m"] = mainda["upaagaami"];
mainda["upagama,m"] = mainda["upaagaami"];
mainda["upaagami,m"] = mainda["upaagaami"];
mainda["upagami,m"] = mainda["upaagaami"];
mainda["upaagacchi,m"] = mainda["upaagaami"];
mainda["upaaga~nchi,m"] = mainda["upaagaami"];
mainda["upagacchi,m"] = mainda["upaagaami"];
mainda["upaga~nchi,m"] = mainda["upaagaami"];
mainda["upagacchittha"] = mainda["upaagaami"];
// removed: upa,t,thahati = upa,t,thahati
mainda["upa,t,thaheti"] = mainda["upa,t,thahati"];
mainda["upa,t,thahanti"] = mainda["upa,t,thahati"];
mainda["upa,t,thahatha"] = mainda["upa,t,thahati"];
mainda["upa,t,thahaami"] = mainda["upa,t,thahati"];
mainda["upa,t,thahema"] = mainda["upa,t,thahati"];
mainda["upa,t,thahatu"] = mainda["upa,t,thahati"];
mainda["upa,t,thaha"] = mainda["upa,t,thahati"];
mainda["upa,t,thaheyya"] = mainda["upa,t,thahati"];

mainda["upa,t,thahassu"] = mainda["upa,t,thahati"];
// removed: upa,t,thaati = upa,t,thaati
mainda["upa,t,theti"] = mainda["upa,t,thaati"];
mainda["upa,t,thanti"] = mainda["upa,t,thaati"];
mainda["upa,t,thenti"] = mainda["upa,t,thaati"];
mainda["upa,t,thesi"] = mainda["upa,t,thaati"];
mainda["upa,t,thaatu"] = mainda["upa,t,thaati"];
mainda["upa,t,thaahi"] = mainda["upa,t,thaati"];
mainda["upa,t,theyya"] = mainda["upa,t,thaati"];

// removed: upati,t,thati = upati,t,thati
mainda["upati,t,thanti"] = mainda["upati,t,thati"];
mainda["upati,t,thatha"] = mainda["upati,t,thati"];
mainda["upati,t,thaama"] = mainda["upati,t,thati"];
mainda["upati,t,thatu"] = mainda["upati,t,thati"];
mainda["upati,t,theyya"] = mainda["upati,t,thati"];
mainda["upati,t,theyyu,m"] = mainda["upati,t,thati"];
mainda["upati,t,theyya,m"] = mainda["upati,t,thati"];
// removed: vadati = vadati
/*mainda["vadanti"] = mainda["vadati"];
mainda["vadasi"] = mainda["vadati"];
mainda["vadatha"] = mainda["vadati"];
mainda["vadaami"] = mainda["vadati"];
mainda["vadaama"] = mainda["vadati"];*/

mainda["vadehi"] = mainda["vadati"];

mainda["vademase"] = mainda["vadati"];
mainda["vadeyya"] = mainda["vajjaa"];
// removed: vajjaa = vajjaa
mainda["vadeyyu,m"] = mainda["vajjaa"];
mainda["vajju,m"] = mainda["vajjaa"];
mainda["vadeyyaasi"] = mainda["vajjaa"];
mainda["vajjesi"] = mainda["vajjaa"];
mainda["vajjaasi"] = mainda["vajjaa"];
mainda["vadeyyaatha"] = mainda["vajjaa"];
mainda["vade"] = mainda["vajjaa"];
mainda["vadeyya,m"] = mainda["vajjaa"];
mainda["vadeyyaami"] = mainda["vajjaa"];
mainda["vajja,m"] = mainda["vajjaa"];
mainda["vadeyyaama"] = mainda["vajjaa"];
// removed: vandati = vandati
//mainda["vandanti"] = mainda["vandati"];
//mainda["vandasi"] = mainda["vandati"];
//mainda["vandatha"] = mainda["vandati"];
//mainda["vandaami"] = mainda["vandati"];
//mainda["vandaama"] = mainda["vandati"];

//mainda["vandantu"] = mainda["vandati"];
mainda["vanda"] = mainda["vandati"];
mainda["vandaahi"] = mainda["vandati"];
mainda["vandeyya"] = mainda["vandati"];
mainda["vandeyyaasi"] = mainda["vandati"];
mainda["vandate"] = mainda["vandati"];
mainda["vandase"] = mainda["vandati"];
mainda["vande"] = mainda["vandati"];
mainda["viharaahi"] = mainda["viharati"];
mainda["vihaasi"] = mainda["viharati"];
mainda["vihi,msu"] = mainda["viharati"];
mainda["viha,msu"] = mainda["viharati"];
// removed: vijaanaati = vijaanaati
mainda["vijaananti"] = mainda["vijaanaati"];
mainda["vijaanaasi"] = mainda["vijaanaati"];
mainda["vijaanaatha"] = mainda["vijaanaati"];
mainda["vijaanaami"] = mainda["vijaanaati"];
mainda["vijaanaama"] = mainda["vijaanaati"];
mainda["vijaanaatu"] = mainda["vijaanaati"];
mainda["vijaanantu"] = mainda["vijaanaati"];
mainda["vijaana"] = mainda["vijaanaati"];
mainda["vijaanaahi"] = mainda["vijaanaati"];
mainda["vijaanaatha"] = mainda["vijaanaati"];
mainda["vijaanaami"] = mainda["vijaanaati"];
mainda["vijaanaama"] = mainda["vijaanaati"];
mainda["vijaaneyya"] = mainda["vijaanaati"];
mainda["vija~n~naa"] = mainda["vijaanaati"];
mainda["vijaaneyyu,m"] = mainda["vijaanaati"];
mainda["vijaaneyyaasi"] = mainda["vijaanaati"];
mainda["vijaaneyyaatha"] = mainda["vijaanaati"];
mainda["vijaaneyya,m"] = mainda["vijaanaati"];
mainda["vija~n~na,m"] = mainda["vijaanaati"];
mainda["vijaaniya,m"] = mainda["vijaanaati"];
mainda["vijaaneyyaama"] = mainda["vijaanaati"];
mainda["vijaanata,m"] = mainda["vijaanaati"];
// removed: vineti = vineti
mainda["vinenti"] = mainda["vineti"];
mainda["vinesi"] = mainda["vineti"];
mainda["vinetha"] = mainda["vineti"];
mainda["vinemi"] = mainda["vineti"];
mainda["vinema"] = mainda["vineti"];
mainda["vinetu"] = mainda["vineti"];
mainda["vinaya"] = mainda["vineti"];
mainda["vineyya"] = mainda["vineti"];
mainda["vineyyu,m"] = mainda["vineti"];
mainda["vineyyaasi"] = mainda["vineti"];
mainda["vineyyaatha"] = mainda["vineti"];
mainda["vineyya,m"] = mainda["vineti"];
mainda["vineyyaama"] = mainda["vineti"];

mainda["vinayassu"] = mainda["vineti"];
mainda["vinayetha"] = mainda["vineti"];
// removed: vu,t,thahati = vu,t,thahati
mainda["vu,t,thahanti"] = mainda["vu,t,thahati"];
mainda["vu,t,thahasi"] = mainda["vu,t,thahati"];
mainda["vu,t,thahatha"] = mainda["vu,t,thahati"];
mainda["vu,t,thahaami"] = mainda["vu,t,thahati"];
mainda["vu,t,thahaama"] = mainda["vu,t,thahati"];
mainda["vu,t,thaati"] = mainda["vu,t,thahati"];
mainda["vu,t,thanti"] = mainda["vu,t,thahati"];
mainda["vu,t,thaasi"] = mainda["vu,t,thahati"];
mainda["vu,t,thaatha"] = mainda["vu,t,thahati"];
mainda["vu,t,thaami"] = mainda["vu,t,thahati"];
mainda["vu,t,thaama"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissati"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissanti"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissasi"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissatha"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissaami"] = mainda["vu,t,thahati"];
mainda["vu,t,thahissaama"] = mainda["vu,t,thahati"];
mainda["vu,t,thaheyya"] = mainda["vu,t,thahati"];
mainda["byantiihoti"] = mainda["vyantiihoti"];
// removed: cinteti = cinteti
mainda["cintenti"] = mainda["cinteti"];
mainda["cintesi"] = mainda["cinteti"];
mainda["cintetha"] = mainda["cinteti"];
mainda["cintemi"] = mainda["cinteti"];
mainda["cintema"] = mainda["cinteti"];
mainda["huveyya"] = mainda["hoti"];

// irregular nouns

mainda["ida,m"] = mainda["ida"];

mainda["aya,m"] = mainda["ida,m"]
mainda["ima,m"] = mainda["ida,m"]
mainda["iminaa"] = mainda["ida,m"]
mainda["assa"] = mainda["ida,m"]
mainda["imasmaa"] = mainda["ida,m"]
mainda["imamhaa"] = mainda["ida,m"]
mainda["assa"] = mainda["ida,m"]
mainda["imassa"] = mainda["ida,m"]
mainda["asmi,m"] = mainda["ida,m"]
mainda["imasmi,m"] = mainda["ida,m"]
mainda["ime"] = mainda["ida,m"]
mainda["ime"] = mainda["ida,m"]
mainda["imehi"] = mainda["ida,m"]
mainda["imesa,m"] = mainda["ida,m"]
mainda["imehi"] = mainda["ida,m"]
mainda["imesa,m"] = mainda["ida,m"]
mainda["imesu"] = mainda["ida,m"]
mainda["ida,m"] = mainda["ida,m"]
mainda["ida,m"] = mainda["ida,m"]
mainda["iminaa"] = mainda["ida,m"]
mainda["assa"] = mainda["ida,m"]
mainda["imasmaa"] = mainda["ida,m"]
mainda["imamhaa"] = mainda["ida,m"]
mainda["assa"] = mainda["ida,m"]
mainda["imassa"] = mainda["ida,m"]
mainda["asmi,m"] = mainda["ida,m"]
mainda["imasmi,m"] = mainda["ida,m"]
mainda["imaani"] = mainda["ida,m"]
mainda["imaani"] = mainda["ida,m"]
mainda["imehi"] = mainda["ida,m"]
mainda["imesa,m"] = mainda["ida,m"]
mainda["imehi"] = mainda["ida,m"]
mainda["imesa,m"] = mainda["ida,m"]
mainda["imesu"] = mainda["ida,m"]
mainda["aya,m"] = mainda["ida,m"]
mainda["ima,m"] = mainda["ida,m"]
mainda["imaaya"] = mainda["ida,m"]
mainda["assaa"] = mainda["ida,m"]
mainda["imaaya"] = mainda["ida,m"]
mainda["assaa"] = mainda["ida,m"]
mainda["imassaa"] = mainda["ida,m"]
mainda["imaayam"] = mainda["ida,m"]
mainda["imaaya"] = mainda["ida,m"]
mainda["imaa"] = mainda["ida,m"]
mainda["imaa"] = mainda["ida,m"]
mainda["imaahi"] = mainda["ida,m"]
mainda["imaasa,m"] = mainda["ida,m"]
mainda["imaahi"] = mainda["ida,m"]
mainda["imaasa,m"] = mainda["ida,m"]
mainda["imaasu"] = mainda["ida,m"]

/*mainda["na,m"] = mainda["na"]
mainda["nena"] = mainda["na"]
mainda["nassa"] = mainda["na"]
mainda["nasmaa"] = mainda["na"]
mainda["namhaa"] = mainda["na"]
mainda["nassa"] = mainda["na"]
mainda["nasmi,m"] = mainda["na"]
mainda["namhi"] = mainda["na"]
mainda["ne"] = mainda["na"]
mainda["nehi"] = mainda["na"]
mainda["nesa,m"] = mainda["na"]
mainda["nehi"] = mainda["na"]
mainda["nesa,m"] = mainda["na"]
mainda["nesu"] = mainda["na"]
mainda["na,m"] = mainda["na"]
mainda["nena"] = mainda["na"]
mainda["nassa"] = mainda["na"]
mainda["nasmaa"] = mainda["na"]
mainda["namhaa"] = mainda["na"]
mainda["nassa"] = mainda["na"]
mainda["nasmi,m"] = mainda["na"]
mainda["namhi"] = mainda["na"]
mainda["naani"] = mainda["na"]
mainda["nehi"] = mainda["na"]
mainda["nesa,m"] = mainda["na"]
mainda["nehi"] = mainda["na"]
mainda["nesa,m"] = mainda["na"]
mainda["nesu"] = mainda["na"]
mainda["na,m"] = mainda["na"]
mainda["naaya"] = mainda["na"]
mainda["nassaa"] = mainda["na"]
mainda["naaya"] = mainda["na"]
mainda["nassaa"] = mainda["na"]
mainda["naaya"] = mainda["na"]
mainda["naaya,m"] = mainda["na"]
mainda["nassa,m"] = mainda["na"]
mainda["naa"] = mainda["na"]
mainda["naahi"] = mainda["na"]
mainda["naasa,m"] = mainda["na"]
mainda["naahi"] = mainda["na"]
mainda["naasa,m"] = mainda["na"]
mainda["naasu"] = mainda["na"]*/
mainda["aham"] = mainda["aha,m"]
mainda["ma,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mez2"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayi"] = mainda["aha,m"]
mainda["maya,m"] = mainda["aha,m"]
mainda["amhe"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhesu"] = mainda["aha,m"]
mainda["aha,m"] = mainda["aha,m"]
mainda["ma,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayi"] = mainda["aha,m"]
mainda["maya,m"] = mainda["aha,m"]
mainda["amhe"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhesu"] = mainda["aha,m"]
mainda["aha,m"] = mainda["aha,m"]
mainda["ma,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayaa"] = mainda["aha,m"]
mainda["mama"] = mainda["aha,m"]
mainda["mama,m"] = mainda["aha,m"]
mainda["mayha,m"] = mainda["aha,m"]
mainda["mayi"] = mainda["aha,m"]
mainda["maya,m"] = mainda["aha,m"]
mainda["amhe"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhehi"] = mainda["aha,m"]
mainda["amhaaka,m"] = mainda["aha,m"]
mainda["no"] = mainda["aha,m"]
mainda["asmaakam"] = mainda["aha,m"]
mainda["amhesu"] = mainda["aha,m"]

mainda["tumha"] = mainda["tuva,m"]
mainda["tayaa"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayaa"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayi"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]
mainda["vo"] = mainda["tumha"]
mainda["tumhehi"] = mainda["tumha"]
mainda["tuyha,m"] = mainda["tumha"]

mainda["tumhaaka,m"] = mainda["tumha"]


mainda["tumhehi"] = mainda["tumha"]

mainda["tumha,m"] = mainda["tumha"]


mainda["tumhesu"] = mainda["tumha"]
mainda["ta,mz1"] = mainda["tumha"]
mainda["tayaa"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayaa"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayi"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]

mainda["tumhehi"] = mainda["tumha"]




mainda["tumhehi"] = mainda["tumha"]



mainda["tumhesu"] = mainda["tumha"]
mainda["tayaa"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayaa"] = mainda["tumha"]
mainda["tava"] = mainda["tumha"]
mainda["te"] = mainda["tumha"]
mainda["tayi"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]
mainda["tumhe"] = mainda["tumha"]

mainda["tumhehi"] = mainda["tumha"]




mainda["tumhehi"] = mainda["tumha"]



mainda["tumhesu"] = mainda["tumha"]

mainda["asu"] = mainda["amu"]
mainda["amunaa"] = mainda["amu"]
mainda["amussa"] = mainda["amu"]
mainda["amumhaa"] = mainda["amu"]
mainda["amussa"] = mainda["amu"]
mainda["amusmi,m"] = mainda["amu"]
mainda["amuu"] = mainda["amu"]
mainda["amuu"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["adu,m"] = mainda["amu"]
mainda["adu,m"] = mainda["amu"]
mainda["amunaa"] = mainda["amu"]
mainda["amussa"] = mainda["amu"]
mainda["amumhaa"] = mainda["amu"]
mainda["amussa"] = mainda["amu"]
mainda["amusmi,m"] = mainda["amu"]
mainda["amuuni"] = mainda["amu"]
mainda["amuuni"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["asu"] = mainda["amu"]
mainda["asu"] = mainda["amu"]
mainda["amussaa"] = mainda["amu"]
mainda["amussaa"] = mainda["amu"]
mainda["amussa,m"] = mainda["amu"]
mainda["amuu"] = mainda["amu"]
mainda["amuu"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["amuuhi"] = mainda["amu"]
mainda["amuusa,m"] = mainda["amu"]
mainda["ena,m"] = mainda["ena"]

mainda["mahaaraajaa"] = mainda["mahaaraajaa"]
mainda["mahaaraaja"] = mainda["mahaaraajaa"]
mainda["mahaaraajaa,m"] = mainda["mahaaraajaa"]
mainda["mahaaraajena"] = mainda["mahaaraajaa"]
mainda["mahaaraajassa"] = mainda["mahaaraajaa"]
mainda["mahaaraajaa"] = mainda["mahaaraajaa"]
mainda["mahaaraajassa"] = mainda["mahaaraajaa"]
mainda["mahaaraaje"] = mainda["mahaaraajaa"]
mainda["mahaaraajaa"] = mainda["mahaaraajaa"]
mainda["mahaaraajaano"] = mainda["mahaaraajaa"]
mainda["mahaaraaje"] = mainda["mahaaraajaa"]
mainda["mahaaraajehi"] = mainda["mahaaraajaa"]
mainda["mahaaraajaana,m"] = mainda["mahaaraajaa"]
mainda["mahaaraajehi"] = mainda["mahaaraajaa"]
mainda["mahaaraajaana,m"] = mainda["mahaaraajaa"]
mainda["mahaaraajesu"] = mainda["mahaaraajaa"]
mainda["candimaa"] = mainda["candimaa"]
mainda["eko"] = mainda["eka"]
mainda["eka,m"] = mainda["eka"]
mainda["ekena"] = mainda["eka"]
mainda["ekassa"] = mainda["eka"]
mainda["ekasmaa"] = mainda["eka"]
mainda["ekamhaa"] = mainda["eka"]
mainda["ekassa"] = mainda["eka"]
mainda["ekasmi,m"] = mainda["eka"]
mainda["ekamhi"] = mainda["eka"]
mainda["eke"] = mainda["eka"]
mainda["eke"] = mainda["eka"]
mainda["ekehi"] = mainda["eka"]
mainda["ekesa,m"] = mainda["eka"]
mainda["ekehi"] = mainda["eka"]
mainda["ekesa,m"] = mainda["eka"]
mainda["ekesu"] = mainda["eka"]
mainda["eka,m"] = mainda["eka"]
mainda["eka,m"] = mainda["eka"]
mainda["ekena"] = mainda["eka"]
mainda["ekassa"] = mainda["eka"]
mainda["ekasmaa"] = mainda["eka"]
mainda["ekamhaa"] = mainda["eka"]
mainda["ko ci"] = mainda["ko ci"]
mainda["ka~n ci"] = mainda["ko ci"]
mainda["kena ci"] = mainda["ko ci"]
mainda["kassa ci"] = mainda["ko ci"]
mainda["kissa ci"] = mainda["ko ci"]
mainda["kasmaa ci"] = mainda["ko ci"]
mainda["kamhaa ci"] = mainda["ko ci"]
mainda["kassa ci"] = mainda["ko ci"]
mainda["kissa ci"] = mainda["ko ci"]
mainda["kismi~n ci"] = mainda["ko ci"]
mainda["kimhi ci"] = mainda["ko ci"]
mainda["ke ci"] = mainda["ko ci"]
mainda["ke ci"] = mainda["ko ci"]
mainda["kehi ci"] = mainda["ko ci"]
mainda["kesa,m ci"] = mainda["ko ci"]
mainda["kehi ci"] = mainda["ko ci"]
mainda["kesa,m ci"] = mainda["ko ci"]
mainda["kesu ci"] = mainda["ko ci"]
mainda["ki~n ci"] = mainda["ko ci"]
mainda["ki~n ci"] = mainda["ko ci"]
mainda["kena ci"] = mainda["ko ci"]
mainda["kassa ci"] = mainda["ko ci"]
mainda["kissa ci"] = mainda["ko ci"]
mainda["kasmaa ci"] = mainda["ko ci"]
mainda["kamhaa ci"] = mainda["ko ci"]
mainda["kassa ci"] = mainda["ko ci"]
mainda["kissa ci"] = mainda["ko ci"]
mainda["kismi~n ci"] = mainda["ko ci"]
mainda["kimhi ci"] = mainda["ko ci"]
mainda["kaani ci"] = mainda["ko ci"]
mainda["kaani ci"] = mainda["ko ci"]
mainda["kehi ci"] = mainda["ko ci"]
mainda["kesa~n ci"] = mainda["ko ci"]
mainda["kehi ci"] = mainda["ko ci"]
mainda["kesa~n ci"] = mainda["ko ci"]
mainda["kesu ci"] = mainda["ko ci"]
mainda["kaa ci"] = mainda["ko ci"]
mainda["ka,m ci"] = mainda["ko ci"]
mainda["kaaya ci"] = mainda["ko ci"]
mainda["kassaa ci"] = mainda["ko ci"]
mainda["kaaya ci"] = mainda["ko ci"]
mainda["kassaa ci"] = mainda["ko ci"]
mainda["kaaya ci"] = mainda["ko ci"]
mainda["kaaya~n ci"] = mainda["ko ci"]
mainda["kassa~n ci"] = mainda["ko ci"]
mainda["kaa ci"] = mainda["ko ci"]
mainda["kaa ci"] = mainda["ko ci"]
mainda["kaahi ci"] = mainda["ko ci"]
mainda["kaasa~n ci"] = mainda["ko ci"]
mainda["kaahi ci"] = mainda["ko ci"]
mainda["kaasa~n ci"] = mainda["ko ci"]
mainda["kaasu ci"] = mainda["ko ci"]
mainda["na ko ci"] = mainda["na ki~n ci"]
mainda["na ka,m ci"] = mainda["na ki~n ci"]
mainda["ekassa"] = mainda["eka"]
mainda["ekasmi,m"] = mainda["eka"]
mainda["ekamhi"] = mainda["eka"]
mainda["ekaani"] = mainda["eka"]

mainda["ubhohi"] = mainda["ubha"]
mainda["ubhinna,m"] = mainda["ubha"]
mainda["ubhosu"] = mainda["ubha"]
mainda["ubhayo"] = mainda["ubha"]

mainda["bhavanto"] = mainda["bhavanta"]
mainda["bhonto"] = mainda["bhavanta"]
mainda["bhavante"] = mainda["bhavanta"]
mainda["bhavantehi"] = mainda["bhavanta"]
mainda["bhavata,m"] = mainda["bhavanta"]
mainda["bhavantehi"] = mainda["bhavanta"]
mainda["bhavata,m"] = mainda["bhavanta"]
mainda["bhavantesu"] = mainda["bhavanta"]
mainda["bhotii"] = mainda["bhavanta"]
mainda["bhoti"] = mainda["bhavanta"]
mainda["bhoti,m"] = mainda["bhavanta"]
mainda["bhotiyaa"] = mainda["bhavanta"]
mainda["bhotiya,m"] = mainda["bhavanta"]
mainda["bhotiyo"] = mainda["bhavanta"]
mainda["bhotiihi"] = mainda["bhavanta"]
mainda["bhotiina,m"] = mainda["bhavanta"]
mainda["bhotiisu"] = mainda["bhavanta"]
mainda["atta"] = mainda["attaz3"]
mainda["attaa"] = mainda["atta"]
mainda["attaana,m"] = mainda["atta"]
mainda["attanaa"] = mainda["atta"]
mainda["attano"] = mainda["atta"]
mainda["attanaa"] = mainda["atta"]
mainda["attani"] = mainda["atta"]
mainda["attaano"] = mainda["atta"]
mainda["attaano"] = mainda["atta"]
mainda["attaano"] = mainda["atta"]
mainda["attehi"] = mainda["atta"]
mainda["attaana,m"] = mainda["atta"]
mainda["attehi"] = mainda["atta"]
mainda["attaana,m"] = mainda["atta"]
mainda["attanesu"] = mainda["atta"]

mainda["brahmaa"] = mainda["brahma"]
mainda["brahme"] = mainda["brahma"]
mainda["brahmaana,m"] = mainda["brahma"]
mainda["brahmunaa"] = mainda["brahma"]
mainda["brahmuno"] = mainda["brahma"]
mainda["brahmunaa"] = mainda["brahma"]
mainda["brahmuno"] = mainda["brahma"]
mainda["brahmani"] = mainda["brahma"]
mainda["brahmaano"] = mainda["brahma"]
mainda["brahmaano"] = mainda["brahma"]
mainda["brahmaano"] = mainda["brahma"]
mainda["brahmehi"] = mainda["brahma"]
mainda["brahmaana,m"] = mainda["brahma"]
mainda["brahmehi"] = mainda["brahma"]
mainda["brahmaana,m"] = mainda["brahma"]
mainda["brahmanesu"] = mainda["brahma"]

mainda["yuvaa"] = mainda["yuva"]
mainda["kammunaa"] = mainda["kamma"]
mainda["kammanaa"] = mainda["kamma"]
mainda["kammuno"] = mainda["kamma"]
mainda["kammaa"] = mainda["kamma"]
mainda["kammasmaa"] = mainda["kamma"]
mainda["kammamhaa"] = mainda["kamma"]
mainda["kammunaa"] = mainda["kamma"]
mainda["kammanaa"] = mainda["kamma"]
mainda["kammato"] = mainda["kamma"]
mainda["kammassa"] = mainda["kamma"]
mainda["kammuno"] = mainda["kamma"]
mainda["kamme"] = mainda["kamma"]
mainda["kammasmi,m"] = mainda["kamma"]
mainda["kammani"] = mainda["kamma"]
mainda["kammaani"] = mainda["kamma"]
mainda["kammaani"] = mainda["kamma"]
mainda["kammehi"] = mainda["kamma"]
mainda["kammaana,m"] = mainda["kamma"]
mainda["kammehi"] = mainda["kamma"]
mainda["kammaana,m"] = mainda["kamma"]
mainda["kammesu"] = mainda["kamma"]

mainda["tayo"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["ti,n,na,m"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["ti,n,na,m"] = mainda["taya"]
mainda["tiisu"] = mainda["taya"]
mainda["tii,ni"] = mainda["taya"]
mainda["ti,ni"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["ti,n,na,m"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["ti,n,na,m"] = mainda["taya"]
mainda["tiisu"] = mainda["taya"]
mainda["tisso"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["tissanna,m"] = mainda["taya"]
mainda["tiihi"] = mainda["taya"]
mainda["tissanna,m"] = mainda["taya"]
mainda["tiisu"] = mainda["taya"]

mainda["pa~ncahi"] = mainda["pa~nca"]
mainda["pa~ncasu"] = mainda["pa~nca"]


mainda["ubho"] = mainda["ubho"]
mainda["ubho"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhosu"] = mainda["ubho"]
mainda["ubho"] = mainda["ubho"]
mainda["ubho"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhosu"] = mainda["ubho"]
mainda["ubho"] = mainda["ubho"]
mainda["ubho"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhohi"] = mainda["ubho"]
mainda["ubhinna,m"] = mainda["ubho"]
mainda["ubhosu"] = mainda["ubho"]
mainda["yaavatako"] = mainda["yaavataka"]
mainda["yaavataka,m"] = mainda["yaavataka"]
mainda["yaavatakena"] = mainda["yaavataka"]
mainda["yaavatakaaya"] = mainda["yaavataka"]
mainda["yaavatakassa"] = mainda["yaavataka"]
mainda["yaavatakaa"] = mainda["yaavataka"]
mainda["yaavatakasmaa"] = mainda["yaavataka"]
mainda["yaavatakamhaa"] = mainda["yaavataka"]
mainda["yaavatakato"] = mainda["yaavataka"]
mainda["yaavatakassa"] = mainda["yaavataka"]
mainda["yaavatake"] = mainda["yaavataka"]
mainda["yaavatakasmi,m"] = mainda["yaavataka"]
mainda["yaavatakaa"] = mainda["yaavataka"]
mainda["yaavatake"] = mainda["yaavataka"]
mainda["yaavatakehi"] = mainda["yaavataka"]
mainda["yaavatakaana,m"] = mainda["yaavataka"]
mainda["yaavatakehi"] = mainda["yaavataka"]
mainda["yaavatakaana,m"] = mainda["yaavataka"]
mainda["yaavatakesu"] = mainda["yaavataka"]
mainda["yaavataka,m"] = mainda["yaavataka"]
mainda["yaavataka,m"] = mainda["yaavataka"]
mainda["yaavatakena"] = mainda["yaavataka"]
mainda["yaavatakaaya"] = mainda["yaavataka"]
mainda["yaavatakassa"] = mainda["yaavataka"]
mainda["yaavatakaa"] = mainda["yaavataka"]
mainda["yaavatakasmaa"] = mainda["yaavataka"]
mainda["yaavatakamhaa"] = mainda["yaavataka"]
mainda["yaavatakato"] = mainda["yaavataka"]
mainda["yaavatakassa"] = mainda["yaavataka"]
mainda["yaavatake"] = mainda["yaavataka"]
mainda["yaavatakasmi,m"] = mainda["yaavataka"]
mainda["yaavatakaani"] = mainda["yaavataka"]
mainda["yaavatakaani"] = mainda["yaavataka"]
mainda["yaavatakehi"] = mainda["yaavataka"]
mainda["yaavatakaana,m"] = mainda["yaavataka"]
mainda["yaavatakehi"] = mainda["yaavataka"]
mainda["yaavatakaana,m"] = mainda["yaavataka"]
mainda["yaavatakesu"] = mainda["yaavataka"]
mainda["yaavatikaa"] = mainda["yaavataka"]
mainda["yaavatika,m"] = mainda["yaavataka"]
mainda["yaavatikaaya"] = mainda["yaavataka"]
mainda["yaavatikaaya"] = mainda["yaavataka"]
mainda["yaavatikaaya"] = mainda["yaavataka"]
mainda["yaavatikaaya"] = mainda["yaavataka"]
mainda["yaavatikaaya"] = mainda["yaavataka"]
mainda["yaavatikaaya,m"] = mainda["yaavataka"]
mainda["yaavatikaayo"] = mainda["yaavataka"]
mainda["yaavatikaa"] = mainda["yaavataka"]
mainda["yaavatikaayo"] = mainda["yaavataka"]
mainda["yaavatikaa"] = mainda["yaavataka"]
mainda["yaavatikaahi"] = mainda["yaavataka"]
mainda["yaavatikaana,m"] = mainda["yaavataka"]
mainda["yaavatikaahi"] = mainda["yaavataka"]
mainda["yaavatikaana,m"] = mainda["yaavataka"]
mainda["yaavatikaasu"] = mainda["yaavataka"]
mainda["gava,m"] = mainda["go"]
mainda["gopa"] = mainda["go"] // added
mainda["gavena"] = mainda["go"]
mainda["gavassa"] = mainda["go"]
mainda["gavaa"] = mainda["go"]
mainda["gavassa"] = mainda["go"]
mainda["gave"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gohi"] = mainda["go"]
mainda["gunna,m"] = mainda["go"]
mainda["gohi"] = mainda["go"]
mainda["gunna,m"] = mainda["go"]
mainda["gava,m"] = mainda["go"]
mainda["gosu"] = mainda["go"]
mainda["gava,m"] = mainda["go"]
mainda["gavena"] = mainda["go"]
mainda["gavassa"] = mainda["go"]
mainda["gavaa"] = mainda["go"]
mainda["gavassa"] = mainda["go"]
mainda["gave"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gaavo"] = mainda["go"]
mainda["gohi"] = mainda["go"]
mainda["gunna,m"] = mainda["go"]
mainda["gohi"] = mainda["go"]
mainda["gunna,m"] = mainda["go"]
mainda["gava,m"] = mainda["go"]
mainda["gosu"] = mainda["go"]
mainda["sakhaa"] = mainda["sakha"]
mainda["sakhaa"] = mainda["sakha"]
mainda["sakhaara,m"] = mainda["sakha"]
mainda["sakhinaa"] = mainda["sakha"]
mainda["sakhino"] = mainda["sakha"]
mainda["sakhinaa"] = mainda["sakha"]
mainda["sakhaarasmaa"] = mainda["sakha"]
mainda["sakhino"] = mainda["sakha"]
mainda["sakhe"] = mainda["sakha"]
mainda["sakhaaro"] = mainda["sakha"]
mainda["sakhaaro"] = mainda["sakha"]
mainda["sakhaaro"] = mainda["sakha"]
mainda["sakhaarehi"] = mainda["sakha"]
mainda["sakhiina,m"] = mainda["sakha"]
mainda["sakhaarehi"] = mainda["sakha"]
mainda["sakhiina,m"] = mainda["sakha"]
mainda["sakhaaresu"] = mainda["sakha"]
mainda["bhaanumaa"] = mainda["bhaanumantu"]
mainda["bhaanuma,m"] = mainda["bhaanumantu"]
mainda["agghanako"] = mainda["agghanaka"]
mainda["agghanaka,m"] = mainda["agghanaka"]
mainda["agghanakena"] = mainda["agghanaka"]
mainda["agghanakaaya"] = mainda["agghanaka"]
mainda["agghanakassa"] = mainda["agghanaka"]
mainda["agghanakaa"] = mainda["agghanaka"]
mainda["agghanakasmaa"] = mainda["agghanaka"]
mainda["agghanakassa"] = mainda["agghanaka"]
mainda["agghanake"] = mainda["agghanaka"]
mainda["agghanakasmi,m"] = mainda["agghanaka"]
mainda["agghanakaa"] = mainda["agghanaka"]
mainda["agghanake"] = mainda["agghanaka"]
mainda["agghanakehi"] = mainda["agghanaka"]
mainda["agghanakaana,m"] = mainda["agghanaka"]
mainda["agghanakehi"] = mainda["agghanaka"]
mainda["agghanakaana,m"] = mainda["agghanaka"]
mainda["agghanakesu"] = mainda["agghanaka"]
mainda["agghanaka,m"] = mainda["agghanaka"]
mainda["agghanaka,m"] = mainda["agghanaka"]
mainda["agghanakena"] = mainda["agghanaka"]
mainda["agghanakaaya"] = mainda["agghanaka"]
mainda["agghanakassa"] = mainda["agghanaka"]
mainda["agghanakaa"] = mainda["agghanaka"]
mainda["agghanakasmaa"] = mainda["agghanaka"]
mainda["agghanakassa"] = mainda["agghanaka"]
mainda["agghanake"] = mainda["agghanaka"]
mainda["agghanakasmi,m"] = mainda["agghanaka"]
mainda["agghanakaani"] = mainda["agghanaka"]
mainda["agghanakaani"] = mainda["agghanaka"]
mainda["agghanakehi"] = mainda["agghanaka"]
mainda["agghanakaana,m"] = mainda["agghanaka"]
mainda["agghanakehi"] = mainda["agghanaka"]
mainda["agghanakaana,m"] = mainda["agghanaka"]
mainda["agghanakesu"] = mainda["agghanaka"]
mainda["agghanikaa"] = mainda["agghanaka"]
mainda["agghanika,m"] = mainda["agghanaka"]
mainda["agghanikaaya"] = mainda["agghanaka"]
mainda["agghanikaaya"] = mainda["agghanaka"]
mainda["agghanikaaya"] = mainda["agghanaka"]
mainda["agghanikaaya"] = mainda["agghanaka"]
mainda["agghanikaaya"] = mainda["agghanaka"]
mainda["agghanikaaya,m"] = mainda["agghanaka"]
mainda["agghanikaayo"] = mainda["agghanaka"]
mainda["agghanikaa"] = mainda["agghanaka"]
mainda["agghanikaayo"] = mainda["agghanaka"]
mainda["agghanikaa"] = mainda["agghanaka"]
mainda["agghanikaahi"] = mainda["agghanaka"]
mainda["agghanikaana,m"] = mainda["agghanaka"]
mainda["agghanikaahi"] = mainda["agghanaka"]
mainda["agghanikaana,m"] = mainda["agghanaka"]
mainda["agghanikaasu"] = mainda["agghanaka"]
mainda["asmaa"] = mainda["asmaa"]
mainda["asmanaa"] = mainda["asmaa"]
mainda["asmena"] = mainda["asmaa"]
mainda["asmani"] = mainda["asmaa"]
mainda["katamo"] = mainda["katama"]
mainda["katama,m"] = mainda["katama"]
mainda["katamena"] = mainda["katama"]
mainda["katamassa"] = mainda["katama"]
mainda["katamasmaa"] = mainda["katama"]
mainda["katamamhaa"] = mainda["katama"]
mainda["katamassa"] = mainda["katama"]
mainda["katamasmi,m"] = mainda["katama"]
mainda["katamamhi"] = mainda["katama"]
mainda["katame"] = mainda["katama"]
mainda["katame"] = mainda["katama"]
mainda["katamehi"] = mainda["katama"]
mainda["katamesa,m"] = mainda["katama"]
mainda["katamehi"] = mainda["katama"]
mainda["katamesa,m"] = mainda["katama"]
mainda["katamesaana,m"] = mainda["katama"]
mainda["katamesu"] = mainda["katama"]
mainda["katama,m"] = mainda["katama"]
mainda["katama,m"] = mainda["katama"]
mainda["katamena"] = mainda["katama"]
mainda["katamassa"] = mainda["katama"]
mainda["katamasmaa"] = mainda["katama"]
mainda["katamamhaa"] = mainda["katama"]
mainda["katamassa"] = mainda["katama"]
mainda["katamasmi,m"] = mainda["katama"]
mainda["katamamhi"] = mainda["katama"]
mainda["katamaani"] = mainda["katama"]
mainda["katamaani"] = mainda["katama"]
mainda["katamehi"] = mainda["katama"]
mainda["katamesa,m"] = mainda["katama"]
mainda["katamehi"] = mainda["katama"]
mainda["katamesa,m"] = mainda["katama"]
mainda["katamesu"] = mainda["katama"]
mainda["katamaa"] = mainda["katama"]
mainda["katama,m"] = mainda["katama"]
mainda["katamaaya"] = mainda["katama"]
mainda["katamassaa"] = mainda["katama"]
mainda["katamaaya"] = mainda["katama"]
mainda["katamassaa"] = mainda["katama"]
mainda["katamaaya"] = mainda["katama"]
mainda["katamassa,m"] = mainda["katama"]
mainda["katamaa"] = mainda["katama"]
mainda["katamaa"] = mainda["katama"]
mainda["katamaahi"] = mainda["katama"]
mainda["katamaasa,m"] = mainda["katama"]
mainda["katamaahi"] = mainda["katama"]
mainda["katamaasa,m"] = mainda["katama"]
mainda["katamaasu"] = mainda["katama"]
mainda["odako"] = mainda["odaka"]
mainda["odaka,m"] = mainda["odaka"]
mainda["odakena"] = mainda["odaka"]
mainda["odakaaya"] = mainda["odaka"]
mainda["odakassa"] = mainda["odaka"]
mainda["odakaa"] = mainda["odaka"]
mainda["odakasmaa"] = mainda["odaka"]
mainda["odakassa"] = mainda["odaka"]
mainda["odake"] = mainda["odaka"]
mainda["odakasmi,m"] = mainda["odaka"]
mainda["odakaa"] = mainda["odaka"]
mainda["odake"] = mainda["odaka"]
mainda["odakehi"] = mainda["odaka"]
mainda["odakaana,m"] = mainda["odaka"]
mainda["odakehi"] = mainda["odaka"]
mainda["odakaana,m"] = mainda["odaka"]
mainda["odakesu"] = mainda["odaka"]
mainda["odaka,m"] = mainda["odaka"]
mainda["odaka,m"] = mainda["odaka"]
mainda["odakena"] = mainda["odaka"]
mainda["odakaaya"] = mainda["odaka"]
mainda["odakassa"] = mainda["odaka"]
mainda["odakaa"] = mainda["odaka"]
mainda["odakasmaa"] = mainda["odaka"]
mainda["odakassa"] = mainda["odaka"]
mainda["odake"] = mainda["odaka"]
mainda["odakasmi,m"] = mainda["odaka"]
mainda["odakaani"] = mainda["odaka"]
mainda["odakaani"] = mainda["odaka"]
mainda["odakehi"] = mainda["odaka"]
mainda["odakaana,m"] = mainda["odaka"]
mainda["odakehi"] = mainda["odaka"]
mainda["odakaana,m"] = mainda["odaka"]
mainda["odakesu"] = mainda["odaka"]
mainda["odikaa"] = mainda["odaka"]
mainda["odika,m"] = mainda["odaka"]
mainda["odikaaya"] = mainda["odaka"]
mainda["odikaaya"] = mainda["odaka"]
mainda["odikaaya"] = mainda["odaka"]
mainda["odikaaya"] = mainda["odaka"]
mainda["odikaaya"] = mainda["odaka"]
mainda["odikaaya,m"] = mainda["odaka"]
mainda["odikaayo"] = mainda["odaka"]
mainda["odikaa"] = mainda["odaka"]
mainda["odikaayo"] = mainda["odaka"]
mainda["odikaa"] = mainda["odaka"]
mainda["odikaahi"] = mainda["odaka"]
mainda["odikaana,m"] = mainda["odaka"]
mainda["odikaahi"] = mainda["odaka"]
mainda["odikaana,m"] = mainda["odaka"]
mainda["odikaasu"] = mainda["odaka"]

/*

mainda["santo"] = mainda["santa"]
mainda["satiz2"] = mainda["santa"]
mainda["sante"] = mainda["santa"]
mainda["santo"] = mainda["santa"]
mainda["sante"] = mainda["santa"]
mainda["sabbhi"] = mainda["santa"]
mainda["sata,m"] = mainda["santa"]
mainda["santesu"] = mainda["santa"]
mainda["santa,m"] = mainda["santa"]
mainda["santa,m"] = mainda["santa"]
mainda["sata,m"] = mainda["santa"]
mainda["sataa"] = mainda["santa"]
mainda["santato"] = mainda["santa"]

mainda["santaani"] = mainda["santa"]
mainda["sabbhi"] = mainda["santa"]
mainda["sata,m"] = mainda["santa"]
mainda["santesu"] = mainda["santa"]
mainda["satii"] = mainda["santa"]
mainda["sati,m"] = mainda["santa"]

mainda["satiyaa"] = mainda["santa"]
mainda["satiya,m"] = mainda["santa"]
mainda["satiyo"] = mainda["santa"]
mainda["satiihi"] = mainda["santa"]
mainda["satiina,m"] = mainda["santa"]
mainda["satiihi"] = mainda["santa"]
mainda["satiina,m"] = mainda["santa"]
mainda["satiisu"] = mainda["santa"]

*/

mainda["jaati,m"] = mainda["jaati"]
mainda["jaatiyaa"] = mainda["jaati"]
mainda["jaccaa"] = mainda["jaati"]
mainda["jaatiyaa"] = mainda["jaati"]
mainda["jaccaa"] = mainda["jaati"]
mainda["jaatiyaa"] = mainda["jaati"]
mainda["jaccaa"] = mainda["jaati"]
mainda["jaatiyaa"] = mainda["jaati"]
mainda["jaccaa"] = mainda["jaati"]
mainda["jaatiyaa"] = mainda["jaati"]
mainda["jaatiya,m"] = mainda["jaati"]
mainda["jaatiyo"] = mainda["jaati"]
mainda["jaatiyo"] = mainda["jaati"]
mainda["jaatiyo"] = mainda["jaati"]
mainda["jaatiihi"] = mainda["jaati"]
mainda["jaatiina,m"] = mainda["jaati"]
mainda["jaatiihi"] = mainda["jaati"]
mainda["jaatiina,m"] = mainda["jaati"]
mainda["jaatiisu"] = mainda["jaati"]
mainda["brahaa"] = mainda["brahanta"]
mainda["brahanta,m"] = mainda["brahanta"]
mainda["brahantaa"] = mainda["brahanta"]
mainda["brahatii"] = mainda["brahanta"]
mainda["candimaa"] = mainda["candimantu"]
mainda["catubba,n,naa"] = mainda["catubba,n,naa"]
mainda["catubba,n,ne"] = mainda["catubba,n,naa"]
mainda["catubba,n,nehi"] = mainda["catubba,n,naa"]
mainda["catubba,n,naana,m"] = mainda["catubba,n,naa"]
mainda["catubba,n,nehi"] = mainda["catubba,n,naa"]
mainda["catubba,n,naana,m"] = mainda["catubba,n,naa"]
mainda["catubba,n,nesu"] = mainda["catubba,n,naa"]

mainda["ta"] = mainda["ta`"]
//mainda["sa"] = mainda["ta"]
mainda["ta,mz2"] = mainda["ta"]
mainda["ten`"] = mainda["ta"]
mainda["tesa,m"] = mainda["ta"]
mainda["tasmaa"] = mainda["ta"]
mainda["tad"] = mainda["ta"]

mainda["tassa,m"] = mainda["ta"]
mainda["taahi"] = mainda["ta"]

mainda["yesa,m"] = mainda["ya"]
mainda["yad"] = mainda["ya"]
mainda["yassaa"] = mainda["ya"]
mainda["yassa,m"] = mainda["ya"]
mainda["yaasa,m"] = mainda["ya"]



mainda["kissa"] = mainda["ka"]
mainda["kasmaa"] = mainda["ka"]
mainda["kamhaa"] = mainda["ka"]
mainda["kismi,m"] = mainda["ka"]
mainda["kimhi"] = mainda["ka"]

mainda["kehi"] = mainda["ka"]
mainda["kesa,m"] = mainda["ka"]
mainda["kehi"] = mainda["ka"]
mainda["kesa,m"] = mainda["ka"]
mainda["kesu"] = mainda["ka"]

mainda["ki,m"] = mainda["ka"]
mainda["kaani"] = mainda["ka"]

mainda["kaa"] = mainda["ka"]
mainda["ka,m"] = mainda["ka"]
mainda["kaayaz2"] = mainda["ka"] // changed
mainda["kassaa"] = mainda["ka"]

mainda["kaaya,m"] = mainda["ka"]
mainda["kassa,m"] = mainda["ka"]

mainda["kaahi"] = mainda["ka"]
mainda["kaasa,m"] = mainda["ka"]
mainda["kaasu"] = mainda["ka"]

mainda["eso"] = mainda["eta"]
mainda["esa"] = mainda["eta"]
mainda["eta,m"] = mainda["eta"]
mainda["etena"] = mainda["eta"]
mainda["etassa"] = mainda["eta"]
mainda["etasmaa"] = mainda["eta"]
mainda["etamhaa"] = mainda["eta"]
mainda["etassa"] = mainda["eta"]
mainda["etasmi,m"] = mainda["eta"]
mainda["etamhi"] = mainda["eta"]
mainda["ete"] = mainda["eta"]
mainda["etehi"] = mainda["eta"]
mainda["etesa,m"] = mainda["eta"]
mainda["etehi"] = mainda["eta"]
mainda["etesa,m"] = mainda["eta"]
mainda["etesu"] = mainda["eta"]
mainda["eta,m"] = mainda["eta"]
mainda["eta"] = mainda["etad"]
mainda["eta,m"] = mainda["eta"]

mainda["etena"] = mainda["eta"]
mainda["etassa"] = mainda["eta"]
mainda["etasmaa"] = mainda["eta"]
mainda["etamhaa"] = mainda["eta"]
mainda["etassa"] = mainda["eta"]
mainda["etasmi,m"] = mainda["eta"]
mainda["etamhi"] = mainda["eta"]
mainda["etaani"] = mainda["eta"]
mainda["etaani"] = mainda["eta"]
mainda["etehi"] = mainda["eta"]
mainda["etesa,m"] = mainda["eta"]
mainda["etehi"] = mainda["eta"]
mainda["etesa,m"] = mainda["eta"]
mainda["etesu"] = mainda["eta"]
mainda["esaa"] = mainda["eta"]
mainda["eta,m"] = mainda["eta"]
mainda["etaaya"] = mainda["eta"]
mainda["etassaa"] = mainda["eta"]
mainda["etaaya"] = mainda["eta"]
mainda["etassaa"] = mainda["eta"]
mainda["etaaya,m"] = mainda["eta"]
mainda["etaaya"] = mainda["eta"]
mainda["etassa,m"] = mainda["eta"]
mainda["etaa"] = mainda["eta"]
mainda["etaa"] = mainda["eta"]
mainda["etaahi"] = mainda["eta"]
mainda["etaasa,m"] = mainda["eta"]
mainda["etaahi"] = mainda["eta"]
mainda["etaasa,m"] = mainda["eta"]
mainda["etaasu"] = mainda["eta"]
mainda["ekaani"] = mainda["eka"]
mainda["ekehi"] = mainda["eka"]
mainda["ekesa,m"] = mainda["eka"]
mainda["ekehi"] = mainda["eka"]
mainda["ekesa,m"] = mainda["eka"]
mainda["ekesu"] = mainda["eka"]
mainda["ekissaa"] = mainda["eka"]
mainda["ekaasa,m"] = mainda["eka"]

mainda["ekesa,m"] = mainda["eka"]
mainda["ekissaa"] = mainda["eka"]
mainda["ekaahi"] = mainda["eka"]
mainda["ekaasa,m"] = mainda["eka"]
mainda["pa,tiraajaa"] = mainda["pa,tiraaja"]
mainda["pa,tiraajaana,m"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~naa"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~no"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~naa"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~no"] = mainda["pa,tiraaja"]
mainda["pa,tiraajini"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~ne"] = mainda["pa,tiraaja"]
mainda["pa,tiraajaano"] = mainda["pa,tiraaja"]
mainda["pa,tiraajaano"] = mainda["pa,tiraaja"]
mainda["pa,tiraajuuhi"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~na,m"] = mainda["pa,tiraaja"]
mainda["pa,tiraajuuhi"] = mainda["pa,tiraaja"]
mainda["pa,tira~n~na,m"] = mainda["pa,tiraaja"]
mainda["pa,tiraajuuna,m"] = mainda["pa,tiraaja"]
mainda["pa,tiraajuusu"] = mainda["pa,tiraaja"]

mainda["raajaana,m"] = mainda["raaja"]
mainda["ra~n~naa"] = mainda["raaja"]
mainda["ra~n~no"] = mainda["raaja"]
mainda["ra~n~naa"] = mainda["raaja"]
mainda["ra~n~no"] = mainda["raaja"]
mainda["raajini"] = mainda["raaja"]
mainda["ra~n~ne"] = mainda["raaja"]
mainda["raajaano"] = mainda["raaja"]
mainda["raajaano"] = mainda["raaja"]
mainda["raajuuhi"] = mainda["raaja"]
mainda["ra~n~na,m"] = mainda["raaja"]
mainda["raajuuhi"] = mainda["raaja"]
mainda["ra~n~na,m"] = mainda["raaja"]
mainda["raajuuna,m"] = mainda["raaja"]
mainda["raajuusu"] = mainda["raaja"]
mainda["bhikkhu"] = mainda["bhikkhu"]
mainda["bhikkhu"] = mainda["bhikkhu"]
mainda["bhikkhu,m"] = mainda["bhikkhu"]
mainda["bhikkhunaa"] = mainda["bhikkhu"]
mainda["bhikkhuno"] = mainda["bhikkhu"]
mainda["bhikkhunaa"] = mainda["bhikkhu"]
mainda["bhikkhuno"] = mainda["bhikkhu"]
mainda["bhikkhussa"] = mainda["bhikkhu"]
mainda["bhikkhusmi,m"] = mainda["bhikkhu"]
mainda["bhikkhavo"] = mainda["bhikkhu"]
mainda["bhikkhuu"] = mainda["bhikkhu"]
mainda["bhikkhavo"] = mainda["bhikkhu"]
mainda["bhikkhuu"] = mainda["bhikkhu"]
mainda["bhikkhave"] = mainda["bhikkhu"]
mainda["bhikkhavo"] = mainda["bhikkhu"]
mainda["bhikkhuu"] = mainda["bhikkhu"]
mainda["bhikkhuuhi"] = mainda["bhikkhu"]
mainda["bhikkhuuna,m"] = mainda["bhikkhu"]
mainda["bhikkhuuhi"] = mainda["bhikkhu"]
mainda["bhikkhuuna,m"] = mainda["bhikkhu"]
mainda["bhikkhuusu"] = mainda["bhikkhu"]
mainda["arahanta"] = mainda["arahant"]
mainda["arahaa"] = mainda["arahanta"]
mainda["araha,m"] = mainda["arahanta"]
mainda["arahanto"] = mainda["arahanta"]
mainda["arahaa"] = mainda["arahanta"]
mainda["arahanta,m"] = mainda["arahanta"]
mainda["arahataa"] = mainda["arahanta"]
mainda["arahantena"] = mainda["arahanta"]
mainda["arahato"] = mainda["arahanta"]
mainda["arahataa"] = mainda["arahanta"]
mainda["arahato"] = mainda["arahanta"]
mainda["arahantassa"] = mainda["arahanta"]
mainda["arahati"] = mainda["arahanta"]
mainda["arahante"] = mainda["arahanta"]
mainda["arahanto"] = mainda["arahanta"]
mainda["arahantaa"] = mainda["arahanta"]
mainda["arahanto"] = mainda["arahanta"]
mainda["arahante"] = mainda["arahanta"]
mainda["arahantehi"] = mainda["arahanta"]
mainda["arahantaana,m"] = mainda["arahanta"]
mainda["arahata,m"] = mainda["arahanta"]
mainda["arahantehi"] = mainda["arahanta"]
mainda["arahantaana,m"] = mainda["arahanta"]
mainda["arahata,m"] = mainda["arahanta"]
mainda["arahantesu"] = mainda["arahanta"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]
mainda["khattu"] = mainda["khattu"]

mainda["cattaaro"] = mainda["catu"]
mainda["cattaaro"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catusu"] = mainda["catu"]
mainda["catuusu"] = mainda["catu"]
mainda["cattaari"] = mainda["catu"]
mainda["cattaari"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catusu"] = mainda["catu"]
mainda["catuusu"] = mainda["catu"]
mainda["cattasso"] = mainda["catu"]
mainda["cattasso"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catuhi"] = mainda["catu"]
mainda["catuuhi"] = mainda["catu"]
mainda["catunna,m"] = mainda["catu"]
mainda["catusu"] = mainda["catu"]
mainda["catuusu"] = mainda["catu"]
mainda["addhaa"] = mainda["addhaa"]
mainda["addhaana,m"] = mainda["addhaa"]
mainda["addhunaa"] = mainda["addhaa"]
mainda["addhuno"] = mainda["addhaa"]
mainda["addhaa"] = mainda["addhaa"]
mainda["muddhaa"] = mainda["muddhaa"]
mainda["muddha,m"] = mainda["muddhaa"]
mainda["muddha,m"] = mainda["muddhaa"]
mainda["muddhaana,m"] = mainda["muddhaa"]
mainda["muddhanaa"] = mainda["muddhaa"]
mainda["muddhani"] = mainda["muddhaa"]
mainda["pumaa"] = mainda["puma"]
mainda["puma,m"] = mainda["puma"]
mainda["puma"] = mainda["puma"]
mainda["pumaana,m"] = mainda["puma"]
mainda["puma,m"] = mainda["puma"]
mainda["pumaanaa"] = mainda["puma"]
mainda["pumunaa"] = mainda["puma"]
mainda["pumena"] = mainda["puma"]
mainda["pumuno"] = mainda["puma"]
mainda["pumassa"] = mainda["puma"]
mainda["pumunaa"] = mainda["puma"]
mainda["pumaanaa"] = mainda["puma"]
mainda["pumaa"] = mainda["puma"]
mainda["pumasmaa"] = mainda["puma"]
mainda["pumamhaa"] = mainda["puma"]
mainda["pumuno"] = mainda["puma"]
mainda["pumassa"] = mainda["puma"]
mainda["pumaane"] = mainda["puma"]
mainda["pume"] = mainda["puma"]
mainda["pumasmi,m"] = mainda["puma"]
mainda["pumamhi"] = mainda["puma"]
mainda["pumaano"] = mainda["puma"]
mainda["pumaa"] = mainda["puma"]
mainda["pumaano"] = mainda["puma"]
mainda["pumaa"] = mainda["puma"]
mainda["pumaano"] = mainda["puma"]
mainda["pume"] = mainda["puma"]
mainda["pumaanehi"] = mainda["puma"]
mainda["pumaanebhi"] = mainda["puma"]
mainda["pumehi"] = mainda["puma"]
mainda["pumebhi"] = mainda["puma"]
mainda["pumaana,m"] = mainda["puma"]
mainda["pumaanehi"] = mainda["puma"]
mainda["pumaanebhi"] = mainda["puma"]
mainda["pumehi"] = mainda["puma"]
mainda["pumebhi"] = mainda["puma"]
mainda["pumaana,m"] = mainda["puma"]
mainda["pumaanesu"] = mainda["puma"]
mainda["pumaasu"] = mainda["puma"]
mainda["pumesu"] = mainda["puma"]
mainda["dve"] = mainda["dvi"]
mainda["dve"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviisu"] = mainda["dvi"]
mainda["dve"] = mainda["dvi"]
mainda["dve"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviisu"] = mainda["dvi"]
mainda["dve"] = mainda["dvi"]
mainda["dve"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviihi"] = mainda["dvi"]
mainda["dvinna,m"] = mainda["dvi"]
mainda["dviisu"] = mainda["dvi"]
mainda["bhava,m"] = mainda["bhavanta"]
mainda["bho"] = mainda["bhavanta"]
mainda["bhavanta,m"] = mainda["bhavanta"]
mainda["bhotaa"] = mainda["bhavanta"]
mainda["bhoto"] = mainda["bhavanta"]
mainda["bhotaa"] = mainda["bhavanta"]
mainda["bhoto"] = mainda["bhavanta"]
mainda["bhoti"] = mainda["bhavanta"]
