export * as BottomPane from '../features/bottom-pane/init.js'
export * as SettingsDialog from '../features/settings-dialog/init.js'
export * as OtherDialogs from '../features/other-dialogs/init.js'
export * as Installation from '../features/installation/init.js'
export * as Navigation from '../features/navigation/init.js'
export * as Search from '../features/search/init.js'
export * as Dictionary from '../features/dictionary/init.js'
